### ISSUE TITLE
Implement escape hatch mechanism contracts

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#1]
See: http://hackingdistributed.com/2016/07/11/decentralized-escape-hatches-for-smart-contracts/

**Comment by maraoz** [comment]
See also ideas in bitcoin covenants paper: http://fc16.ifca.ai/bitcoin/papers/MES16.pdf

**Comment by androolloyd** [comment]
the DEH is an interesting mechanism, and one that I will explore, is this still an active ticket?

**Comment by frangio** [comment]
Definitely! Go ahead. 😄

**Comment by elopio** [comment]
The [RefundVault](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.9.0/contracts/crowdsale/distribution/utils/RefundVault.sol) could be considered a escape hatch. We could generalize it to support different kinds of triggers.

**Comment by nventuro** [comment]
Closing - we probably don't want to provide such complex functionality out of the box, but rather the building blocks required to implement it: e.g. `RefundEscrow`, https://github.com/OpenZeppelin/openzeppelin-solidity/issues/239, etc.
