### ISSUE TITLE
Explore formal verification ideas

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#10]
I'm opening this issue to collect resources and ideas on formal verification on Zeppelin contracts.

I'll start with this paper, which uses F\* to formally verify Solidity contracts:
http://research.microsoft.com/en-us/um/people/nswamy/papers/solidether.pdf

**Comment by jeamick** [comment]
Hello @maraoz  What is the current state of this project ?

Thanks

JM

**Comment by nventuro** [comment]
Good formal verification tools are still lacking, so we will continue resorting to community feedback and external audits for the time being. Closing this to reduce the issue clutter.
