### ISSUE TITLE
Extra confirmation measure in `Ownable#renounceOwnership`

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-solidity#1000]
Consider adding an argument to `Ownable#renounceOwnership` (e.g. the contract address) as an extra confirmation measure that the step is desired, since it is a potentially risky operation.

Arguments against: every transaction in Ethereum should be treated as risky by interfaces, so we could consider that this should be solved at a different level.

**Comment by elopio** [comment]
Happy birthday @frangio. As a gift, you have the issue #1000!
With love from all the openzeppelin community.

**Comment by roschler** [comment]
Happy Birthday Francisco (@frangio)!

**Comment by martriay** [comment]
Happy birthday @frangio!

**Comment by frangio** [comment]
I discussed this offline with some people and I'm leaning towards the argument against:
> every transaction in Ethereum should be treated as risky by interfaces, so we could consider that this should be solved at a different level.

Closing.
