### ISSUE TITLE
Use explicit integer sizes

### ISSUE THREAD

**Issue by xareelee** [OpenZeppelin/openzeppelin-solidity#1003]
## 🎉 Description

- [x] 🐛 This is a bug report. (MAYBE)

I saw that this project uses `uint256` almost everywhere, but I found that it also uses `uint` in some cases:

* https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.10.0/contracts/token/ERC20/StandardToken.sol#L89
* https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.10.0/contracts/token/ERC20/StandardToken.sol#L112
* https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.10.0/contracts/token/ERC20/StandardToken.sol#L117

Why?

**Comment by DJXia** [comment]
Integers
int / uint: Signed and unsigned integers of various sizes. Keywords uint8 to uint256 in steps of 8 (unsigned of 8 up to 256 bits) and int8 to int256. uint and int are aliases for uint256 and int256, respectively.

**Comment by frangio** [comment]
We prefer the explicit `uint256`. These must have gotten in accidentally. We should change them. :slightly_smiling_face:
