### ISSUE TITLE
Add asyncTransfer in PullPayment

### ISSUE THREAD

**Issue by wanglingsong** [OpenZeppelin/openzeppelin-solidity#1011]
## 🎉 Description

- [x] 📈 This is a feature request.

## 📝 Details

Is it possible to add asyncTransfer method to allow payment transfer between payees?

```
    function asyncTransfer(address _from, address _to, uint256 amount) internal {
        payments[_from] = payments[_from].sub(amount);
        payments[_to] = payments[_to].add(amount);
    }
```

**Comment by frangio** [comment]
Hi @wanglingsong! Thank you for the suggestion.

We are working on a fix for #901 to make `PullPayment` more trustless, and unfortunately I don't think this feature will make sense after this fix.
