### ISSUE TITLE
Deploy openzeppelin-zos to kovan

### ISSUE THREAD

**Issue by ghostbuster91** [OpenZeppelin/openzeppelin-solidity#1012]
## 🎉 Description

Hi, right now  `openzeppelin-zos` is deployed on mainnet, ropsten and rinkeby but not on kovan. Since kovan uses POA it is much faster than other chains, and so more pleasant for development. 

- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

I know that it should be possible to deploy `openzeppelin-zos` to kovan using `zos` cli, simply invoking:  
`zos push --deploy-stdlib --network kovan` but there is a problem with that (https://github.com/zeppelinos/zos-cli/issues/256)

**Comment by frangio** [comment]
Thanks for reporting @ghostbuster91! Agreed that this was an oversight and we should publish on Kovan. 

I ported this issue over to the new repo specific to `openzeppelin-zos`. https://github.com/OpenZeppelin/openzeppelin-zos/issues/1
