### ISSUE TITLE
A small bug in comments

### ISSUE THREAD

**Issue by aleybovich** [OpenZeppelin/openzeppelin-solidity#1013]
## 🎉 Description
- [X ] 🐛 This is a bug report.

In `openzeppelin-solidity/contracts/token/ERC827/ERC827Token.sol` in the comment to `approveAndCall` method it states: 

```
* @param _data ABI-encoded contract call to call `_to` address.
```

It should be `_spender` instead of `_to` there as the actual argument name is `_spender`. 

## 💻 Environment

Current master

**Comment by frangio** [comment]
Thanks @aleybovich! It was fixed in #1007.
