### ISSUE TITLE
Add BigNumber support to expectEvent/inLogs

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1026]
* No support for BigNumbers
The current [equality test](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/test/helpers/expectEvent.js#L8) fails for BigNumber objects (which have an `equal` method). `chai-bignumber` supports these assertions with the chain `number.should.be.bignumber.equal(otherNumber`).

**Comment by nventuro** [comment]
Superceded by #1169 and #1189

**Comment by frangio** [comment]
Reopening because we have no issue to track supporting BigNumber equality in `expectEvent`.
