### ISSUE TITLE
onERC721Received operator parameter

### ISSUE THREAD

**Issue by mudgen** [OpenZeppelin/openzeppelin-solidity#1032]
The ERC721 standard changed today.  The `onERC721Received` function now has an additional operator parameter. This should be updated in Open Zepplin code so that it complies with the ERC721 standard.

**Comment by johnhforrest** [comment]
Has anyone started on this one? If not, I can take a stab.

For reference, here's the original PR with the breaking change: https://github.com/ethereum/EIPs/pull/1160/files

**Comment by johnhforrest** [comment]
Nevermind, looks like @paulbarclay is working on this here: https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1047

**Comment by shrugs** [comment]
solved in #1047
