### ISSUE TITLE
Issue calling approve/allowance/transferFrom functions of ERC20 contracts from other smart contracts

### ISSUE THREAD

**Issue by Bwest981** [OpenZeppelin/openzeppelin-solidity#1036]
Here is the code:
https://ethfiddle.com/eYFYAlAugn

Here are my steps:
Step 1: Deploy Simple Token
Step 2: Deploy Add Token Contract
Step 3: Set token contract to the Simple Token contract address
Step 4: Attempting to use the tokenApprove function("AddTokenContractAddress", 1000)
Step 5: Attempting to see the allowance by calling tokenAllowance function("Address I used to deploy","AddTokenContractAddress")

Issue => I expected 1000, but get 0 instead. WHY???

**Comment by junjchen** [comment]
I tried to repeat your steps but saw the following compilation errors
```
Error
:51:36: Warning: This looks like an address but has an invalid checksum. If this is not used as an address, please prepend '00'.
    address tokenContractAddress = 0x5a59796c3d6bc8612dca71559ace90bd419f19b9;
                                   ^----------------------------------------^
```

**Comment by komalsukhani** [comment]
approve(address _spender, uint256 _value) function of Simple Token will allow _spender to transfer tokens from **msg.sender** account.

When tokenApprove(AddTokenContractAddress,1000) calls approve() function, msg.sender gets changed to address of addToken contract. That means you are allowing AddTokenContractAddress to transfer token from AddTokenContractAddress itself.

You can verify that by calling tokenAllowance(AddTokenContractAddress,AddTokenContractAddress) 

So, there is nothing wrong with approve() function.

**Comment by frangio** [comment]
@Bwest981 You're missing a `return` statement in line 60:

```solidity
function tokenAllowance(address _owner, address _spender) public view returns(uint256){contractToken.allowance(_owner, _spender);}
```
