### ISSUE TITLE
I am not sure that's right, please help me 

### ISSUE THREAD

**Issue by liwei00wade** [OpenZeppelin/openzeppelin-solidity#1048]
feature request：
１、only the original 'owner' of the contract can mint tokens, and the address that receives the minted tokens can be chosen;
2、 any address can burn a token by itself.

-------------------

pragma solidity ^0.4.24;

//import "../token/ERC20/StandardToken.sol";
import "../token/ERC20/MintableToken.sol";
import "../token/ERC20/StandardBurnableToken.sol";

//contract ChildChain is MintableToken,StandardBurnableToken {

contract ChildChain is MintableToken,StandardBurnableToken{
  string public name = "TutorialToken";
  string public symbol = "TT";
  uint8 public decimals = 2;
  uint public INITIAL_SUPPLY = 12000;

  constructor() public {
    totalSupply_ = INITIAL_SUPPLY;
    balances[msg.sender] = INITIAL_SUPPLY;
  }
}

**Comment by frangio** [comment]
Hello @liwei00wade!

This kind of question is better suited to StackOverflow, or [our Slack community](https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1048).

However, it does look like you're implementing your desired feature set correctly.
