### ISSUE TITLE
how to find the problem ?

### ISSUE THREAD

**Issue by liwei00wade** [OpenZeppelin/openzeppelin-solidity#1049]
I am sure that it  is not executed when I receive the following receipt;
How to find the reason ?
-------------------------------------
 receipt:{
	"root": "0x8818873db3047ed5eff7ed135846b5d09128f479160e845238446e76c029b16c",
	"status": "0x0",
	"cumulativeGasUsed": "0x186a0",
	"logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
	"logs": [],
	"transactionHash": "0x7a50336d123364d9d1d32a828454b5aa613d69fa5868daf3783865a16aed9598",
	"contractAddress": "0x0000000000000000000000000000000000000000",
	"gasUsed": "0x186a0"

**Comment by frangio** [comment]
Hi @liwei00wade! This information is unfortunately not quite enough to debug your problem. I suggest asking your question in more detail in StackOverflow or [our Slack community](https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1048).
