### ISSUE TITLE
minor RBAC documentation error

### ISSUE THREAD

**Issue by cweiers** [OpenZeppelin/openzeppelin-solidity#1055]
In RBAC.sol, the @dev comment for the contract still says: 
* It's also recommended that you define constants in the contract, like ROLE_ADMIN below,
 * to avoid typos.

In the current version, ROLE_ADMIN is never defined anywhere in the contract. 
I suppose it was just overlooked when an inbuild admin role was removed (?). I briefly skipped over the history, but couldn't find the exact commit. Anyway,  it caused a minor moment of confusion for me, so I thought I should at least mention it. 

- [ ] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.
- [x] :monkey: This is some super minor nitpicking thats neither a bug nor a feature request

**Comment by junjchen** [comment]
Looks like it was overlooked when moving `RBACWithAdmin.sol` to `examples/`. This @dev comment belongs to that contract.
