### ISSUE TITLE
Cannot deploy a simple ERC721Token contract

### ISSUE THREAD

**Issue by such** [OpenZeppelin/openzeppelin-solidity#1058]
## 🎉 Description

I'm trying to run
```
truffle migrate
```

on this very simple project: https://github.com/such/test-openzeppelin-erc721

I'm running `Ganache CLI v6.1.4 (ganache-core: 2.1.3)` locally with default settings.

It fails with `Error: The contract code couldn't be stored, please check your gas amount.`

Increasing the gasLimit yields different errors (like `Error: sender doesn't have enough funds to send tx. The upfront cost isError: sender doesn't have enough funds to send tx. The upfront cost is...`) but it never goes through.

- [x ] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 💻 Environment

Next, we need to know what your environment looks like.

- Which version of OpenZeppelin are you using?
Tested with 1.10.0 and `master`
- What network are you deploying to? Ganache? Ropsten?
Ganache CLI
- How are you deploying your OpenZeppelin-backed contracts? truffle? Remix? Let us know!
Truffle

## 📝 Details

The gas required to deploy the contract seems huge and no sane configuration allows it.

## 🔢 Code To Reproduce Issue [ Good To Have ]

See project here: https://github.com/such/test-openzeppelin-erc721

```
git clone https://github.com/such/test-openzeppelin-erc721
npm install
npm install -g truffle
truffle migrate
```

**Comment by Emiller88** [comment]
Been having this issue for the past week. +1

**Comment by such** [comment]
My bad, I had missed that the ERC721Token constructor takes arguments.
This is solved with `contract Test is ERC721Token("Test", "Test")` by instance.
The error could be more helpful though but I guess this is not on OpenZeppelin.

**Comment by Emiller88** [comment]
@such Thanks! 
I expected the constructor to be at the top(Like mentioned in the [style guide](https://solidity.readthedocs.io/en/v0.4.24/style-guide.html#order-of-functions) guide, however, it was hidden under all the variables so I missed it. 

Hopefully, this issue helps anyone else in the future that has this issue. It appears it was added 2 months ago so that's why you don't see it in earlier ERC721 contracts that used it.
