### ISSUE TITLE
Permanent storage contract required

### ISSUE THREAD

**Issue by boxcee** [OpenZeppelin/openzeppelin-solidity#1066]
## 🎉 Description

As this article (https://medium.com/rocket-pool/upgradable-solidity-contract-design-54789205276d) mentions, I can imagine the necessity of a permanent storage solution to be able to update contracts while keeping data stored in contracts.

- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

## 🔢 Code To Reproduce Issue [ Good To Have ]

I recommend to integrate the storage contract from RocketPool.

[RocketPoolStorage.sol](https://github.com/rocket-pool/rocketpool/blob/master/contracts/RocketStorage.sol)

**Comment by frangio** [comment]
Hi @boxcee! Thanks for the suggestion.

This has been discussed before in #381, where we concluded to not have it in OpenZeppelin. We recommend the more general approach to upgradeability found in [ZeppelinOS](https://github.com/zeppelinos/zos-lib/).

**Comment by boxcee** [comment]
Thanks
