### ISSUE TITLE
Make ERC20 compliant with ERC-165

### ISSUE THREAD

**Issue by dougiebuckets** [OpenZeppelin/openzeppelin-solidity#1073]
## 🎉 Description

@shrugs Has done a nice job making ERC721 compliant w/ ERC-165: https://github.com/OpenZeppelin/openzeppelin-solidity/commit/259b9da3e6081c3c14f449cad83004d64c0b9cb7

 It would seem to make sense to do the same for ERC20, right? From the EIP:

"For some "standard interfaces" like the ERC-20 token interface, it is sometimes useful to query whether a contract supports the interface and if yes, which version of the interface, in order to adapt the way in which the contract is to be interacted with. Specifically for ERC-20, a version identifier has already been proposed. This proposal standardizes the concept of interfaces and standardizes the identification (naming) of interfaces."

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-165.md

- [x] 📈 This is a feature request.

**Comment by frangio** [comment]
After some consideration we decided not to implement this. We haven't received any _real_ requests for it, and "it would seem to make sense" does not justify the added cost and complexity of adding ERC165 to ERC20.

Thanks for the suggestion regardless @dougiebuckets!

**Comment by fulldecent** [comment]
It case anybody is still interested, the 0xcert Framework implementation of ERC-20 does support ERC-165. That is here https://github.com/0xcert/framework/tree/master/packages/0xcert-ethereum-erc20-contracts

And yes that effort was inspired by this issue opened here.

**Comment by thedavidmeister** [comment]
@frangio i would like to *really* request this, so that i can do checks ahead of time for users before deploying trading strategies that might rely on functions like `balanceOf`
