### ISSUE TITLE
Write a more comprehensive "Getting started" guide

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-solidity#1081]
We want to have an introductory guide for newcomers with all the information they need to get started using OpenZeppelin. There's currently a "Getting started" section in the README, but it only shows how to install the library, and how to import the `Ownable` contract.

We should have something more comprehensive that roughly shows the structure of the project, the different kinds of contracts and libraries we provide, and how to use and customize them.

This can hopefully become a page in the docsite.

**Comment by frangio** [comment]
@shrugs Do you think we can have this for [v1.12.0](https://github.com/OpenZeppelin/openzeppelin-solidity/milestone/2)?

**Comment by dougiebuckets** [comment]
Are you thinking content like [this](https://docs.google.com/document/d/1arinMRwG2k_Vsvg3eNA2GWOrpptuDxExkbeHZC93THI/edit) that could follow after the "Installing OpenZeppelin" section?

**Comment by frangio** [comment]
@dougiebuckets Yeah! 100% :smile: 

For the tests part there's already a guide planned (#1077).

**Comment by dougiebuckets** [comment]
OK, awesome. I should be able to get you guys something to review before the end of the week.
