### ISSUE TITLE
Add examples of extending _preValidatePurchase in Crowdsale.sol

### ISSUE THREAD

**Issue by vertangelx** [OpenZeppelin/openzeppelin-solidity#1096]
While reading through the `Crowdsale.sol` smart contract, I am wondering if someone can explain to me what this portion of the comments mean:

> Use super to concatenate validations.

What can be a reason for concatenating validations, and can we have an example of doing this?

https://github.com/OpenZeppelin/openzeppelin-solidity/blob/92b695f2fb258a5669181d1d8cf8e73aa756f22c/contracts/crowdsale/Crowdsale.sol#L110-L123

Thank you!

**Comment by frangio** [comment]
Thanks for bringing this up @vertangelx!

The inline documentation is lacking in this regard, it should have an example or use clearer language.

For an example, see `CappedCrowdsale`:

https://github.com/OpenZeppelin/openzeppelin-solidity/blob/5daaf60d11ee2075260d0f3adfb22b1c536db983/contracts/crowdsale/validation/CappedCrowdsale.sol#L38-L46

A precondition is added to the existing ones by overriding the function and using `super`.
