### ISSUE TITLE
Failed to build Solidity contract - "...MintableToken.sol" not found: File not found.

### ISSUE THREAD

**Issue by zulhfreelancer** [OpenZeppelin/openzeppelin-solidity#1111]
## 🎉 Description

I'm using openzeppelin-solidity inside my contract. `truffle compile` command runs smoothly and I managed to deploy my contract to Rinkeby without any issues.

But when I try to run `abigen` command, I got some errors. Details below.

- [x] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 💻 Environment

- Which version of OpenZeppelin are you using? = 1.11.0
- What network are you deploying to? = Ganache & Rinkeby, but it's not related to the problem
- How are you deploying your OpenZeppelin-backed contracts? = Truffle

## 📝 Details

When I ran `abigen --sol=ABCtoken.sol --pkg=main --out=ABCtoken.go` command, I got the following error:

```
Failed to build Solidity contract: solc: exit status 1
ABCtoken.sol:3:1: Error: Source "openzeppelin-solidity/contracts/token/ERC20/MintableToken.sol" not found: File not found.
import "openzeppelin-solidity/contracts/token/ERC20/MintableToken.sol";
^---------------------------------------------------------------------^
```

## 🔢 Code To Reproduce

1) Init a Truffle project.

2) Create a new contract. Name the file as _ABCtoken.sol_.

```
pragma solidity ^0.4.23;

import "openzeppelin-solidity/contracts/token/ERC20/MintableToken.sol";

contract ABCtoken is MintableToken {
  string public constant name = "ABCtoken";
  string public constant symbol = "ABC";
  uint8 public constant decimals = 18;

  constructor() public {
    // make the deployer rich
    balances[msg.sender] = 1000 * 1 ether;
  }
}
```

3) Run `yarn add openzeppelin-solidity` command.

4) Run `truffle compile` and make sure you see no errors.

5) `cd` into contracts folder.

6) Run `abigen --sol=ABCtoken.sol --pkg=main --out=ABCtoken.go`.

## 👍 Other Information

Geth version: 1.8.12-stable
OS & Version: OSX 10.12.6

I'm not sure this is go-ethereum abigen problem or openzeppelin-solidity problem. 😕

**Comment by nventuro** [comment]
Sounds like an `abigen` issue IMO, considering `truffle` builds them just fine. I don't know though what sort project directory structure `abigen` expects, so I'm not sure if there's anything we could/should do on our end to help.

**Comment by zulhfreelancer** [comment]
I tried with many options. The problem persists.

| Installation Command                  | Path inside ABCtoken.sol                                                  | ABIGEN Result | Truffle Compile Result |
|---------------------------------------|---------------------------------------------------------------------------|---------------|------------------------|
| `$ yarn add zeppelin-solidity`        | `import "zeppelin-solidity/contracts/token/ERC20/MintableToken.sol";`     | Failed        | Passed                 |
| `$ npm install zeppelin-solidity`     | `import "zeppelin-solidity/contracts/token/ERC20/MintableToken.sol";`     | Failed        | Passed                 |
| `$ yarn add openzeppelin-solidity`    | `import "openzeppelin-solidity/contracts/token/ERC20/MintableToken.sol";` | Failed        | Passed                 |
| `$ npm install openzeppelin-solidity` | `import "openzeppelin-solidity/contracts/token/ERC20/MintableToken.sol";` | Failed        | Passed                 |

**Comment by komalsukhani** [comment]
When a solidity file is provided to abigen, it compiles the file using solc compiler.
According to solidity doc

> solc only allows you to include files from certain directories: They have to be in the directory (or subdirectory) of one of the explicitly specified source files or in the directory (or subdirectory) of a remapping target.

Currently, there is no way to provide remapping target to abigen command. (Issue for the same is raised in geth repo [#16518](https://github.com/ethereum/go-ethereum/issues/16518))

So all imported files have to be in same directory.

**Comment by nventuro** [comment]
Thanks for your input @komalsukhani, I figured it must be something along those lines.

Closing since this is a `solc` and `abigen` issue.
