### ISSUE TITLE
ERC165 Cache Mixin

### ISSUE THREAD

**Issue by shrugs** [OpenZeppelin/openzeppelin-solidity#1127]
## 🎉 Description

While browsing [EIP 820](https://github.com/ethereum/EIPs/issues/820) I found code like

```
    function erc165InterfaceSupported(address _contract, bytes4 _interfaceId) constant public returns (bool) {
        if (!erc165Cache[_contract][_interfaceId]) {
            erc165UpdateCache(_contract, _interfaceId);
        }
        return interfaces[_contract][_interfaceId] != 0;
    }

    function erc165UpdateCache(address _contract, bytes4 _interfaceId) public {
        interfaces[_contract][_interfaceId] =
            erc165InterfaceSupported_NoCache(_contract, _interfaceId) ? _contract : 0;
        erc165Cache[_contract][_interfaceId] = true;
    }
```

which cleverly caches the results of 165 lookups.

We should 

1) profile the gas gains
2) develop a mixin contract that can be added to `ERC165Checker.sol`

- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

**Comment by frangio** [comment]
Closing this issue. The added complexity and correctness concerns around cache invalidation make me think this is not worthwhile to implement.
