### ISSUE TITLE
import "github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/ERC721BasicToken.sol";

### ISSUE THREAD

**Issue by dwayneem** [OpenZeppelin/openzeppelin-solidity#1136]
## 🎉 Description

- [X] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 💻 Environment

Next, we need to know what your environment looks like.

- Which version of OpenZeppelin are you using?
- What network are you deploying to? Ganache? Ropsten?
- How are you deploying your OpenZeppelin-backed contracts? truffle? Remix? Let us know!

## 📝 Details

Describe the problem you have been experiencing in more detail. Include as much information as you think is relevant. Keep in mind that transactions can fail for many reasons; context is key here.

## 🔢 Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

```
insert short code snippets here
```

## 👍 Other Information

In the Remix IDE attempting to compile a source with the single line
import "github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/ERC721BasicToken.sol";

fails with the error message:
Unable to import "undefined" : not found.

**Comment by nventuro** [comment]
This is a Remix issue, not an OpenZeppelin one. Looks like it's not the first time this has happened: https://github.com/ethereum/remix/issues/696

**Comment by yarcowang** [comment]
I do get this error, seems a redirect problem.

DO NOT USE the link you view it on GitHub, ex.:  
`https://github.com/ethereum/dapp-bin/blob/master/library/features.sol`  
OR  
`https://github.com/ethereum/dapp-bin/raw/master/library/features.sol`(the `raw` button, a redirection link)

You SHOULD use:  
`https://raw.githubusercontent.com/ethereum/dapp-bin/master/library/features.sol`

**Comment by enderphan94** [comment]
neither of them worked for me :(

**Comment by frangio** [comment]
Please try my suggestions here https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2032#issuecomment-568757498

**Comment by abcoathup** [comment]
@enderphan94 
There is an example in the Community Forum of importing from GitHub when using Remix: https://forum.openzeppelin.com/t/deploy-a-simple-erc20-token-in-remix/1203

If you have questions you can ask in the Community Forum: https://forum.openzeppelin.com
