### ISSUE TITLE
Increase coverage to 100%

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1147]
Coverage has remained at 95% for quite a bit, though I'm not sure if this is really a fault of our test suite, or an integration issue with `solidity-coverage` (see #1137). We should look into this, figure out what's missing/wrong, and bump the coverage figure.

**Comment by frangio** [comment]
This has progressed quite a lot. 100% is not doable because of https://github.com/sc-forks/solidity-coverage/issues/269.
