### ISSUE TITLE
npm: openzeppelin-solidity vs. zeppelin-solidity 

### ISSUE THREAD

**Issue by jmcnevin** [OpenZeppelin/openzeppelin-solidity#1152]
I'm a little confused/concerned that there are two npm packages out there with very similar names, but at different versions.  What is the reason for this?  The "openzeppelin-solidity" package seems to be the more "official" of the two.

https://www.npmjs.com/package/openzeppelin-solidity
https://www.npmjs.com/package/zeppelin-solidity

**Comment by frangio** [comment]
Hi @jmcnevin. The package was renamed to <code><b>open</b>zeppelin-solidity</code> in [1.9.0](https://github.com/OpenZeppelin/openzeppelin-solidity/releases/tag/v1.9.0). The `zeppelin-solidity` package has been deprecated in favor of the new one. Regardless, we are keeping the old package up to date until the 2.0 release of OpenZeppelin.

There is a deprecation notice when you visit the package or install it, suggesting to install the newer one. It was put up at the moment of the rename but for some reason was not showing up any more. I've already put it back in place, but I'm going to contact npm to understand why it was not showing up. Thanks for pointing it out.
