### ISSUE TITLE
All state variables should be private

### ISSUE THREAD

**Issue by elopio** [OpenZeppelin/openzeppelin-solidity#1174]
Solidity adds public getters to public state variables. This is kind of magical and dark, and could lead to mistakes.

We should be more explicit on everything we do, to make the code clearer and easier to review. So let's get rid of the automatic getters making all the public state variables private. If the variable has to be accessed from outside of the contract, we should add a getter function that should be either internal or public, depending on how the contracat is designed.

This gives us an extra benefit because the state variables will be implementation details and this allows us to make some changes without modifying the public API of the contract.

**Comment by frangio** [comment]
The main benefit of this IMO is encapsulation of a contract's state, because `private` state variables cannot be modified by derived classes. This enhances the auditability of a modular set of contracts.

**Comment by frangio** [comment]
Keep in mind that the previous #1097 is a subset of this dealing specifically with `StandardToken`, and is being addressed in #1197.

**Comment by frangio** [comment]
Fixed.
