### ISSUE TITLE
Make our function names clearer

### ISSUE THREAD

**Issue by elopio** [OpenZeppelin/openzeppelin-solidity#1178]
Some of the names of our functions should be improved.

If a function returns a boolean, it's name should be a question. For example, capReached should be isCapReached.

If a function is a hook intended to be implemented by derived contracts, it should have the word `on`. For example, finalization should be onFinalized.

Most of the other functions should have verbs on their names that clearly explain the thing it does.

**Comment by elopio** [comment]
I also think that the getter functions should be named like getVariable, and the setters setVariable. But maybe we should discuss this one a little more because people might be used to having the functions with the same name as the variables.

**Comment by frangio** [comment]
We've decided against some of these, and implemented others in other PRs.
