### ISSUE TITLE
Use I prefix for ERC interfaces

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-solidity#1196]
This may be a controversial one, but we're unhappy with the current naming for interface+implementation contract pairs like `ERC20`+`StandardToken`, and `ERC721`+`ERC721Token`. The implementation names are chosen arbitrarily only so as not to clash with the corresponding interface. Moreover, the two pairs presented are inconsistent. We know that this is an area of confusion for users. Arbitrariness and inconsistency breed confusion, so let's improve that.

We should name our ERC interfaces with an `I` prefix, and the corresponding implementation without it. We'll then have `IERC20`+`ERC20` and `IERC721`+`ERC721`.

This should not unnecessarily proliferate though. Some interfaces are actually abstract base contracts, and they should be appropriately given an abstract name, and their implementations a concrete name. This is why the issue is only about ERC interfaces. If there are other interfaces which you think deserve better naming please write a comment.

**Comment by shrugs** [comment]
(imo this should also include other interface-like interfaces and contracts we have in the repo, not just ERCs)

**Comment by nventuro** [comment]
We seem to have consensus on moving forward with this: are there any arguments against?
