### ISSUE TITLE
Use this in tests

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1200]
Some tests still have global(ish) state, we should move towards storing those in `this`.

Part of #1091.

**Comment by Aniket-Engg** [comment]
@nventuro I think most of the tests are following this. Can you please to the files lacking this?

**Comment by nventuro** [comment]
To clarify, this doesn't refer to configuration variables (e.g. `const cap = ether(20);`), but to things like

```
let token;
beforeEach(async function () {
  token = await Token.new();
});
```

`examples/SimpleToken` is guilty of this, as is `MerkleProof`, `DetailedERC20`, and `ReentracnyGuard`. There may be more examples of this, but I'm not sure.

**Comment by Aniket-Engg** [comment]
I checked each test file. Changes were required only in the files mentioned by you. Still if anyone finds that I missed something, Please add here.
