### ISSUE TITLE
Improve ERC165 testing

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1203]
As noted [here](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1193#issuecomment-412365610), we should improve our `shouldSupportInterfaces` functions so that they not only test the interface has been registered, but also that it actually exists in the API, preventing mis-registration and errors like [the one made](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1193#issuecomment-412357812) in #1193.

**Comment by Aniket-Engg** [comment]
I think this can be tested by checking that a corresponding `.json` file exists in `build` folder.

**Comment by nikeshnazareth** [comment]
can I take this one?

**Comment by nventuro** [comment]
@nikeshnazareth go ahead! This one has been in the backlog for a long time now, but it'd be great if we got it done :)
