### ISSUE TITLE
Visibility of StandardToken state variables

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/openzeppelin-solidity#1208]
## 🎉 Description
```
contract StandardToken is ERC20 {
  mapping(address => uint256) balances;
  mapping (address => mapping (address => uint256)) internal allowed;
  uint256 totalSupply_;
  ...
}
```

I think that it would be best to:
1. Explicitly declare the visibility of `balances` and `totalSupply_`
2. Change this visibility from (implicit) `public` to `internal` (since an explicit Getter function is implemented for each one of these variables)

Side note:
The 3 state variables in this contract are not conforming to the same coding convention (though I suppose that it would be a breaking change to fix it at this point).

**Comment by nventuro** [comment]
Thanks for reporting this @barakman! I wonder how it slipped by.

We're doing API breakage in [OZ 2.0](https://github.com/OpenZeppelin/openzeppelin-solidity/milestone/3), so this is actually the perfect time to address this :)

**Comment by nventuro** [comment]
Just noticed #1197 will take care of this, so there's no need to worry :)
