### ISSUE TITLE
ERC20 token with snapshots

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-solidity#1209]
We should have a flavor of ERC20 that adds snapshotting of balances. This mechanism allows for implementing a number of things such as trustless dividends, weighted voting (think DAOs), and forking.

I wrote an implementation that is quite efficient, with _O(log(snapshot count))_ cost for retrieving past balances, and relatively small constant overhead for transfers. It can be found in my [`frangio:feature-snapshot-token`](https://github.com/frangio/openzeppelin-solidity/blob/feature-snapshot-token/contracts/token/ERC20/SnapshotToken.sol) branch.

I posted this initially in #991 but can't continue working on it for now due to lack of time. Someone needs to complete the work on it by adding comprehensive tests and documentation, and maybe review some naming. After #1097 is merged it should also account for the new internal `_mint` and `_burn` functions. We should measure the gas overhead too. Don't hesitate to ask any questions about it!

There was some previous discussion in #991, and in #1100 which was a proposal of an implementation that turned out to be too costly.

**Comment by dmdque** [comment]
Came across this issue in passing. This [contract](https://github.com/yarrumretep/dividend-token/blob/master/contracts/DividendToken.sol) may be helpful.

**Comment by jbogacz** [comment]
@frangio I'm trying map in my mind your branch code to current project state. Could you correct me if I'm wrong -> Old **StandardToken** is just now **ERC20** right ? We'r gonna to produce something like SnapshotERC20 or better to stick naming convention ERC20Snapshot ?

**Comment by frangio** [comment]
>Old StandardToken is just now ERC20 right ?

Yes! And we should stick tot he naming convention with something like `ERC20Snapshot`, or `ERC20Snapshots`. Other name ideas are welcome.

@jbogacz are you interested in working on this issue?

**Comment by jbogacz** [comment]
@frangio Yes, I'm! It's very good candidate to get more familiar with OZ engine.

**Comment by frangio** [comment]
@jbogacz Awesome. Let me know if you have any questions.

**Comment by mswezey23** [comment]
Validity Labs is also working on a Snapshot Token. Currently finishing it up now, will do an internal review later this week with the hopes of submitting a PR to OZ.
