### ISSUE TITLE
why not use tx.origin == msg.sender to judge the caller is a contract address or EOA?

### ISSUE THREAD

**Issue by flyq** [OpenZeppelin/openzeppelin-solidity#1212]
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/AddressUtils.sol

**Comment by nventuro** [comment]
First of all, `isContract` checks the code size for _any_ address, not just the caller.

With that out of the way, there are multiple reasons why `tx.origin` is usually a bad idea, at least security-wise: see [here](https://github.com/ethereum/solidity/issues/683) an issue where removing it from Solidity was proposed, and [here](https://ethereum.stackexchange.com/questions/196/how-do-i-make-my-dapp-serenity-proof) a suggestion from Vitalik to 'not assume that tx.origin will continue to be usable or meaningful'.

**Comment by flyq** [comment]
thx
