### ISSUE TITLE
Have only one variant of expectEvent

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-solidity#1220]
Our `expectEvent` helper currently comes in two variants: `expectEvent.inLogs` and `expectEvent.inTransaction`. As far as I can tell, we only need one of the two. `inTransaction` was suggested by @nventuro as the one to keep.

I'd also reconsider whether it should be an async function. It seems like it would make sense as a sync function. We can expect a receipt as the argument and we wouldn't need to `await` it.

**Comment by nventuro** [comment]
I don't see a point in making it `async`, since you'll need to `await` on your test anyway.

**Comment by Aniket-Engg** [comment]
`inLogs` should be removed only from `module.exports` and used internally for `inTransaction` or it should be removed completely and functionality of `inLogs` should be added in `inTransaction`?

**Comment by nventuro** [comment]
Closed via #1511
