### ISSUE TITLE
Crowd sale buy tokens fails in geth due to token safe transfer

### ISSUE THREAD

**Issue by madan-ideas2it** [OpenZeppelin/openzeppelin-solidity#1221]
I tried a crowdsale with Standard token. When i call the buyToken methods using ganache-cli as the network, it works fine, but when i repeat the same with geth, it fails.

I found the root cause to be,

token.safeTransfer line in crowdsale.sol

It redirects to SageERC20.sol which in turn should call the transfer method in BasicToken.sol

Which will return true if success.

But when i call this method, it fails.

But the method doesnot have any issue, i even tried commenting out all lines in the method and returned true, still it fails

**Comment by nventuro** [comment]
Hi @madan-ideas2it! Are you using a Geth node with an ad-hoc network, or connecting to one of the cannonical networks (mainnet, ropsten, etc.)? Also, could you provide some more information on your setup, etc? Thanks!

**Comment by madan-ideas2it** [comment]
@nventuro I am connecting to a private network. And i found the root cause. With the latest solidity compilers, calling an external contract method from within another contract fails. For this we need to update the genesis config with "ByzantiumBlock": 0. And reinitialize the network. Now it works fine

**Comment by nventuro** [comment]
Awesome! Closing the issue then.
