### ISSUE TITLE
"The contract code couldn't be stored, please check your gas amount" when inheriting from Crowdsale

### ISSUE THREAD

**Issue by shabbosgoy** [OpenZeppelin/openzeppelin-solidity#1224]
## 🎉 Description

When creating a basic contract, without any functionality whatsoever, that inherits from Crowdsale (i.e. Crowdsale.sol), the aforementioned error occurs. This occurs both on Ganach, Ropsten and Rinkeby. The moment I leave out the inheritance (i.e. "is Crowdsale" portion), the contract compiles and migrates just fine to Ganach, Ropsten and Rinkeby.

Working code:
```
pragma solidity ^0.4.24;

import "./PrettyToken.sol";
import "../node_modules/openzeppelin-solidity/contracts/crowdsale/Crowdsale.sol";

contract PrettyTokenSale {

  constructor(uint256 _rate, address _wallet, ERC20 _token) public {

  }

  function doNothing() public returns (bool success) {
  	return true;
  }
}
```

Not working code:
```
pragma solidity ^0.4.24;

import "./PrettyToken.sol";
import "../node_modules/openzeppelin-solidity/contracts/crowdsale/Crowdsale.sol";

contract PrettyTokenSale is Crowdsale {

  constructor(uint256 _rate, address _wallet, ERC20 _token) public Crowdsale(_rate, _wallet, _token) {

  }

  function doNothing() public returns (bool success) {
  	return true;
  }
}
```

- [x ] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 💻 Environment

Next, we need to know what your environment looks like.

- Which version of OpenZeppelin are you using?
Latest, on Windows 10. Latest Node. Latest Truffle. Latest everything.

- What network are you deploying to? Ganache? Ropsten?
Ganache, Ropsten, Rinkeby

- How are you deploying your OpenZeppelin-backed contracts? truffle? Remix? Let us know!

## 📝 Details

When deploying to both Ropsten and Rinkeby, the error I mentioned above happens. When deploying to Ganache I get:
`Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: VM Exception while processing transaction: revert`

## 🔢 Code To Reproduce Issue [ Good To Have ]

See initial report.

## 👍 Other Information
This also happens when copy-pasting the example Crowdsale contract in the Github. When copy-pasting the actual code from Crowdsale.sol into my own contract, such as to make my contract have the same functionality without inheriting, I get the same error.

**Comment by nventuro** [comment]
See your error message, you're getting a `revert` in your transaction. The reason is that you're passing invalid parameters to your `Crowdsale`, which [has some validations in its constructor](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.12.0/contracts/crowdsale/Crowdsale.sol#L58).

Make sure the `rate`, `wallet` and `token` parameters are valid, and you'll be able to deploy just fine.

**Comment by shabbosgoy** [comment]
Thank you so much! It was the `require(_rate)`. My apologies for opening this issue - but I hope this helps others.

**Comment by nventuro** [comment]
No worries! Thank you for your detailed report, which allowed me to quickly pinpoint the issue :) As a general rule, whenever you get a `revert` in an OZ contract, that means you're doing something wrong somewhere (in your case, passing an invalid rate).
