### ISSUE TITLE
Arguments for parent constructor not specified in child (TimedCrowdsale.sol)

### ISSUE THREAD

**Issue by Profess0r** [OpenZeppelin/openzeppelin-solidity#1227]
## 🎉 Description

I playing around with crowdsale contracts and get "This contract does not implement all functions and thus cannot be created" error when tried to deploy TimedCrowdsale contract. It happened because TimedCrowdsale contract inherited from Crowdsale contract but it has constructor with arguments which not specified in TimedCrowdsale contract. I assume that definition of constructor in TimedCrowdsale must be changed from 

constructor(uint256 _openingTime, uint256 _closingTime) public {
    // solium-disable-next-line security/no-block-members
    require(_openingTime >= block.timestamp);
    require(_closingTime >= _openingTime);

    openingTime = _openingTime;
    closingTime = _closingTime;
}

to something like

constructor(
    uint256 _openingTime, 
    uint256 _closingTime, 
    uint256 _rate, 
    address _wallet, 
    address _token
) 
    public Crowdsale(_rate, _wallet, ERC20(_token)) 
{
    // solium-disable-next-line security/no-block-members
    require(_openingTime >= block.timestamp);
    require(_closingTime >= _openingTime);

    openingTime = _openingTime;
    closingTime = _closingTime;
}

## 💻 Environment

Issue was discovered using Remix. Interesting fact that while using ethFiddle online IDE it seems posible to deploy contract but not specified arguments will be default values, which not the right behavior either.

## 👍 Other Information

It seems that other contracts, in particular IncreasingPriceCrowdsale, may have the same issue.

**Comment by frangio** [comment]
Hi @Profess0r, thanks for reporting.

This is in fact by design, you're supposed to put the different crowdsale "flavors" together into a contract of your own. Please take a look at this example:

https://github.com/OpenZeppelin/openzeppelin-solidity/blob/64c324e37c17c5e0501bb746975040d1ae020806/contracts/examples/SampleCrowdsale.sol#L39-L60


We'll be working on the documentation to make this clearer.
