### ISSUE TITLE
ERC721Token doesn't compile, receiving an error.

### ISSUE THREAD

**Issue by alexacostarua** [OpenZeppelin/openzeppelin-solidity#1239]
## 🎉 Description

Was trying to compile the ERC721Token.sol using truffle.  I correctly imported the necessary files for it, but failed with an error.

- [ ] 🐛 This is a bug report.

## 💻 Environment

- Which version of OpenZeppelin are you using? installed from the github help page using npm
- What network are you deploying to? custom network (parity POA)
- How are you deploying your OpenZeppelin-backed contracts? using truffle v4.1.14, solidity v0.4.24
Ubuntu 16.04

## 📝 Details
Tried to compile using truffle prerequisites compiled then thrown an error

Compiling ./contracts/ERC721Token.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/AddressUtils.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/introspection/ERC165.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/introspection/SupportsInterfaceWithLookup.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/math/SafeMath.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721Basic.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721BasicToken.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721Receiver.sol...

/home/user1/ethereum-erc721-master/contracts/ERC721Token.sol:71:13: DeclarationError: Undeclared identifier. Did you mean "exists"?
    require(_exists(_tokenId));
            ^-----^
,/home/user1/ethereum-erc721-master/contracts/ERC721Token.sol:120:13: DeclarationError: Undeclared identifier. Did you mean "exists"?
    require(_exists(_tokenId));
            ^-----^
Compilation failed. See above.

**Comment by nventuro** [comment]
Hm, I'm not sure what may be causing that issue. Something weird I noticed about your setup, however, is that you have an `ERC721Token.sol` contract in `contracts/`: you should be importing the OpenZeppelin, not copying the source code.

**Comment by alexacostarua** [comment]
Awesome @nventuro thanks for the pointer.  Now I've correctly imported the source code and got it to compile.  My contract looks like this:
-------------------------------------------------------------------------------------------------------------------------------------------
 pragma solidity ^0.4.23;

import "/home/user1/ethereum-erc721-master/node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721Token.sol";

contract MyERC721 is ERC721Token {
    constructor (string _name, string _symbol) public
        ERC721Token(_name, _symbol)
    {
    }

    /**
    * Custom accessor to create a unique token
    */
    function mintUniqueTokenTo(
        address _to,
        uint256 _tokenId,
        string  _tokenURI
    ) public
    {
        super._mint(_to, _tokenId);
        super._setTokenURI(_tokenId, _tokenURI);
    }
}
-------------------------------------------------------------------------------------------------------------------------------------------
It compiled.
I got this error when attempting to migrate to my network:
Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Transaction cost exceeds current gas limit. Limit: 4700000, got: 6721975. Try decreasing supplied gas.
    at Object.InvalidResponse (/usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /usr/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:225:1
    at /usr/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
-------------------------------------------------------------------------------------------------------------------------------------------
I realize the error has to do with my network gas-limit not being high enough.  The one other question I have for you is where would I set the variables such as name, initial supply, and symbol.   I wonder this because I've worked with ERC20 contracts and it seems more straight forward in setting those default variables within the .sol then for the ERC721.
Thanks for the help.

**Comment by nventuro** [comment]
Could you clarify a bit further on what you mean by setting name and symbol? You seem to be doing it just fine (as constructor arguments) in your example. If you want hardcoded values, as opposed to paramatrized during construction, you can easily do so:

```
contract MyERC721 is ERC721Token {
  constructor () public
  ERC721Token("MyToken", "MYTKN")
  {
  }
```

**Comment by alexacostarua** [comment]
Thanks again @nventuro !  I got the contract deployed.  I also used the constructor you provided me with a name and symbol.  I believe the contract address for the token would be: 0xc89de68687389ae6c818e79a364823594b6f482e
-------------------------------------------------------------------------------------------------------------------------------------------
Compiling ./contracts/MyERC721.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/AddressUtils.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/introspection/ERC165.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/introspection/SupportsInterfaceWithLookup.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/math/SafeMath.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721Basic.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721BasicToken.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721Receiver.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721Token.sol...

Compilation warnings encountered:

/home/user1/ethereum-erc721-master/contracts/MyERC721.sol:6:18: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    constructor (string _name, string _symbol) public
                 ^----------^
,/home/user1/ethereum-erc721-master/contracts/MyERC721.sol:6:32: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    constructor (string _name, string _symbol) public
                               ^------------^

Writing artifacts to ./build/contracts

Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x85dac9720dd43a6cf94a501bf6e8b8e4ef891b8a8129920a8be1fe8f8c851f07
  Migrations: 0x6e70b14711201d0a84b4ee3a1654e34cb575374f
Saving successful migration to network...
  ... 0xf1e8bdf1ef313122a7b33116fa78626fc86d9c18499b6e61132d1c8ba1bf5cd7
Saving artifacts...
Running migration: 2_erc721_migration.js
  Deploying MyERC721...
  ... 0x3ced5d5be985295ed0888025156b768ffaeed387835b9eb64f98100b4f187497
  MyERC721: 0xc89de68687389ae6c818e79a364823594b6f482e
Saving successful migration to network...
  ... 0xbc2bba934fa8e0c0ea82300707a4d065d636c3be833a19a5b0bf2c15ee9c7f81
Saving artifacts...
-------------------------------------------------------------------------------------------------------------------------------------------
The last issue I have now is that.  I'm adding the contract to a wallet client, but it requires not only a contract address, also a "id", a "uniqueID", and an external path.  Where can I find what these values are set as?
Thanks so much. This will be my final question.  Sorry to bother you.

**Comment by alexacostarua** [comment]
I know I could set those values if I deployed it with Remix IDE, but since I cant get contracts ABI code from truffle, I cant call those commands through myetherwallet.  I tried setting the values and republishing the contract but I believed it failed:

-------------------------------------------------------------------------------------------------------------------------------------------
pragma solidity ^0.4.23;

import "/home/user1/ethereum-erc721-master/node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721Token.sol";

contract MyERC721 is ERC721Token {
    constructor (string _name, string _symbol) public
        ERC721Token("DogBone", "DB")
    {
    }

    /**
    * Custom accessor to create a unique token
    */
    function mintUniqueTokenTo(
        address _to,
        uint256 _tokenId,
        string  _tokenURI
    ) public
    {
        super._mint(0x0496632f490cb4fbe6559d202120a6fd332442e7, 12);
        super._setTokenURI(12, "dogbone");
    }
}
-------------------------------------------------------------------------------------------------------------------------------------------
truffle migrate
Compiling ./contracts/MyERC721.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/AddressUtils.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/introspection/ERC165.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/introspection/SupportsInterfaceWithLookup.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/math/SafeMath.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721Basic.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721BasicToken.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721Receiver.sol...
Compiling ./node_modules/openzeppelin-solidity/contracts/token/ERC721/ERC721Token.sol...

Compilation warnings encountered:

/home/user1/ethereum-erc721-master/contracts/MyERC721.sol:20:21: Warning: This looks like an address but has an invalid checksum. If this is not used as an address, please prepend '00'. Correct checksummed address: '0x0496632F490cb4FbE6559D202120A6fd332442e7'. For more information please see https://solidity.readthedocs.io/en/develop/types.html#address-literals
        super._mint(0x0496632f490cb4fbe6559d202120a6fd332442e7, 12);
                    ^----------------------------------------^
,/home/user1/ethereum-erc721-master/contracts/MyERC721.sol:6:18: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    constructor (string _name, string _symbol) public
                 ^----------^
,/home/user1/ethereum-erc721-master/contracts/MyERC721.sol:6:32: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    constructor (string _name, string _symbol) public
                               ^------------^
,/home/user1/ethereum-erc721-master/contracts/MyERC721.sol:15:9: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
        address _to,
        ^---------^
,/home/user1/ethereum-erc721-master/contracts/MyERC721.sol:16:9: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
        uint256 _tokenId,
        ^--------------^
,/home/user1/ethereum-erc721-master/contracts/MyERC721.sol:17:9: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
        string  _tokenURI
        ^---------------^

Writing artifacts to ./build/contracts

Using network 'development'.

Network up to date.
-------------------------------------------------------------------------------------------------------------------------------------------
Not sure why it wouldn't at least return the contract address??

**Comment by alexacostarua** [comment]
Ok. I've added the contract successfully.  I have access to the calls through the abi code using myetherwallet.  I can set the token id, the token uri, aswell as the address.  The issue is now making allowing the wallet client to see this information.  I'm using a fork of trustwallets code to set this collectible: it asks for the id, the contract, the name, the category, annotation, imagepath, externalpath, and unique id.  I currently know the id which is the token id, the name which I set in the constructor, the imagepath, and it claims the unique id, is the token id + the contract (as a string).  I was wondering if you knew what the other variables were?  They are all type string.  Please leave a doge donation address as well you've been greatly helpful!

**Comment by nventuro** [comment]
Sorry @alexacostarua, I'm not familiar with trustwallets, maybe you'll have better luck asking on their forums? I suspect though that those may be fields stored where the tokenURI points to. And thanks for the doge offer :)
