### ISSUE TITLE
Do not use storage for SupportsInterface implementation

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-solidity#1245]
A contract that currently implements ERC165 extends from SupportsInterfaceWithLookup, which defines a mapping in storage where all the interface identifiers are stored. While this provides `O(1)` lookup, it involves a high gas cost in terms of saving all the IDs in storage. 

An alternative implementation could be to simply check the interface ID subsequently against the set of hardcoded identifiers (especially since these values are constants). This implementation was used in the [ZeppelinOS fork of OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-zos/blob/master/contracts/token/ERC721/ERC721Token.sol#L67-L68), for instance. 

The gas usage limit should not be an issue, as a call with 10 interface id checks costs ~700 gas, way under the 30K limit.

**Comment by frangio** [comment]
The lookup implementation of `supportsInterface` costs 616 gas. Given that this cost is constant, and surpassed by the proposed alternative with only 10 interface ids, I think the lookup wins cost-wise.

Additionally, I consider the internal API of lookup to be way better and safer. It's a call to `_registerInterface`, whereas hardcoding the ids requires overloading the `supportsInterface` function and manually calling `super`.

All this considered, my vote is to keep the lookup implementation.

**Comment by fincrypchain001** [comment]
CLOSED ALL ACCOUNT BIGCRYPTO001

**Comment by nventuro** [comment]
While this could eventually become an issue with contracts that have a large amount of identifiers, the current implementation is fine as-is.
