### ISSUE TITLE
safeConversion.sol - Standard contract for type conversion

### ISSUE THREAD

**Issue by nachomazzara** [OpenZeppelin/openzeppelin-solidity#1255]
## 🎉 Description

The idea is to have a library contract with standard methods for type conversion will allow for better compatibility between contracts

- [x] 📈 This is a feature request.

## 🔢 Code example

- [x] - bytes to uint
- [x] - uint to bytes
- [ ] - others (Add please useful conversion type)

```solidity
pragma solidity ^0.4.24;

/**
 * @title safeConversion
 * @dev Type conversion with safety checks that revert on error
 */
library SafeConversion {

function toBytes(uint256 x) internal pure returns (bytes b) {
    b = new bytes(32);
    // solium-disable-next-line security/no-inline-assembly
    assembly { mstore(add(b, 32), x) 
   }
}

function _bytesToUint(bytes b) internal pure returns (uint256) {
    bytes32 out;

    for (uint i = 0; i < b.length; i++) {
      out |= bytes32(b[i] & 0xFF) >> i.mul(8);
    }

    return uint256(out);
  }
}
```

**Comment by frangio** [comment]
Hi @nachomazzara! Can you share a few examples where you'd use these conversions? What kind of safety checks would they have?

**Comment by nachomazzara** [comment]
@frangio sure!

We transfer tokens from one contract to another.
 
As we using the `onERC721Received` which expect `userData` to be bytes we need to convert the data to send to bytes [before transferring](https://github.com/decentraland/land/blob/master/contracts/land/LANDRegistry.sol#L249) them and then convert from bytes to uint once [we receive it](https://github.com/decentraland/land/blob/master/contracts/land/LANDRegistry.sol#L249)

**Comment by frangio** [comment]
Got it! Completely agree that `onERC721Received` and similar functionality needs helpers for the conversion.

There's an upcoming Solidity feature, `abi.decode`, built for this  It's already merged so it will be in the next release. Since that's coming out soon I think we should rather wait for that than implement it in OpenZeppelin.

**Comment by nachomazzara** [comment]
Ah, ok. Do you have an example or somewhere to read about how can we will use it in a future?

**Comment by frangio** [comment]
Yeah, sorry, I forgot to include the link. :sweat_smile: 

This is the documentation: https://solidity.readthedocs.io/en/latest/units-and-global-variables.html#abi-encoding-and-decoding-functions.

You will basically be able to do:

```
function onERC721Received(..., bytes _data) public returns (bytes4) {
  uint param = abi.decode(_data, (uint));
}
```

Closing this issue in favor of the native Solidity functions.
