### ISSUE TITLE
Add generic proxy implementation

### ISSUE THREAD

**Issue by federicobond** [OpenZeppelin/openzeppelin-solidity#130]
http://martin.swende.se/blog/EVM-Assembly-trick.html

We could implement base behaviour in a GenericProxy contract and write OwnedProxy and MultisigProxy rules for changing the target.

I can work on a pull request if you are interested.

**Comment by elopio** [comment]
We have the generic proxy in [zos-lib](https://github.com/zeppelinos/zos-lib/blob/3d6690afd8c9cf33d261a21fa56efca8b70f8058/contracts/upgradeability/Proxy.sol). Maybe later we can move some of those things to the openzeppelin stdlib, but for now I think that for now it's nice to have it there.  

@federicobond: it would be nice if you give it a look an let us know what do you think. It's a critical component of the upgradeability of zeppelin os, so we need to get many eyes to review it.

Closing for now, we can reopen it later to move the contract.
