### ISSUE TITLE
Differences between ERC20 contracts between node package and github repository

### ISSUE THREAD

**Issue by gorlitzer** [OpenZeppelin/openzeppelin-solidity#1314]
## 🎉 Description
Good morning, as usual I' m using your npm module to work with my contracts in a truffle directory but i noticed that there are gaps between contracts from the github repository and the node modules package. 
Also It would be useful for compiler' s warnings to add require statements. 

- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

## 💻 Environment

Next, we need to know what your environment looks like.

- Which version of OpenZeppelin are you using?
  "openzeppelin-solidity": "^1.12.0"
- What network are you deploying to? Ganache? Ropsten?
  Ganache
- How are you deploying your OpenZeppelin-backed contracts? truffle? Remix? Let us know!
  truffle

## 📝 Details

Contracts in ERC20/ directory are named differently and all the require statements need to be updated.

**Comment by nventuro** [comment]
The `master` branch of the repo is much further ahead from the 1.12 release: we've actually just released the [2.0 release candidate](https://github.com/OpenZeppelin/openzeppelin-solidity/releases/tag/v2.0.0-rc.1). If you want to take a look at the state of the repo as of 1.12, click [here](https://github.com/OpenZeppelin/openzeppelin-solidity/tree/v1.12.0).

In any case, you should only use the versions released in npm as opposed to simply cloning the repo (unless you want to do development in OZ itself and contribute :))

**Comment by gorlitzer** [comment]
oh oh so sorry, i wasn' t able to find the 2.0 candidate, now i will use it! Thanks.
At the moment the best case i found to clone your contracts instead of using the released version is for implementing a "staged crowdsale" with different rates, or a mintable token with different minters. 
Thank you mate
