### ISSUE TITLE
NonReentrant change is breaking

### ISSUE THREAD

**Issue by BrendanChou** [OpenZeppelin/openzeppelin-solidity#1326]
## 🎉 Description

The new nonReentrant function uses a local variable which counts toward the stack limit for any functions that use this modifier, making some contracts unable to be compiled.

Results in the error: `CompilerError: Stack too deep, try removing local variables.`

- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

## 💻 Environment

This is a change from v1.11 to v1.12

**Comment by frangio** [comment]
Thanks @BrendanChou, this is very interesting... Do you have an example contract that would trigger this?

**Comment by BrendanChou** [comment]
This is probably a little more complicated than is necessary but this is the function that triggered for me:

https://gist.github.com/BrendanChou/5672f834ef6af3dcd297a6e2ccd77bdb

**Comment by frangio** [comment]
Thanks! We're definitely going to keep this in mind for future minor releases starting with v2.0.
