### ISSUE TITLE
Request for implementing a contract which supports "multi-user" access

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/openzeppelin-solidity#1328]
## 🎉 Description

One of the main issues that we've come across, is the ability to scale-out (aka *horizontal-scaling*) the execution of `onlyOwner` functions in our system.

Such function can be called only from a single account, hence, in every function-call, one must increment the nonce before sending the transaction to the Ethereum node.

However, if we allow such function to be called from any one of several given accounts, then we can easily "split the work" over several different nodes (aka *load-balancing*), and achieve a higher throughput.

My suggestion here is to implement a contract supporting "multi-user" access, which can be inherited by anyone.

This contract will provide the following:
- An `onlyUser` modifier, which can be used (by the derived contract) instead of `onlyOwner`
- A pair of functions for accepting new / rejecting existing users, which will be restricted by `onlyOwner`

- [x] 📈 This is a feature request.

## 📝 Details

```
import "./Ownable.sol";

contract Usable is Ownable {
    address[] public userList;

    struct User {
        bool valid;
        uint index;
    }

    mapping(address => User) public users;

    /**
     * @dev Throws if called by any account other than one of the users.
     */
    modifier onlyUser() {
        require(users[msg.sender].valid);
        _;
    }

    /**
     * @dev Accept a new user.
     * @param _user The user's address.
     */
    function accept(address _user) external onlyOwner {
        User storage userRef = users[_user];
        require(_user != address(0));
        require(!userRef.valid);
        userRef.valid = true;
        userRef.index = userList.length;
        userList.push(_user);
    }

    /**
     * @dev Reject an existing user.
     * @param _user The user's address.
     */
    function reject(address _user) external onlyOwner {
        User storage userRef = users[_user];
        require(userRef.index < userList.length);
        require(_user == userList[userRef.index]);
        address lastUser = userList[userList.length - 1];
        users[lastUser].index = userRef.index;
        userList[userRef.index] = lastUser;
        userList.length -= 1;
        delete users[_user];
    }

    /**
     * @dev Get the total number of users.
     * @return The total number of users.
     */
    function userCount() external view returns (uint) {
        return userList.length;
    }
}
```

**Comment by nventuro** [comment]
Hey there @barakman! The upcoming OpenZeppelin 2.0 release (for which we already have a [release candidate](https://github.com/OpenZeppelin/openzeppelin-solidity/releases/tag/v2.0.0-rc.1) deprecates `Ownable` in favor of [more granular roles](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1291), e.g. a [`MinterRole`](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v2.0.0-rc.1/contracts/access/roles/MinterRole.sol), which you'll notice looks very similar to what you propose, and should easily cover your use case (though it is not the one we had in mind when designing it)
