### ISSUE TITLE
Create a standard Will contract

### ISSUE THREAD

**Issue by demibrener** [OpenZeppelin/openzeppelin-solidity#134]
https://www.reddit.com/r/ethereum/comments/5oq7ne/bountyrequest_for_a_contract_standard_will/

**Comment by JGcarv** [comment]
I'll start working on this!

**Comment by maraoz** [comment]
Great!

**Comment by ajsantander** [comment]
@JGcarv did you manage to make any progress on this?

**Comment by elopio** [comment]
This one looks good: https://github.com/EtherDogs/HeritableWallet
It is GPL though, so we can't just copy the code. Somebody can use the ideas from the README to implement one for openzeppelin. I like the "I am still alive" feature, it could be used for other things, like when you loose access to your private keys.

**Comment by artiebits** [comment]
[already implemented](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/ownership/Heritable.sol), isn't it?

**Comment by elopio** [comment]
Indeed, thanks for the notice @artiebits.
