### ISSUE TITLE
Figure out why the test suite doesn't finish

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1340]
For some time now we've had hangs in the CI, where the build fails because it goes over the maximum time limit, which requires a manual restart. It also sometimes happens locally. @shrugs [suggested](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1323#issuecomment-420790968) using  https://github.com/mafintosh/why-is-node-running to find the root cause.

**Comment by jbogacz** [comment]
Hey @nventuro don't you fortuitously capture any logs from issued CI job run? I faced this issue ones but didn't think to save it. As it's suggested in #1323 it can happen due to unresolved promises so having some logs it will be easier to track issued one.

**Comment by nventuro** [comment]
Looks like #1526 will fix this - if it turns out it doesn't, we'll need to dig deeper.
