### ISSUE TITLE
Demo snippet in README does not work in v1.12

### ISSUE THREAD

**Issue by Gargo** [OpenZeppelin/openzeppelin-solidity#1342]
Men just try to use instructions from your readme. For example I get the following on windows 10:
`Error: Could not find openzeppelin-solidity/contracts/token/ERC721/ERC721Full.sol from any sources; imported from E:\nodejs_projects\truffle-test\contracts\Test.sol`

**Comment by frangio** [comment]
Hi @Gargo. The instructions in the readme are for version 2.0.0-rc, which you can install through `npm install openzeppelin-solidity@next`.

Thanks for mentioning this. We'll make it clearer.

**Comment by Gargo** [comment]
@frangio thanks it almost works. The only problem is how to disable warnings in vs code now.
And of course you should fix readme
