### ISSUE TITLE
npm module openzeppelin-solidity of doesn't have ERC721Mintable.sol and many more files

### ISSUE THREAD

**Issue by princesinha19** [OpenZeppelin/openzeppelin-solidity#1345]
I have installed openzeppelin-soilidty through npm but it doesn't contain ERCMintable.sol, ERC721Full.sol and many more files. And if i clone the code through github then in ERC70 folder ERCMintable.sol and all other files are present.

Screenshot of npm module 
![screenshot from 2018-09-24 20-12-19](https://user-images.githubusercontent.com/28489437/45959053-9f689b80-c036-11e8-8040-f735cdf346bd.png)

Screenshot of github repository 
![screenshot from 2018-09-24 20-16-19](https://user-images.githubusercontent.com/28489437/45959090-b7d8b600-c036-11e8-9e64-386e418eee43.png)

**Comment by frangio** [comment]
Hi @princesinha19! Apologies for the confusion. These contracts were added in the latest release cycle and are part of the v2.0 release candidate.

`ERC721Full` is called `ERC721Token` in v1.12, but there is unfortunately no `ERC721Mintable` equivalent.

If you would like to test the release candidate you can install it via `npm install openzeppelin-solidity@next`.

**Comment by princesinha19** [comment]
okay @frangio. Thanks for clearification.
