### ISSUE TITLE
Proposal: MultiOwnable Smart Contract

### ISSUE THREAD

**Issue by ChrisCates** [OpenZeppelin/openzeppelin-solidity#1347]
A variation of the Ownable.sol contract.
I'd like to see a Multi Ownership Smart Contract that utilizes `mapping` as part of the OZ project.

I have created an implementation that may be of interest... And can send a pull request for review if open to a file such as `MultiOwnable.sol`. in `/contracts/ownership`

**Comment by nventuro** [comment]
Hi @ChrisCates! Do you mean you'd like multiple accounts to have a role? If so, [we've introduced that same thing](https://github.com/OpenZeppelin/openzeppelin-solidity/tree/master/contracts/access/roles) in the [2.0 release candidate](https://github.com/OpenZeppelin/openzeppelin-solidity/releases/tag/v2.0.0-rc.1), check it out!

**Comment by ChrisCates** [comment]
@nventuro the `Roles.sol` and it's respective files are for specific permissions.

The `Ownable.sol` contract acts almost as an administrative role for all account functionality.
Also, I feel the structure of the `Roles.sol` code could be simplified greatly as there are some redundancies in terms of functionality.

In fact, this may a good opportunity to restructure to have an `admin` role for verbosity purposes.
Are you open to reviewing a pull request with a proposal refactor in the v2.0.0 release?

**Comment by nventuro** [comment]
>The Ownable.sol contract acts almost as an administrative role for all account functionality.

That is precisely why we've decided to remove it in 2.0, and move towards more granular permissions (#366). 

Which redundancies worry you? The distinct roles under the `roles` directory are, granted, the exact same contract in essence: they exist only due to limitations of Solidity, and will be auto generated (#1290) in the future.

**Comment by ChrisCates** [comment]
@nventuro Ahh I see.
It seems a lot of other files depend on it.

Ah, so they will have auto-generated stubs in the future...
In that case I don't have any concerns.

Thanks for the clarifications.
