### ISSUE TITLE
Ownable contract: Undeclared identifier. Did you mean "owner"

### ISSUE THREAD

**Issue by UncleVultur** [OpenZeppelin/openzeppelin-solidity#1352]
## 🎉 Description

- [x] 🐛 This is a bug report.

Next, we need to know what your environment looks like.

- Which version of OpenZeppelin are you using?
latest 0,4.24
- What network are you deploying to? Ganache? Ropsten?
ganache
- How are you deploying your OpenZeppelin-backed contracts? truffle? Remix? Let us know!
truffle

## 📝 Details

I can't make a function to transfer to owner, aditionaly in ganache the owner address results in 0x0000000000...

## 🔢 Code To Reproduce Issue [ Good To Have ]

```
function transfer() public {
_owner.transfer(100000000);
}
```

**Comment by frangio** [comment]
Hi @UncleVultur. The `_owner` state variable is private, you should use the public getter `owner()`: `owner().transfer(100000000)`.
