### ISSUE TITLE
Warning or automatic correction the parameter of ether()

### ISSUE THREAD

**Issue by HSY229** [OpenZeppelin/openzeppelin-solidity#1353]
## 🎉 Description

Should we do one of below thing in `test/helpers/ether.js#ether()`?
* throw error
* convert number to string before invoke `web3.toWei(n, 'ether')`

-  [x] 📈 This is a feature request.

## 💻 Environment

- openzeppelin-solidity 1.12.0
- web3 0.20.6
- Truffle v4.1.14 (core: 4.1.14)
- Solidity v0.4.24 (solc-js) 

## 📝 Details

I want to use helper method to convert ether value into wei, but the result is incorrect. I notice that I have to use `String` to be the parameter of `ether()`.

[helper method](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/test/helpers/ether.js)
[web3#toWei() doc v1.0.0](https://web3js.readthedocs.io/en/1.0/web3-utils.html#towei)

## 🔢 Code To Reproduce Issue 

```Javascript
const { BigNumber } = web3;
const { ether } = require('openzeppelin-solidity/test/helpers/ether');
const loger = require('mocha-logger');

require('chai')
    .use(require('chai-bignumber')(BigNumber))
    .should();

describe('I want to use helper method to convert ether value into wei', () => {
    it('should output 123456789012345678 wei when input is 0.123456789012345678 ether', async () => {
        const result = ether(0.123456789012345678);
        loger.log(`result is ${result}`); // result is 123456789012345680
        result.should.be.bignumber.equal(new BigNumber('123456789012345678'));
    });

    it('should output 123456789012345678 wei when input is string and equal to 0.123456789012345678 ether', async () => {
        const result = ether('0.123456789012345678');
        loger.log(`result is ${result}`); // result is 123456789012345678
        result.should.be.bignumber.equal(new BigNumber('123456789012345678'));
    });
});
```

## 👍 Other Information

```Shell
 I want to use helper method to convert ether value into wei
    1) should output 123456789012345678 wei when input is 0.123456789012345678 ether
    ✓ should output 123456789012345678 wei when input is string and equal to 0.123456789012345678 ether

1 passing (9s)
  1 failing

  1) I want to use helper method to convert ether value into wei
       should output 123456789012345678 wei when input is 0.123456789012345678 ether:

      AssertionError: expected '123456789012345680' to equal '123456789012345678'
      + expected - actual

      -123456789012345680
      +123456789012345678
```

**Comment by nventuro** [comment]
This is not an issue with the helper, but with floating point representation: JavaScript's floating point numbers are not large enough to correctly store 0.123456789012345678, so even if we converted to string you woulnd't get the correct result. 

You can verify this by running `node` and typing the number, or opening the browser dev tools, and typing `console.log(0.123456789012345678)`.
