### ISSUE TITLE
Add tests for events in roles constructors

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-solidity#1354]
In https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1329 we made sure that `<Role>Added` events are emitted at construction, but we don't have tests for it yet because it's not as easy to retrieve the decoded logs emitted in a constructor using Truffle.

**Comment by Aniket-Engg** [comment]
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/80458ebc72f1c7c9695416edbe26690f72e406a0/test/examples/SimpleToken.test.js#L35
Here we test an event emitted in constructor. Should testing be done in the same way for roles constructors?
