### ISSUE TITLE
Rename 'anyone' account in tests to something else

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1357]
When testing access control related functionality, we usually have an `anyone` account that represents an account with no special permissions, e.g.:

```
it('reverts when anyone attempts to self-destruct', async function () {
  await assertRevert(this.contract.destroy({ from: anyone });
});
```

`anyone` is probably not the best name we can find, we should find something that better conveys the meaning of 'anyone else', 'any random account', etc.

**Comment by yosriady** [comment]
How about `stranger`?

**Comment by Aniket-Engg** [comment]
what about `guest`?

**Comment by nventuro** [comment]
Hmm, I like `other` better than the other proposals, I think it could work.

**Comment by mswezey23** [comment]
My vote is on `other` as well.

**Comment by ckshei** [comment]
I'd like to try and help work on this!

**Comment by ckshei** [comment]
I'll probably need a bit of guidance though - are we looking to change all references in anyone to "other" in the tests, or only in some specific instances, or only in the description?

**Comment by nventuro** [comment]
I think just the account name: test descriptions to go 'tokens can be transferred to anyone' are actually correct (assuming anyone is no-none :stuck_out_tongue:).

**Comment by ckshei** [comment]
:+1: got it. @nventuro, am I changing each instance of `from: anyone` to `from: other`? Or are some of the "anyone's" valid in the tests? 

In other words, I'm only changing this: 
```
  it('can be finalized by anyone after ending', async function () {
    await time.increaseTo(this.afterClosingTime);
    await this.crowdsale.finalize({ from: anyone });
  });
```
to 
```
  it('can be finalized by anyone after ending', async function () {
    await time.increaseTo(this.afterClosingTime);
    await this.crowdsale.finalize({ from: other });
  });
```

**Comment by nventuro** [comment]
Correct! I don't think we want to leave any instance of `anyone`: the core issue is that 'anyone' shouldn't be an account name (because it belongs to 'someone'). 'other' implies that that account isn't special (and represents 'anyone', which is why we leave it in the test descriptions :stuck_out_tongue:).

**Comment by ckshei** [comment]
Got it. @nventuro - You can see my first attempt here: https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1718

I changed all the references of "anyone" in the code to "other" and I'm pretty confident I didn't miss any. Just not sure if I might have done a few that weren't meant to have changed. I think I noticed one instance where "other" was declared but never actually used. I could remove that if you'd like.
