### ISSUE TITLE
Remove selfdestruct from BreakInvariantBounty

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1384]
`selfdestruct` can lead to tricky situations, has been the cause of major bugs, and has a debatable usefulness. We should avoid using it whenever possible.

Note that this is not a breaking change since this contract is in the `drafts` directory in the 2.0 release.

**Comment by Aniket-Engg** [comment]
Do we need to remove it from `BreakInvariantBounty` only?

**Comment by Aniket-Engg** [comment]
I checked that apart from `BreakInvariantBounty`, `selfdestruct` is only being used in `ForceEther` which is there for this destruction functionality only. So only remaining case is  `BreakInvariantBounty`. I will submit a PR with the required changes.
