### ISSUE TITLE
Improve SafeMath test coverage

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1386]
There are a couple edge cases we should consider adding tests for, to prevent regression errors:
 * `div`​ with numbers that aren’t divisible evenly
 * `div`​ with the first argument being 0
 * `mul`​ with the second argument being 0

Thanks @cwhinfrey and the Level K team for suggesting this!

**Comment by chesnokovilya** [comment]
I want to work on this.

**Comment by nventuro** [comment]
Go ahead @chesnokovilya! I'll gladly review your PR :)
