### ISSUE TITLE
import 'openzeppelin-solidity/...' does not compile when truffle is installed locally

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/openzeppelin-solidity#1387]
This issue has been reported in various versions and in various forums.

I can import any openzeppelin contract when I specify its full path (either relative or absolute).

But when I start the `import` statement with `'openzeppelin-solidity` as suggested in your official documentation, `truffle compile` is unable to resolve this type of `import` statements.

I suspect that it might work correctly when Truffle is installed globally (i.e., `npm install truffle -g`), because the official documentation specifies that this is how Truffle should be installed. However, for several (unrelated) reasons, I need to have Truffle installed locally, and so I cannot rely on this for a solution or a workaround.

**💻 Environment**

I am using:
- Truffle v4.1.14 (which relies on solc v0.4.24)
- OpenZeppelin v1.12.0
- Windows 10

**🔢 Code to reproduce bug**

**Directory Structure:**
- test:
  - node_modules:
    - openzeppelin-solidity:
      - contracts:
        - ownership:
          - Ownable.sol
  - project:
    - contracts:
      - MyContract.sol (see below)
    - truffle-config.js (can be empty)
  - package.json (see below)

**File MyContract.sol:**
```
pragma solidity 0.4.24;
import "openzeppelin-solidity/contracts/ownership/Ownable.sol";
contract MyContract is Ownable {
    uint public x = 42;
}
```

**File package.json:**
```
{
  "devDependencies": {
    "truffle": "4.1.14",
    "openzeppelin-solidity": "1.12.0"
  }
}
```

**Command-line execution:**
```
npm install
cd project
node ../node_modules/truffle/build/cli.bundled.js compile
```

Thanks

**Comment by nventuro** [comment]
Hmm, weird. I also have truffle installed locally, and am able to compile and test just fine (albeit on Linux). I think Travis is also setup to have it locally installed.

You mentioned you run `node ../node_modules/truffle/build/cli.bundled.js compile`, I worry there may be some differences when truffle is executed that way. Have you tried running `npx truffle compile`? (this is what I use)

For more info on `npx`, read [here](https://www.npmjs.com/package/npx) (afaik, it comes preinstalled with `npm`).

**Comment by barakman** [comment]
@nventuro:
I apologize, unable to reproduce.
Must have missed something, then fixed it implicitly.
Closing this issue.
Thanks.
