### ISSUE TITLE
Improve Ownable events

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1392]
`Ownable` currently has `OwnershipTransferred` and `OwnershipRenounced`: this is inconsistent with the rest of the project. We should get rid of `OwnershipRenounced`, and emit `OwnershipTransferred` both in the constructor (from address 0), and when renouncing (to address 0).

**Comment by Aniket-Engg** [comment]
I think `Transferred` can be declared as `event Transferred ( address from, address too)` . And then we can emit it as:
In Constructor: `emit Transferred(address(0),  _owner)`
In `renounceOwnership` : `emit Transferred( _owner, address(0))`
In `_transferOwnership` : `emit Transferred( _owner,  newOwner)`
