### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Thirdwizard** [OpenZeppelin/openzeppelin-solidity#1399]
Please can I get a guideline on How to Use the OpenZepplin Token, Crowdsale and Bounty Smart Contract.. Like a Comment on each Code in the Smart Contract showing where and what has to be changed. Please I'M NEW. Thanks.

**Comment by mswezey23** [comment]
They have examples located here:
https://github.com/OpenZeppelin/openzeppelin-solidity/tree/master/contracts/examples

To follow what has changed, please look at the commit history here:
https://github.com/OpenZeppelin/openzeppelin-solidity/commits/master

To follow what has changed, per official release, please look here:
https://github.com/OpenZeppelin/openzeppelin-solidity/releases

**Comment by nventuro** [comment]
Thanks @mswezey23 :)

Also, you're welcome to join [our Slack](https://slack.openzeppelin.org/) to ask questions!
