### ISSUE TITLE
Rename supportsInterfaces

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1412]
In `ERC165Checker`, `supportsInterfaces`​ as a function name is very similar to `supportsInterface`, which may be error prone. We should rename this to something more easily distinguishable, I'd go with `supportsAllInterfaces` (to emphasize they all must be supported), but something like `supportsManyInterfaces` (or multiple) would also work.

Also, all `internal` and `private` functons in this contract should have a leading underscore.

**Comment by vlvrd** [comment]
Hey @nventuro, can you assign this one to me?

**Comment by nventuro** [comment]
GitHub won't let me assign issues to new contributors, but feel free to work on this @vlvrd!

**Comment by nventuro** [comment]
Sorry @vlvrd, but we are planning on releasing 2.0 tomorrow and needed to get this fix in :( I addressed it in https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1435. Thanks though!

**Comment by vlvrd** [comment]
Nah nevermind @nventuro, I was planning on tackling your codebase this weekend anyway so I'm sure I'll still find a way to make myself useful (:

Thanks anyway!

**Comment by parkinsonj** [comment]
@nventuro leading underscores in `internal` functions does not make sense in a library IMO.

In a smart contract, I could understand why you might want to have underscores for conceptual reasons such as emulating hidden functions in other languages (although of course that's what the private and internal keywords _actually_ do), but in a library that is used as `using X for Y` then those internal functions are exposed and called like `addr._exposedInternalFunction()` which is simply unnecessary and ugly.
