### ISSUE TITLE
ERC20 implementation has extraneous quantity check

### ISSUE THREAD

**Issue by fulldecent** [OpenZeppelin/openzeppelin-solidity#1454]
The code:

```solidity
  function _burn(address account, uint256 value) internal {
    require(account != 0);
    require(value <= _balances[account]);

    _totalSupply = _totalSupply.sub(value);
    _balances[account] = _balances[account].sub(value);
    emit Transfer(account, address(0), value);
  }
```

From:

> https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/ERC20.sol#L186-L193

Has an unnecessary `require(value <= _balances[account]);` This test is already performed as part of the following line `_balances[account] = _balances[account].sub(value);`.

Likewise for `burnFrom`.

**Comment by Aniket-Engg** [comment]
If that is a case, i think it also applies for `_transfer` & `transferFrom`
