### ISSUE TITLE
Allow subclases of Pausable to modify the _paused state

### ISSUE THREAD

**Issue by elopio** [OpenZeppelin/openzeppelin-solidity#1459]
Note: ​Subclasses of Pausable currently have no access to the ​ _paused​ state variable. Adding internal functions for _pause​ and ​ _unpause​ would allow for subclasses that provide additional functionality. (e.g. a contract that allows for unpausing by any address after a time period has expired)

This issue was reported in the [LevelK](https://www.levelk.io/) audit.

**Comment by nventuro** [comment]
>If the address of the contract is one of the pauses, wouldn't it be able to call the public pause and unpause functions?

Yes, but it'd have to do so through an external call (i.e `address(this).pause()` as opposed to simply `pause()`).

I'm currently somewhat ambivalent regarding adding `internal` functions, but following the current logic, this contract is a clear candidate to have these added.

**Comment by frangio** [comment]
We seem to be aligned on internal functions :P (

**Comment by frangio** [comment]
Also have my doubts regarding internal functions lately. See https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1460#issuecomment-496953925, https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1766#issuecomment-496955838.

Would prefer to keep `Pausable` as is  for now.
