### ISSUE TITLE
Allow subclasses to renounce ownership

### ISSUE THREAD

**Issue by elopio** [OpenZeppelin/openzeppelin-solidity#1460]
Subclasses of ​ Ownable​ are able to transfer ownership but are not able to set ​ _owner​ to a 0 address like ​ renounceOwnership does. Consider exposing an internal function to allow ​ Ownable subclasses to remove the owner.

This issue was reported in the [LevelK](https://www.levelk.io/) audit.

**Comment by nventuro** [comment]
While interesting, I'd rather we leave `Ownable` as-is to focus on other solutions, considering we're moving away from it, and only leaving it in the library for e.g. quick prototypes. This is, however, pretty much the only bit missing from its [API](https://docs.openzeppelin.org/v2.3.0/api/ownership#ownable) to have it 'feature complete'. @frangio thoughts?

**Comment by frangio** [comment]
I prefer keeping `Ownable` as is now. I don't think we have a clear picture yet of exactly what things should be available internally, as we've recently found some internal functions that we're questioning.
