### ISSUE TITLE
On RefundEscrow, add isState function

### ISSUE THREAD

**Issue by elopio** [OpenZeppelin/openzeppelin-solidity#1461]
We recommend replacing all ​ _state​ checks such as require(_state == State.Active);​ with a modifier. (e.g. ​ isState(State.Active)​ )

This issue was reported in the [LevelK](https://www.levelk.io/) audit.

**Comment by obernardovieira** [comment]
Can I do this one, please?

**Comment by elopio** [comment]
Go for it @obernardovieira. Let us know if you need a hand.

**Comment by obernardovieira** [comment]
From my side, yes. I'm just waiting for a review or probably be merged.

**Comment by frangio** [comment]
From https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1475#issuecomment-470255981:
> We have been thinking about this and have decided not to make this change. The main reason is that our coverage analysis tool does not properly work with modifiers
