### ISSUE TITLE
Add clearAllowance to ERC20

### ISSUE THREAD

**Issue by elopio** [OpenZeppelin/openzeppelin-solidity#1463]
an internal function such as _clearAllowance()​ may be useful when a transaction requires a certain amount of token be approved for transfer but, in some cases, transfers none or a fraction of the approved amount.

This issue was reported in the [LevelK](https://www.levelk.io/) audit.

**Comment by Aniket-Engg** [comment]
@elopio In the given case, what will be the functionality of `_clearAllowance()`? Please add a bit more detail.

**Comment by elopio** [comment]
Hey @Aniket-Engg, this issue is tagged for more discussion. We'll add more details when during the next following weeks when we have time to analize it. If you have ideas, feel free to throw them in here.

**Comment by Aniket-Engg** [comment]
Actually i was looking to know the motivation behind the suggestion of this function so that i can brainstorm it.

**Comment by frangio** [comment]
This can already be accomplished by calling `approve(0)`. I'm not sure if the proposed function would add any other functionality that I'm not seeing.

@cwhinfrey Could you expand on this a bit?

**Comment by cwhinfrey** [comment]
@frangio Our thinking was that ERC20 subclasses may want to zero out an account's allowance, even if that account is not `msg.sender`. A real-world use case for this is now escaping me though. It may make sense to hold off until one comes up.

**Comment by nventuro** [comment]
This can be achieved via [`ERC20._approve()`](https://docs.openzeppelin.org/v2.3.0/api/token/erc20#ERC20._approve(address,address,uint256)), introduced in v2.2.0.
