### ISSUE TITLE
Change the name of isContract()

### ISSUE THREAD

**Issue by elopio** [OpenZeppelin/openzeppelin-solidity#1466]
On [Address.sol](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/dac5bccf803696d9d98d269b8c27c7aac5fa1c5c/contracts/utils/Address.sol#L16)

Because this function returns false when called from a contract’s constructor, consider calling this function isInitializedContract()​ for clarity.

This issue was reported in the [LevelK](https://www.levelk.io/) audit.

**Comment by elopio** [comment]
See also https://github.com/ConsenSys/smart-contract-best-practices/blob/master/docs/recommendations.md#avoid-using-extcodesize-to-check-for-externally-owned-accounts

**Comment by nventuro** [comment]
I think the [current warning](https://docs.openzeppelin.org/v2.3.0/api/utils#Address.isContract(address)) is clear enough to consider this done.
