### ISSUE TITLE
Where is openzeppelin-solidity/contracts/token/ERC20/StandardToken.sol?

### ISSUE THREAD

**Issue by kennblvnp** [OpenZeppelin/openzeppelin-solidity#1480]

**Comment by kennblvnp** [comment]
I think I'm gonna use ERC20.sol they have the same codes for StandardToken.sol base in this video https://www.youtube.com/watch?v=_ikc4Ct7wvk.

**Comment by obernardovieira** [comment]
As you can see https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1478, it does not exists anymore. OZv2 has changed a "bit".

**Comment by snario** [comment]
This is generally how to achieve the same effect https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/examples/SimpleToken.sol

**Comment by kennblvnp** [comment]
@obernardovieira Yeah im aware.. so what is the replacement of StandardToken.sol?

**Comment by kennblvnp** [comment]
@snario Yes im using this

**Comment by obernardovieira** [comment]
`2. Find/Replace StandardToken / BurnableToken / MintableToken to ERC20`

There's no StandardToken anymore, only ERC20.

**Comment by pRoy24** [comment]
Hi,
Please update the docs with the same.
I also created a pull request in Truffle Examples repository to reflect the change 
https://github.com/trufflesuite/trufflesuite.com/pull/216

**Comment by CruzMolina** [comment]
Thank you @pRoy24 for updating the docs! @kennblvnp please see this newly updated section: https://github.com/trufflesuite/trufflesuite.com/blob/master/src/tutorials/robust-smart-contracts-with-openzeppelin.md#creating-the-tutorialtoken-smart-contract

**Comment by kennblvnp** [comment]
@CruzMolina @pRoy24  thanks everyone!

**Comment by nventuro** [comment]
Thanks a lot everyone for this! :clap:
