### ISSUE TITLE
Code style in Roles

### ISSUE THREAD

**Issue by vittominacori** [OpenZeppelin/openzeppelin-solidity#1483]
As per your new code style, these should have an underscore prefix as they are private, shouldn't?

`Roles.Role private cappers;` in [CapperRole.sol](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/access/roles/CapperRole.sol#L11)

`Roles.Role private minters;` in [MinterRole.sol](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/access/roles/MinterRole.sol#L11)

`Roles.Role private pausers;` in [PauserRole.sol](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/access/roles/PauserRole.sol#L11)

`Roles.Role private signers;` in [SignerRole.sol](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/access/roles/SignerRole.sol#L11)

**Comment by nventuro** [comment]
You're absolutely right (see [here](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/CODE_STYLE.md#naming) for the relevant rule), thank you for reporting this @vittominacori!
