### ISSUE TITLE
ERC721.sol SafeTransferFrom does not work if msg.sender is approved

### ISSUE THREAD

**Issue by StefanelStan** [OpenZeppelin/openzeppelin-solidity#1497]
Hello. 
I am using the openZeppelin "openzeppelin-solidity": "2.0.0-rc.1", in my dApp project.
As I am testing it with truffle, I have experienced a bug/ or wrong code description.
(I am unable to copy-paste the code due to copy-rights).
Basically the unit tests fail when attempting to do these 3 steps:
1. Mint a token from accounts[0]  OK
2. ERC721.approve (accounts[1], token, {from:accounts[0]); OK
//at this point accouns[0] owns the token and accounts[1] is approved.
3. From the description of `ERC721`
`safeTransferFrom : Requires the msg sender to be the owner, approved, or operator`
safeTransferFrom(accounts[1], accounts[2], tokenId, {from: accounts[1]});
//fails here. If I change the sender & _from to accounts[0] works fine. But I want to test the approved account usability as it's stated in description.
Thanks.
**💻 2.0.0-rc.1 / latest truffle as of 10 Nov 2018**

**📝 **

**🔢 Code to reproduce bug**

**Comment by frangio** [comment]
Hi @StefanelStan. The last step should be <code>safeTransferFrom(__accounts[0]__, accounts[2], tokenId, { from: accounts[1]})</code>.

**Comment by StefanelStan** [comment]
Hi! 
You are right. Thanks for clarifications. In my wrapper function I was setting the from to msg.sender. Got it now. TY
