### ISSUE TITLE
Pull payment helper with multiple withdraws with a single function

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#15]
Lots of security problems (including [the infamous TheDAO hack](http://hackingdistributed.com/2016/06/17/thoughts-on-the-dao-hack/)) can be prevented by using a pull payment strategy (as opposed to pushing payments with `send`).

We already have a simple [PullPayment](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.9.0/contracts/payment/PullPayment.sol) contract, but more comprehensive tools, documentation and examples are needed.

A simple idea is to create a subclass of PullPayment that allows sending money to all pending payees at once.

**Comment by mardlin** [comment]
The user experience of pull payments is much weaker than that of push payments. 

Perhaps something could be done using an external contract as a timer or "cron job runner" to initiate the withdrawal for customers after a certain time.

Dapps which are intended to hold less (ex. https://github.com/makoto/blockparty) value may also be an acceptable use of push payments.

**Comment by maraoz** [comment]
Thanks for the suggestion @mardlin! I love the idea.
It's a very good compromise solution, because a "cron job" that dispatches all the payments would have a cost (owner of the cron job has to pay for all the gas for withdrawals), but it would improve Pull Payments UX by a lot for users!
So, the contract owner is probably motivated to pay for that gas cost. Maybe we could implement another version of PullPayments with a "withdrawAll" method?

**Comment by mardlin** [comment]
> Maybe we could implement another version of PullPayments with a "withdrawAll" method?

That is awesome. In practice, it would often need a modifier on it to ensure that only qualifying deposits are refunded.

**Comment by maraoz** [comment]
What do you mean by "qualifying deposits"?

**Comment by nventuro** [comment]
Closing to reduce issue clutter. Such a feature would probably be implemented via metatransactions, which we're currently working on to improve support.
