### ISSUE TITLE
Add 'shouldFailWithMessage' test helper

### ISSUE THREAD

**Issue by remon-nashid** [OpenZeppelin/openzeppelin-solidity#1502]
**🧐 Motivation**
Exactly as described in issue's title :).

**📝 Details**
First of all, thanks for prividing this awesome framework. It makes creating secure smart contracts actually possible!

I've been importing functions from `openzeppelin-solidity/tests/helpers` to use in my own tests for a couple of weeks. They work perfectly so there's no need to craft my own. Helpers in `shouldFail.js` have been particularly useful.

Aside, from the canned `shouldFail[reverting,throwing,outOfGas]` helpers, I think the generic `shouldFailWithMessage` is flexible and can be used to check for different failure reasons. However, it is not exported by the module.

I suggest exporting it so it could be used externally when neither of `reverting, throwing, outOfGas` fill the bill.

I will follow up with a one liner PR to introduce that change.

Thanks!

**Comment by frangio** [comment]
Glad you find the helpers useful @remon-nashid! We're actually planning on providing a package full of these helpers. Check out https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1204. We'll definitely include `shouldFailWithMessage` in it.

I'm keeping this and the associated PR open until @nventuro comes back online in a few days. He's leading the test helpers project.

**Comment by remon-nashid** [comment]
Fixed by @nventuro's #1513

**Comment by remon-nashid** [comment]
Ah! sorry for the misunderstanding. 

Actually, when I attempted to submit a PR that exports `shouldFail.withMessage`, I realised that revert messages are not exposed by Ganache-cli versions [< 6.1.2](https://github.com/trufflesuite/ganache-cli/releases/tag/v6.1.2). OZ library uses 6.1.0 so we'll need to update it. I can open a new PR to update Ganache-cli but please let me know if you'd prefer to update to 6.1.2 or perhaps leap-frog it to 6.2.X.

Regarding your comment [here](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1503#issuecomment-442798646)

> It did give me an idea for an API though: what if instead of having shouldFailWithMessage we had a withMessage function that checked for the string, and added it to the other shouldFail functions? So we'd end up with:

> ``` 
> shouldFail.withMessage
> shouldFail.reverting.withMessage
> shouldFail.throwing.withMessage
>```

As far as I understand `throw` keyword is an alias to `revert`, and it was removed in solidity 0.5.0. However, exceptions still _throw_ with a message but I believe that message is almost always `invalid opcode`.

If the above is true then we only need `withMessage` and `reverting.withMessage`. They're similar though. What do you think?

**Comment by nventuro** [comment]
>I can open a new PR to update Ganache-cli but please let me know if you'd prefer to update to 6.1.2 or perhaps leap-frog it to 6.2.X.

Given that 6.2 seems bring performance improvements, I don't see a reason to not update to the latest 6.2.x version.

>If the above is true then we only need withMessage and reverting.withMessage. They're similar though. 

Yeah, let's just go with `reverting.withMessage` for now. `withMessage` may be useful e.g. when testing for the errors that other helpers throw, but we don't need that yet.

Thanks a lot @remon-nashid! :)

**Comment by remon-nashid** [comment]
Started working on ganache-cli update in #1535 .

**Comment by remon-nashid** [comment]
Working on exporting test helper + adding unit tests for the helper itself.

**Comment by nventuro** [comment]
This was added to https://github.com/OpenZeppelin/openzeppelin-test-helpers
