### ISSUE TITLE
Adding an Implementation of ERC1538

### ISSUE THREAD

**Issue by mudgen** [OpenZeppelin/openzeppelin-solidity#1504]
**🧐 Motivation**
ERC1538 is a very useful standard for transparent, upgradeable contracts that provides the following benefits:

1. The ability to add, replace or remove multiple functions of a contract atomically (at the same time).
2. Each time a function is added, replaced or removed, it is documented with events.
3. Build trust over time by showing all changes made to a contract.
Unlimited contract size.
4. The ability to query information about functions currently supported by the contract.
5. One contract address that provides all needed functionality and never needs to be replaced by another contract address.
6. The ability for a contract to be upgradeable for a time, and then become immutable.
7. Add trustless guarantees to a contract with "unchangeable functions".

[See ERC1538 for more information.](https://github.com/ethereum/EIPs/issues/1538)

**📝 Details**

Is anybody interested in adding an implementation of this standard to OpenZepplin?  I think it would be a valuable contribution.

**Comment by adibas03** [comment]
@mudgen your implementation in (https://github.com/mudgen/transparent-contracts-erc1538) looks good.
You could create a PR with that

**Comment by frangio** [comment]
Hi @mudgen! We think that upgradeabilty requires a lot more tooling than what's in scope for OpenZeppelin. So our current decision is to leave those matters to [ZeppelinOS](https://zeppelinos.org/).
