### ISSUE TITLE
how to send and receive Eth on contract ?

### ISSUE THREAD

**Issue by liwei00wade** [OpenZeppelin/openzeppelin-solidity#1518]
who can give me an example ?

**Comment by frangio** [comment]
Hi @liwei00wade! Take a look at [`PaymentSplitter`](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/21ed6bee256a3ce5057d8233f5649b9ab16dc7c4/contracts/payment/PaymentSplitter.sol) for an example of a contract that both receives and sends ether.

For this kind of broad question, please [join our Slack community](https://slack.openzeppelin.org/) and ask in the `#beginners` channel.
