### ISSUE TITLE
How to receive an optional data on contract when send Eth to it ?

### ISSUE THREAD

**Issue by liwei00wade** [OpenZeppelin/openzeppelin-solidity#1519]
I found out a field "hex data optional";
I want to receive the data on contract, is it msg.data ?

I will try.

**Comment by frangio** [comment]
Hi @liwei00wade! Depending on what you want to do with the data, sometimes `msg.data` will be enough and other times you will want to define a function. Feel free to browse through this repository to see examples of Solidity code.

For this sort of question, please [join our Slack community](https://slack.openzeppelin.org/) and ask in the `#beginners` channel.
