### ISSUE TITLE
ERC20Detailed should Inherit from ERC20, not IERC20

### ISSUE THREAD

**Issue by ImAllInNow** [OpenZeppelin/openzeppelin-solidity#1536]
If I create a token that inherits from ERC20Detailed, I would also need to inherit from ERC20 to get the implementation, but since ERC20Detailed is not an interface itself, it should properly inherit from ERC20, not IERC20.

**💻 Environment**

2.0.0

**📝 Details**

The standard way I would like to use ERC20Detailed would be to directly inherit from it as in:
```
contract MyToken is ERC20Detailed {
    ...
}
```

But this doesn't get me all of the implementation of an ERC20 so I would also have to inherit from ERC20:
```
contract MyToken is ERC20Detailed, ERC20 {
    ...
}
```

This seems odd to have to inherit both, and, depending on how solidity does it, there are two versions of IERC20 inherited, one through ERC20Detailed and one through ERC20 itself. This doesn't seem right. All of the other subclasses of ERC20 (Mintable, Pausable, etc) inherit from ERC20, not IERC20.

I would think that the code would just have to change from:
```
contract ERC20Detailed is IERC20 {
```

to 
```
contract ERC20Detailed is ERC20 {
```

**Comment by nventuro** [comment]
I think our reasoning with this one was not forcing users of `ERC20Detailed` to also use our `ERC20` implementation, but I'm not sure how strong that argument is, considering it does make usage a bit cumbersome. @frangio thoughts?

**Comment by frangio** [comment]
I don't have too strong an opinion on this, but in any case `ERC20` is not useful by itself unless you extend it, so a concrete `ERC20Detailed` wouldn't be useful either unless you extend it or combine it with `ERC20Mintable`. I feel like it would change usage of the contract by very little so I would not worry about it now, but I'd keep it in mind when we release a new major.
