### ISSUE TITLE
Latest Open Zeppelin ERC20 Contract Implementation - Can't Call functions from Remix IDE using Metamask nor MyEtherWallet

### ISSUE THREAD

**Issue by Dycedlp** [OpenZeppelin/openzeppelin-solidity#1558]
Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 3000948248000000000 and got: 0

It won't let me add more gas to Remix IDE nor MyEtherwallet for the calls.

Similar messages occur when I try to use addMinter(), I can use the transfer function fine with no gas cost, I'm using POA with min-gas-limit 0.  
-------------------------------------------------------------------------------------------------------------------
pragma solidity ^0.4.24;

import "./ERC20Pausable.sol";
import "./ERC20Burnable.sol";
import "./ERC20Capped.sol";

contract Xoticcoin is ERC20Pausable, ERC20Capped, ERC20Burnable {
    uint256 public constant INITIAL_SUPPLY = 100000000000000000000000000000000;
    uint constant public decimals     = 18;
    string constant public name       = "Xotic Coin";
    string constant public symbol     = "XTX";
    
    constructor (uint256 cap) public ERC20Capped(cap) {
        _mint(msg.sender, INITIAL_SUPPLY);
    }

}
-------------------------------------------------------------------------------------------------------------------

**🔢 Code to reproduce bug**
- No code needed can't use minting nor burning functions.  I'm using an Inject Web 3 provider to deploy the contract & call the functions.  Not working.
-------------------------------------------------------------------------------------------------------------------

**Comment by frangio** [comment]
Hi @Dycedlp. What cap are you setting?

**Comment by Dycedlp** [comment]
Thanks Frangio, it was exactly that.  Cheers!  Set it higher than it could handle.  All good.

**Comment by Dycedlp** [comment]
It says Contract Call
Error: Bad instruction
when I make any call like addMinter(), burnFrom(), that stuff.  It doesn't work.
