### ISSUE TITLE
[Meta] 2.1 backports

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-solidity#1566]
This is a list of PRs that have to be cherry-picked into [`release-v2.1.0`](https://github.com/OpenZeppelin/openzeppelin-solidity/tree/release-v2.1.0) before releasing.

- [x] https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1565
- [x] https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1567

**Comment by nventuro** [comment]
Fixed in daa301fef01bf94875579a4785c0e0b2a5896ea7 and 13eff701123038cde1e5282864325b21e70366e4.
