### ISSUE TITLE
ERC20 Private Usage Scenario + Requirements

### ISSUE THREAD

**Issue by Dycedlp** [OpenZeppelin/openzeppelin-solidity#1569]
Initial Smart Contract Requirements:
3.	Ability to burn tokens
a.	Be able to burn tokens at any specific address from the owner account (either determined by who deployed the initial contract or by a variable)
4.	Ability to freeze wallets (one, a range or all)

**Comment by frangio** [comment]
Hi @Dycedlp. I'm closing the issue because there is no question or request, but let me know if there is something we can help you with.
