### ISSUE TITLE
automate publishing to npm, ethpm and tagging in git.

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#157]

**Comment by frangio** [comment]
Consider #607 and #633 if those are merged.

**Comment by jordanglassman** [comment]
Probably pending this issue, but I notice that versions 1.4.0 and 1.5.0 have not been deployed to ethpm yet.

https://www.ethpm.com/registry/packages/25

**Comment by nventuro** [comment]
This is WAY overdue.
