### ISSUE TITLE
Solidity 0.5 upgrade followup: address Ownable.owner needs to be payable

### ISSUE THREAD

**Issue by remon-nashid** [OpenZeppelin/openzeppelin-solidity#1582]
A great job has been done in [release-v2.1.0-solc-0.5](https://github.com/OpenZeppelin/openzeppelin-solidity/tree/release-v2.1.0-solc-0.5) to bring all contracts to 0.5. However, I stumbled upon one `address` variable that should probably be `address payable`. There might be more.

[Owner](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/release-v2.1.0-solc-0.5/contracts/ownership/Ownable.sol#L9) of an `Owanble` contract is expected to receive funds in nemerous cases such as self destruction (e.g `selfdestruct(owner());`), or whenever contract's owner need to withdraw its balance. Hence, owner's address needs to be declared `payable`.

I'm working on a PR against `release-v2.1.0-solc-0.5` branch now.

**Comment by nventuro** [comment]
Hey @remon-nashid!

`Ownable` itself doesn't have the capability for selfdestruction, are you talking about a scenario in which you extend from it?

**Comment by remon-nashid** [comment]
> Hey @remon-nashid!
> 
> `Ownable` itself doesn't have the capability for selfdestruction, are you talking about a scenario in which you extend from it?

Exactly. See `distruct` function in this contract for example: https://github.com/remon-nashid/xia/blob/master/contracts/Lockers.sol#L44

**Comment by nventuro** [comment]
Hm, interesting. We don't usually advocate for `selfdestruct`, but you could however make the same case for e.g. a regular Ether transfer. I worry that this line of though would end up making all addresses payable, rendering the feature useless. A simple cast to `address payable` might be the best way to tackle this. @frangio thoughts?

**Comment by frangio** [comment]
I agree that a cast is the best option here.
