### ISSUE TITLE
Add a whitelister role admin that can reset the whitelist

### ISSUE THREAD

**Issue by Levino** [OpenZeppelin/openzeppelin-solidity#1585]
**🧐 Motivation**
 This is about the [whitelister role](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/63ce358f30d71e5af5f70bbd4db7daea379b7c9b/contracts/access/roles/WhitelisterRole.sol)

Following up on a [comment](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1525#issuecomment-451119421) I made:

So the whitelisting usually will be automated, I suppose. Lets say we have some server side code that verifies some user input data and then adds an address as whitelisted. Now some attacker gets access to this server and uses the whitelister private key to add himself to the whitelisters. Then they could forever temper with the whitelist. Currently there is not way to remove someone from the whitlisters list again.

**📝 Details**
It would be nice to have an additional Owner who can reset the whitelister list.

**Comment by nventuro** [comment]
Hmm, you do have sort of a valid point in that the whitelist admins will usually not sign messages manually, though I wonder how that server would look like. In any case, any automated service that signs messages for an account should be extremely well guarded - not only could the whitelist be tampered with, but funds could be stolen, tokens exchanged, etc.

All in all, I think this requirement is too specific to be part of OpenZeppelin, specially considering we provide the tools for users to implement these custom features on their own. You could either use `Ownable` or create a new role to reset the whitelist, and have your crowdsale also extend from `WhitelistCrowdsale`, thereby allowing pausers to stop the crowdsale process until the issue has been dealt with.

**Comment by nventuro** [comment]
Hey @Levino, we're closing this for now due to the requirement being deemed to specific: we consider such a feature should be part of a user's business logic. Feel free to continue the discussion though if you feel we're in the wrong about this!
