### ISSUE TITLE
Add number of accounts to Role struct (Roles.sol)

### ISSUE THREAD

**Issue by vdrg** [OpenZeppelin/openzeppelin-solidity#1597]
**🧐 Motivation**
It would be nice to have the number of accounts that have a role if you want to limit the maximum number of accounts or require at least one account with a role (multisigs for example, where you never want to remove all the owners/signers).

**📝 Details**
Add `uint256 size` or `uint256 count` to the `Role` struct in `Roles.sol`. It should change when calling `add()` or `remove()`.

Also, I think there shouldn't be any additional restrictions in the library (a minimum of 1 account, etc). The logic for restrictions should be part of the contract using the library.

It is true that this variable could be stored in the contract that uses the library, but as it is a property of the data structure I think it makes sense to include it here.

**Comment by nventuro** [comment]
Hello @vdrg, thanks for this suggestion! I like this idea, and agree with this bit:
>Also, I think there shouldn't be any additional restrictions in the library (a minimum of 1 account, etc). The logic for restrictions should be part of the contract using the library.

This request is related to github.com/OpenZeppelin/openzeppelin-solidity/issues/1602: if we decide to move forward. we'll probably implement both at once.

**Comment by nventuro** [comment]
Closing in favor of #1602.
