### ISSUE TITLE
Can't deploy ERC721 Token contract

### ISSUE THREAD

**Issue by takahser** [OpenZeppelin/openzeppelin-solidity#1619]
I'm trying to deploy a ERC721 token contract, but it fails with an error:

```
,zeppelin-solidity/contracts/token/ERC721/ERC721Token.sol:59:58: TypeError: Data location must be "memory" for return parameter in function, but none was given.
  function tokensOf(address _owner) public view returns (uint256[]) {
                                                         ^-------^
Compilation failed. See above.
```

**💻 Environment**

- **npm packages**

```
    "ganache-cli": "^6.2.5",
    "zeppelin-solidity": "^1.12.0"
```

- Truffle v5.0.2 (core: 5.0.2)
- Node v10.10.0

**📝 Details**

- I followed [this tutorial](https://maksimivanov.com/posts/gradient-coin-tutorial/)
- This is my contract

```
pragma solidity ^0.4.17;

import 'zeppelin-solidity/contracts/token/ERC721/ERC721Token.sol';

import 'zeppelin-solidity/contracts/ownership/Ownable.sol';

contract GradientToken is ERC721Token, Ownable {
  string public constant NAME = "GradientToken";
  string public constant SYMBOL = "GRAD";
}
```

- In my mocha spec I trigger the deployment

```
const GradientToken = artifacts.require("GradientToken");

contract("Gradient token", accounts => {
  it("Should make first account an owner", async () => {
    let instance = await GradientToken.deployed();
    let owner = await instance.owner();
    assert.equal(owner, accounts[0]);
  });
});
```
- I execute the specs using `truffle test` (the spec file is located in the /test directory)
- I get the error as described
- I tried adding a constructor, as described in https://github.com/OpenZeppelin/openzeppelin-solidity/issues/880 . However, it failed with the exact same error message.
- [reproduction repo](https://github.com/takahser/gradient-token-tutorial)

**🔢 Code to reproduce bug**

- see above

**Comment by nventuro** [comment]
Hello @takahser! The issue is that you're using truffle 5 (and therefore Solidity v0.5.0 by default), but the version of OpenZeppelin that you're using is _very_ old (over a year!). Uninstall `zeppelin-solidity` (the old name of the library) and do a fresh install of `openzeppelin-solidity`: you need to use at least v2.1.1 to have v0.5.0 support.

**Comment by nventuro** [comment]
(keep in mind that some stuff changed between your version and the current one, for example, `ERC721Token` is now simply called `ERC721`)
