### ISSUE TITLE
can you please provide a link to recent contracts audit?

### ISSUE THREAD

**Issue by bsadeh** [OpenZeppelin/openzeppelin-solidity#1627]
**🧐 Motivation**

**📝 Details**

**Comment by spalladino** [comment]
Sure! You can read it [here](https://drive.google.com/file/d/1gWUV0qz3n52VEUwoT-VlYmscPxxo9xhc/view), more context in [this post](https://blog.zeppelin.solutions/announcing-openzeppelin-2-0-afb70aaa298d).

**Comment by elopio** [comment]
This should be added to the README or to https://github.com/OpenZeppelin/openzeppelin-solidity/tree/master/audit.
I'm going to leave this open for @frangio to fix.

**Comment by fulldecent** [comment]
A contract audit is no substitute for a well-funded bug bounty!

See #841

**Comment by nventuro** [comment]
Closed via #1664.
