### ISSUE TITLE
Truffle not able to compile the contract despite importing the the contract and npm i open-zappline

### ISSUE THREAD

**Issue by pranavdaa** [OpenZeppelin/openzeppelin-solidity#1631]
I have npm i     "openzeppelin-solidity": "1.12.0"
still error
![image](https://user-images.githubusercontent.com/38764142/52164805-45cb5880-271d-11e9-8b96-ed03d9f53431.png)

also imported it in my contract 

![image](https://user-images.githubusercontent.com/38764142/52164833-bf634680-271d-11e9-84cc-f5c0726c0bb9.png)

**Comment by Aniket-Engg** [comment]
I think contract name you are trying to inherit is named as `ERC721` . Try changing it and see if it works.

**Comment by frangio** [comment]
Hi @pranavdaa! Please share the error that Truffle is printing.

Is the command you ran `npm i "openzeppelin-solidity": "1.12.0"`? If you want to use OpenZeppelin v1 you should run `npm i openzeppelin-solidity@1.12.0`. However, I would strongly recommend installing OpenZeppelin v2 and using Solidity 0.4.

**Comment by pranavdaa** [comment]
@frangio  this worked for me thanks fot the help.

**Comment by frangio** [comment]
You're welcome! Also check out our forum to ask about any new problems you run into.

https://forum.zeppelin.solutions
