### ISSUE TITLE
No way to change name/symbol in ERC721 Metadata

### ISSUE THREAD

**Issue by aakilfernandes** [OpenZeppelin/openzeppelin-solidity#1632]
There's currently no function for changing the name/symbol in ERC621 Metadata Extension.

**Comment by frangio** [comment]
Hi @aakilfernandes! Thanks for this suggestion.

However, is changing name and symbol actually allowed in ERC721? It sounds more like something that should always remain the same for a particular token.

**Comment by aakilfernandes** [comment]
I don't think including a public setName or setSymbol is warranted, but for child contracts it would be nice to give the owner an option.

As for the "should it be changeable", I think yes in that name and symbol are only for user interfaces anyway, not security. If you're using name and symbol to prevent phishing, you're doing it wrong. Any contract can claim to be the CryptoKitty contract. The only way to verify is to check the address of the contract against another source.

I think there should be central contract where names and symbols are managed with permissions and duplication is prevented, but I think the ship has sailed on that.

**Comment by frangio** [comment]
Right, precisely because names are meant for user interfaces, it's important to understand whether UIs assume this metadata to be fixed or not. My intuition is that they will load the name and symbol once and cache it.

Have you run into the need for this feature yourself?

I'm leaning towards not including it.

**Comment by fulldecent** [comment]
I agree that setting it should be outside the scope of OZ's implementation.

Yes, you *could* change the name and symbol. And there's a lot of other things you can do. But we expect few people will do this so the way people will do that is to subclass an existing implementation like OZ and then add this feature.

**Comment by nventuro** [comment]
Agree with both @frangio and @fulldecent, closing this.
