### ISSUE TITLE
Error message for require in Ownable 

### ISSUE THREAD

**Issue by josojo** [OpenZeppelin/openzeppelin-solidity#1634]
**🧐 Motivation**
Improving the quality of code

**📝 Details**
The referenced require statement (Ownable contract,` modifier onlyOwner()` ) should output an Error, in case the require fails. This helps to debug and is also good for testing

**Comment by frangio** [comment]
Hi @josojo! Thanks for the suggestion. We should add revert reasons soon! I'm closing this issue in favor of the one we already have: #888.
