### ISSUE TITLE
Various non-functional typos and code intention suggestions

### ISSUE THREAD

**Issue by nikeshnazareth** [OpenZeppelin/openzeppelin-solidity#1643]
While looking through the codebase I found some non-functional typos and potential mismatches between comments and code intention. I thought addressing these could be a good first pull request.

Below is the list of suggested changes. If you're happy for me to make them, should I open a separate pull request per change, or a single one for all of them?

Sorry for the wall of text! I thought it would be less intrusive than opening lots of issues.
### Spelling/Grammar

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/token/ERC20/ERC20.sol#L93
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/token/ERC20/ERC20.sol#L108
Suggested change (on both lines): replace **allowed_[_spender]** with **_allowed[spender]**

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/utils/Arrays.sol#L11-L20
Suggested changes: 
   - fix typo in the word **algorithm**
   - replace **it's** with **its**
   - fix typo in the word **greater**
  - replace **to be find** with **to be found**

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/test/ownership/Ownable.behavior.js#L19
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/test/ownership/Secondary.test.js#L32
Suggested change: fix typo in the word **transferring** in both cases

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/test/lifecycle/Pausable.test.js#L20
Suggested change: fix typo in the word **unpaused**

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/ownership/Ownable.sol#L46
Suggested change: "Renouncing ownership..."

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/crowdsale/Crowdsale.sol#L14-L15
Suggested change: "The external interface...**conforms** the base architecture... **It is** *not* intended..."

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/drafts/Counters.sol#L11
Suggested change: using **Counters** for **Counters**.Counter;

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/token/ERC721/ERC721Enumerable.sol#L170-L171
Suggested change: fix typo in the variable name *lastTokenId*

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/test/token/ERC721/ERC721PausedToken.behavior.js#L58
Suggested change: fix typo in the work **existence**

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/crowdsale/Crowdsale.sol#L68
Suggested change: "other contracts will transfer **funds**"

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/crowdsale/price/IncreasingPriceCrowdsale.sol#L31
Suggested change: fix typo in the word **doesn't**

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/test/crowdsale/IncreasingPriceCrowdsale.test.js#L34
Suggested change: "reverts with a final **rate** equal to the initial rate"

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/test/crowdsale/AllowanceCrowdsale.test.js#L57
Suggested change: fix typo in the word **allowance**

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/payment/escrow/RefundEscrow.sol#L86
Suggested change: fix typo in the word **overridden**

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/drafts/ERC20Migrator.sol#L20
Suggested change: fix typo in the word **transferred**

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/drafts/SignatureBouncer.sol#L32
Suggested change: fix typo in the variable name **_signature**

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/drafts/SignatureBouncer.sol#L59
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/drafts/SignatureBouncer.sol#L67
Suggested change: fix typo in the word **specified** on both lines

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/test/drafts/SignedSafeMath.test.js#L22
Suggested change: fix typo in the word **positive**

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/drafts/TokenVesting.sol#L15
Suggested change: Add a space before the (final) word **Therefore**

### Code Intention
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/ownership/Ownable.sol#L45-L48
Suggested change: move the line about the `onlyOwner` modifier to the @dev comment. A generic user wouldn't know what that means. 

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/token/ERC20/ERC20.sol#L53-L61
Suggested change: shouldn't the @dev comment be "Transfer token **to** a specified address" ?

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/token/ERC721/ERC721Enumerable.sol#L36-L37
Suggested change: conform to **ERC721Enumerable via ERC165**

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/test/crowdsale/AllowanceCrowdsale.test.js#L75-L80
Should the test be named "when token wallet is the zero address"? That seems to be what is being tested.

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/crowdsale/distribution/FinalizableCrowdsale.sol#L6-L11
Suggested change: "Extension of **TimedCrowdsale**". It is (transitively) an extension of `Crowdsale` but isn't it preferable to be specific? 

Similarly, this could say "Extension of **FinalizableCrowdsale**"
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/crowdsale/distribution/RefundableCrowdsale.sol#L7-L17

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/test/payment/PaymentSplitter.test.js#L87
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/test/payment/PaymentSplitter.test.js#L93
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/test/payment/PaymentSplitter.test.js#L99
Suggested change: remove the unused second parameter 'ether' to the `ether` function on all three lines

---
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/drafts/SignatureBouncer.sol#L74-L78
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/drafts/SignatureBouncer.sol#L82-L86
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/40d15146c46c0b26960e1eae0c0b27bf8258a729/contracts/drafts/SignatureBouncer.sol#L94-L99
Suggested change: rename the `account` parameter to `sender` in all three cases. These functions have comments that say `sender` when referring to the variable `account`. I think it would be clearer if either the comments or the variable names were updated for consistency. Since `account` is always set to `msg.sender` and the intention of the functions is to validate that the message sender is authorised to perform the action, I suggest renaming the variable to `sender`.

**Comment by nventuro** [comment]
Wow @nikeshnazareth, these are absolutely great! Thank you so much for your thorough work with this.

I'd say a single PR should fit these fine, since it'll be way easier for you to create and us to manage, and we can always discuss individual changes as review comments.
