### ISSUE TITLE
Add redundant address guard to ERC20Migrator migrate function

### ISSUE THREAD

**Issue by nikeshnazareth** [OpenZeppelin/openzeppelin-solidity#1656]
This is just a code style issue and I'm not sure if it's intentional, but I'm mentioning it in case it's an oversight. 

Consider the `ERC20Migrator` `migrate` function:
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/a1f168be961b6c2f7592716864d7b9b104365476/contracts/drafts/ERC20Migrator.sol#L78-L87

This could be called before `beginMigration` is called, which means `_newToken` is not set (it defaults to zero). Such a call would (correctly) fail, because `_newToken.mint` is undefined.

However, it seems to me that the OZ defensive programming style is to check preconditions and explicitly fail if they are not met. To that end, this function could have the guard:
> `require(address(_newToken) != address(0));`

I'm happy to make the PR if you agree

**Comment by nventuro** [comment]
Thanks for spotting this @nikeshnazareth! I agree with your assesment, an explicit check is better than our current behavior of relying on `call` failing.

For reference, the reason why `newToken` isn't set at construction time and `beginMigration` needs to exist, is that said token will be an `ERC20Mintable`, with `ERC20Migrator` set as a minter. This obviously cannot be done before creation (at least not without using `CREATE2` :stuck_out_tongue:).
