### ISSUE TITLE
SafeERC20 inaccurate comment - Does not revert on non-true value

### ISSUE THREAD

**Issue by felix2feng** [OpenZeppelin/openzeppelin-solidity#1692]
@nventuro We have considered migrating our own implementation of SafeERC20 with the OpenZeppelin one and found that Tokens that return numbers in approve/transferFrom operations do not revert. In the code itself, it says that the return value must be true.

See here for a mock token you can test against:
https://github.com/SetProtocol/set-protocol-contracts/blob/master/contracts/mocks/tokens/InvalidReturnTokenMock.sol

**Comment by Skyge** [comment]
I am not sure what do you mean? ` return numbers in approve/transferFrom operations do not revert`?

**Comment by frangio** [comment]
Hi @felix2feng. When an operation has a a return value, `SafeERC20` interprets it exactly as Solidity would, for backwards compatibility. If a contract returns a non-zero number in place of a bool, Solidity will interpret it as `true`, and so `SafeERC20` considers it a success and does not revert.

You're right that the comment is not accurate. We should change it to reflect the actual semantics.

https://github.com/OpenZeppelin/openzeppelin-solidity/blob/cf7375d6b873afc9f705e329db39e2ef389af9d2/contracts/token/ERC20/SafeERC20.sol#L48

I'm not sure what Set are doing but IMO a return value of 4 should not be considered a failure.
