### ISSUE TITLE
Inconsistent punctuation use in comments

### ISSUE THREAD

**Issue by Flash-Git** [OpenZeppelin/openzeppelin-solidity#1697]
There doesn't appear to be a standard when it comes to whether to have a periods in the comments above contract functions.

[ERC721.sol](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/ERC721.sol
)
```
/**
  * @dev Gets the owner of the specified token ID
  * @param tokenId uint256 ID of the token to query the owner of
  * @return address currently marked as the owner of the given token ID
  */
/**
  * @dev Approves another address to transfer the given token ID
  * The zero address indicates there is no approved address.
  * There can only be one approved address per token at a given time.
  * Can only be called by the token owner or an approved operator.
  * @param to address to be approved for the given token ID
  * @param tokenId uint256 ID of the token to be approved
  */
```

[ERC20.sol](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/ERC20.sol
)
```
/**
  * @dev Gets the balance of the specified address.
  * @param owner The address to query the balance of.
  * @return A uint256 representing the amount owned by the passed address.
  */
/**
  * @dev Transfer token to a specified address
  * @param to The address to transfer to.
  * @param value The amount to be transferred.
  */
```

I don't know why I noticed...

**Comment by frangio** [comment]
Thanks for spotting this!

All `@dev` documentation should have punctuation. I'm not sure about `@param`. We are planning to write a style guide for this soon, but this simple criteria should be enough if someone is interested in making a PR for it.

**Comment by Flash-Git** [comment]
I don't mind doing it if I have time this afternoon.

**Comment by nventuro** [comment]
We've updated all of the @dev comments (which now have consistent punctuation). A style guide is missing still (though to be fair it may be too early to write one).
