### ISSUE TITLE
Refactoring function ownerOf in ERC721.sol

### ISSUE THREAD

**Issue by zhek** [OpenZeppelin/openzeppelin-solidity#1701]
Check the presence of a token using the function  _exists.  Now the ownerOf function corresponds to the getApproved function.

```
function ownerOf(uint256 tokenId) public view returns (address) {
        require(_exists(tokenId));
        return _tokenOwner[tokenId];
}
```

**Comment by princesinha19** [comment]
can you explain in detail @zhek

**Comment by zhek** [comment]
> can you explain in detail @zhek

In the proposed variant, the existence of the token is checked using the _exists function. As already done in the getApproved function.

**Comment by princesinha19** [comment]
okay. But I don't think that there is much need for this. I had a look into the code, I think we should do more error handling and checks in all functions. what do you think @frangio @nventuro?
If you want I can create a PR.

**Comment by nventuro** [comment]
Hello @zhek! I'm not sure what you mean, are you suggesting rewriting `_exists` in terms of `ownerOf`?

**Comment by princesinha19** [comment]
@nventuro I think he mean that we should first check, is the token e exists using _exists() in ownerOf() method. Just like getApproved().

**Comment by nventuro** [comment]
Ahh, I see. For reference for everyone else, these are the functions being discussed:

```
function ownerOf(uint256 tokenId) public view returns (address) {
    address owner = _tokenOwner[tokenId];
    require(owner != address(0));
    return owner;
}

function _exists(uint256 tokenId) internal view returns (bool) {
    address owner = _tokenOwner[tokenId];
    return owner != address(0);
}
```

Yes, I did think of that when revising `ownerOf` recently, but unfortunately due to how Solidity's codegen works, that would mean performing an extra `SLOAD` (since `_exists` doesn't return the owner). I think `ownerOf` is short and readable enough that the benefit of performing that deduplication may not be warranted. @frangio thoughts on this?

**Comment by zhek** [comment]
> @nventuro I think he mean that we should first check, is the token e exists using _exists() in ownerOf() method. Just like getApproved().

yes

**Comment by princesinha19** [comment]
> @nventuro I think he mean that we should first check, is the token e exists using _exists() in ownerOf() method. Just like getApproved().
> 
> yes
https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1701#issuecomment-478905701

I did this too in my PR #1702. Please have a look @nventuro.

**Comment by frangio** [comment]
I agree with @nventuro that the code is short enough that we should prioritize the cheaper implementation.
