### ISSUE TITLE
Couldn't burn tokens by accessing from contract even after approval

### ISSUE THREAD

**Issue by smrMadhan7** [OpenZeppelin/openzeppelin-solidity#1705]
I'm trying to call burnFrom() in the token from a contract by creating a interface object. After approval transferFrom() works fine whereas an error thrown while calling burnFrom().

for example, I've token X deployed. I'm calling it from an other contract with IERC20 tokenX object.

function burnToken(address _address,uint256 value) public{
        Token.burnFrom(_address,value);
    }

**Comment by Skyge** [comment]
Yeah, what is the  error? 
I think when we use  the function `approve()`, what we are doing actually is that 
```
tokenOwner => spender => tokenAmount
```
 so if we want to call the function `burnFrom()` by this way `Token.burnFrom(_address,value);`, what we should do is that at first,` approve(contractB, value)`, then just call `Token.burnFrom(_address,value);` in the contractB. I think this will be OK. But it will be some weird, you can refer to this contract [ERC20Burnable.sol](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/ERC20Burnable.sol).
By the way, OpenZeppelin has a [forum](https://forum.zeppelin.solutions ), if you have time, you can glance over it.

**Comment by Skyge** [comment]
Yeah, what is the  error? 
You can refer to this contract [ERC20Burnable.sol](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/ERC20Burnable.sol). I think your way is a little weird.

**Comment by nventuro** [comment]
Could you share your setup in greater detail? Keep in mind that if you call `burnFrom` from another contract, then _that contract_ is the one that you need to approve.

**Comment by smrMadhan7** [comment]
> Could you share your setup in greater detail? Keep in mind that if you call `burnFrom` from another contract, then _that contract_ is the one that you need to approve.

Yeah, I've done that. That's why I mentioned transferFrom() works fine.

This is the code I'm executing. The token is created with open zeppelin 0.5.2 standard. I've an interface which has burnFrom(). I just don't get it, If transferFroms works in the sense burnFrom() should also work. But its throwing an error
 function returnToken(uint256 _amount) public returns(bool){
       
        require(HeliusToken.balanceOf(msg.sender)>=_amount);
        require(hasInvested[_address] == true);
        
       Token.burnFrom(msg.sender,address(this),_amount);
        //getPropertyTokens(msg.sender,_amount);
       
    }

**Comment by smrMadhan7** [comment]
Yeah, I've done that. That's why I mentioned transferFrom() works fine.

This is the code I'm executing. The token is created with open zeppelin 0.5.2 standard. I've an interface which has burnFrom(). I just don't get it, If transferFroms works in the sense burnFrom() should also work. But its throwing an error.

function returnToken(uint256 _amount) public returns(bool){
    require(Token.balanceOf(msg.sender)>=_amount);
    require(hasInvested[_address] == true);
    
   Token.burnFrom(msg.sender,_amount);
    //getPropertyTokens(msg.sender,_amount);   
}
P.s The user has enough balance and error not occured by require statements.

**Comment by nventuro** [comment]
Could you share a snippet of how you call `transferFrom `in that contract?

**Comment by Skyge** [comment]
contract `ERC20Burnable.sol` is that:
```
pragma solidity ^0.5.0;

import "./ERC20.sol";

contract ERC20Burnable  {
    
    ERC20 erc20;
    constructor(address _ERC20Address) public {
        erc20 = ERC20(_ERC20Address);
    }
 
    function burnFrom(address from, uint256 value) public {
        erc20._burnFrom(from, value);
    }
}
```
contract` ERC20.sol` is:
```
pragma solidity 0.5.0;

import "./IERC20.sol";
import "./SafeMath.sol";

contract ERC20 is IERC20 {
    using SafeMath for uint256;

    mapping (address => uint256) private _balances;

    mapping (address => mapping (address => uint256)) private _allowed;

    uint256 private _totalSupply;
    
    constructor() public {
        _balances[msg.sender] = 10000;
        _totalSupply = 10000;
    }

    function allowance(address owner, address spender) public view returns (uint256) {
        return _allowed[owner][spender];
    }

    function approve(address spender, uint256 value) public returns (bool) {
        _approve(msg.sender, spender, value);
        return true;
    }

    function _transfer(address from, address to, uint256 value) internal {
        require(to != address(0));

        _balances[from] = _balances[from].sub(value);
        _balances[to] = _balances[to].add(value);
        emit Transfer(from, to, value);
    }

    function _burn(address account, uint256 value) internal {
        require(account != address(0));

        _totalSupply = _totalSupply.sub(value);
        _balances[account] = _balances[account].sub(value);
        emit Transfer(account, address(0), value);
    }

    function _approve(address owner, address spender, uint256 value) internal {
        require(spender != address(0));
        require(owner != address(0));

        _allowed[owner][spender] = value;
        emit Approval(owner, spender, value);
    }

    function _burnFrom(address account, uint256 value) public {
        _burn(account, value);
        _approve(account, msg.sender, _allowed[account][msg.sender].sub(value));
    }
}
```
Deploy the contract `ERC20.sol`  with the account1, then deploy the contract `ERC20Burnable.sol`, call `approve(address(account1), address(ERC20Burnable), 100)`, then call `burnFrom(address(account1), 50 )`, it will be OK, it will burn the `ERC20Burnable` approval token, but I think this way is a little weird. I prefer [this way](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/ERC20Burnable.sol)

**Comment by nventuro** [comment]
@Skyge to clarify, I was requesting @smrMadhan7 to post a snippet of _their_ contract with the `transferFrom` call.

**Comment by Skyge** [comment]
Yeah, I also think he should provide more details about his contract, in order to we can quickly help him solve it.

**Comment by smrMadhan7** [comment]
This is the code used for token.
pragma solidity 0.5.0;

import "./Roles.sol";
import "./MinterRole.sol";
import "./Ownable.sol";

/**
 * @title SafeMath
 * @dev Unsigned math operations with safety checks that revert on error
 */
library SafeMath {
    /**
     * @dev Multiplies two unsigned integers, reverts on overflow.
     */
    function mul(uint256 a, uint256 b) internal pure returns (uint256) {
        // Gas optimization: this is cheaper than requiring 'a' not being zero, but the
        // benefit is lost if 'b' is also tested.
        // See: https://github.com/OpenZeppelin/openzeppelin-solidity/pull/522
        if (a == 0) {
            return 0;
        }

        uint256 c = a * b;
        require(c / a == b);

        return c;
    }

    /**
     * @dev Integer division of two unsigned integers truncating the quotient, reverts on division by zero.
     */
    function div(uint256 a, uint256 b) internal pure returns (uint256) {
        // Solidity only automatically asserts when dividing by 0
        require(b > 0);
        uint256 c = a / b;
        // assert(a == b * c + a % b); // There is no case in which this doesn't hold

        return c;
    }

    /**
     * @dev Subtracts two unsigned integers, reverts on overflow (i.e. if subtrahend is greater than minuend).
     */
    function sub(uint256 a, uint256 b) internal pure returns (uint256) {
        require(b <= a);
        uint256 c = a - b;

        return c;
    }

    /**
     * @dev Adds two unsigned integers, reverts on overflow.
     */
    function add(uint256 a, uint256 b) internal pure returns (uint256) {
        uint256 c = a + b;
        require(c >= a);

        return c;
    }

    /**
     * @dev Divides two unsigned integers and returns the remainder (unsigned integer modulo),
     * reverts when dividing by zero.
     */
    function mod(uint256 a, uint256 b) internal pure returns (uint256) {
        require(b != 0);
        return a % b;
    }
}
/**
 * @title ERC20 interface
 * @dev see https://github.com/ethereum/EIPs/issues/20
 */
interface IERC20 {
    function transfer(address to, uint256 value) external returns (bool);

    function approve(address spender, uint256 value) external returns (bool);

    function transferFrom(address from, address to, uint256 value) external returns (bool);

    function totalSupply() external view returns (uint256);

    function balanceOf(address who) external view returns (uint256);

    function allowance(address owner, address spender) external view returns (uint256);

    event Transfer(address indexed from, address indexed to, uint256 value);

    event Approval(address indexed owner, address indexed spender, uint256 value);
}

/**
 * @title Standard ERC20 token
 *
 * @dev Implementation of the basic standard token.
 * https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md
 * Originally based on code by FirstBlood:
 * https://github.com/Firstbloodio/token/blob/master/smart_contract/FirstBloodToken.sol
 *
 * This implementation emits additional Approval events, allowing applications to reconstruct the allowance status for
 * all accounts just by listening to said events. Note that this isn't required by the specification, and other
 * compliant implementations may not do it.
 */
contract ERC20 is IERC20 {
    using SafeMath for uint256;

    mapping (address => uint256) private _balances;

    mapping (address => mapping (address => uint256)) private _allowed;

    uint256 private _totalSupply;

    /**
     * @dev Total number of tokens in existence
     */
    function totalSupply() public view returns (uint256) {
        return _totalSupply;
    }

    /**
     * @dev Gets the balance of the specified address.
     * @param owner The address to query the balance of.
     * @return An uint256 representing the amount owned by the passed address.
     */
    function balanceOf(address owner) public view returns (uint256) {
        return _balances[owner];
    }

    /**
     * @dev Function to check the amount of tokens that an owner allowed to a spender.
     * @param owner address The address which owns the funds.
     * @param spender address The address which will spend the funds.
     * @return A uint256 specifying the amount of tokens still available for the spender.
     */
    function allowance(address owner, address spender) public view returns (uint256) {
        return _allowed[owner][spender];
    }

    /**
     * @dev Transfer token for a specified address
     * @param to The address to transfer to.
     * @param value The amount to be transferred.
     */
    function transfer(address to, uint256 value) public returns (bool) {
        _transfer(msg.sender, to, value);
        return true;
    }

    /**
     * @dev Approve the passed address to spend the specified amount of tokens on behalf of msg.sender.
     * Beware that changing an allowance with this method brings the risk that someone may use both the old
     * and the new allowance by unfortunate transaction ordering. One possible solution to mitigate this
     * race condition is to first reduce the spender's allowance to 0 and set the desired value afterwards:
     * https://github.com/ethereum/EIPs/issues/20#issuecomment-263524729
     * @param spender The address which will spend the funds.
     * @param value The amount of tokens to be spent.
     */
    function approve(address spender, uint256 value) public returns (bool) {
        _approve(msg.sender, spender, value);
        return true;
    }

    /**
     * @dev Transfer tokens from one address to another.
     * Note that while this function emits an Approval event, this is not required as per the specification,
     * and other compliant implementations may not emit the event.
     * @param from address The address which you want to send tokens from
     * @param to address The address which you want to transfer to
     * @param value uint256 the amount of tokens to be transferred
     */
    function transferFrom(address from, address to, uint256 value) public returns (bool) {
        _transfer(from, to, value);
        _approve(from, msg.sender, _allowed[from][msg.sender].sub(value));
        return true;
    }

    /**
     * @dev Increase the amount of tokens that an owner allowed to a spender.
     * approve should be called when allowed_[_spender] == 0. To increment
     * allowed value is better to use this function to avoid 2 calls (and wait until
     * the first transaction is mined)
     * From MonolithDAO Token.sol
     * Emits an Approval event.
     * @param spender The address which will spend the funds.
     * @param addedValue The amount of tokens to increase the allowance by.
     */
    function increaseAllowance(address spender, uint256 addedValue) public returns (bool) {
        _approve(msg.sender, spender, _allowed[msg.sender][spender].add(addedValue));
        return true;
    }

    /**
     * @dev Decrease the amount of tokens that an owner allowed to a spender.
     * approve should be called when allowed_[_spender] == 0. To decrement
     * allowed value is better to use this function to avoid 2 calls (and wait until
     * the first transaction is mined)
     * From MonolithDAO Token.sol
     * Emits an Approval event.
     * @param spender The address which will spend the funds.
     * @param subtractedValue The amount of tokens to decrease the allowance by.
     */
    function decreaseAllowance(address spender, uint256 subtractedValue) public returns (bool) {
        _approve(msg.sender, spender, _allowed[msg.sender][spender].sub(subtractedValue));
        return true;
    }

    /**
     * @dev Transfer token for a specified addresses
     * @param from The address to transfer from.
     * @param to The address to transfer to.
     * @param value The amount to be transferred.
     */
    function _transfer(address from, address to, uint256 value) internal {
        require(to != address(0));

        _balances[from] = _balances[from].sub(value);
        _balances[to] = _balances[to].add(value);
        emit Transfer(from, to, value);
    }

    /**
     * @dev Internal function that mints an amount of the token and assigns it to
     * an account. This encapsulates the modification of balances such that the
     * proper events are emitted.
     * @param account The account that will receive the created tokens.
     * @param value The amount that will be created.
     */
    function _mint(address account, uint256 value) internal {
        require(account != address(0));

        _totalSupply = _totalSupply.add(value);
        _balances[account] = _balances[account].add(value);
        emit Transfer(address(0), account, value);
    }

    /**
     * @dev Internal function that burns an amount of the token of a given
     * account.
     * @param account The account whose tokens will be burnt.
     * @param value The amount that will be burnt.
     */
    function _burn(address account, uint256 value) internal {
        require(account != address(0));

        _totalSupply = _totalSupply.sub(value);
        _balances[account] = _balances[account].sub(value);
        emit Transfer(account, address(0), value);
    }

    /**
     * @dev Approve an address to spend another addresses' tokens.
     * @param owner The address that owns the tokens.
     * @param spender The address that will spend the tokens.
     * @param value The number of tokens that can be spent.
     */
    function _approve(address owner, address spender, uint256 value) internal {
        require(spender != address(0));
        require(owner != address(0));

        _allowed[owner][spender] = value;
        emit Approval(owner, spender, value);
    }

    /**
     * @dev Internal function that burns an amount of the token of a given
     * account, deducting from the sender's allowance for said account. Uses the
     * internal burn function.
     * Emits an Approval event (reflecting the reduced allowance).
     * @param account The account whose tokens will be burnt.
     * @param value The amount that will be burnt.
     */
    function _burnFrom(address account, uint256 value) internal {
        _burn(account, value);
        _approve(account, msg.sender, _allowed[account][msg.sender].sub(value));
    }
}

/**
 * @title Burnable Token
 * @dev Token that can be irreversibly burned (destroyed).
 */
contract ERC20Burnable is ERC20,MinterRole  {
    /**
     * @dev Burns a specific amount of tokens.
     * @param value The amount of token to be burned.
     */
    function burn(uint256 value) public {
        _burn(msg.sender, value);
    }

    /**
     * @dev Burns a specific amount of tokens from the target address and decrements allowance
     * @param from address The account whose tokens will be burned.
     * @param value uint256 The amount of token to be burned.
     */
    function burnFrom(address from, uint256 value) public {
        _burnFrom(from, value);
    }
}

contract XToken is ERC20Burnable  { 
    
  string public name="X Token";
  string public symbol="X";
  uint8 public decimals=18;
 
  
  /**
     * @dev Function to mint tokens
     * @param to The address that will receive the minted tokens.
     * @param value The amount of tokens to mint.
     * @return A boolean that indicates if the operation was successful.
     */
    function mint(address to, uint256 value) public onlyMinter returns (bool) {
        _mint(to, value);
        return true;
    }


}

**This is the interface used.**

interface Minter{
    function mint(address to, uint256 value)  external returns (bool);
    function totalSupply() external view returns (uint256);
    function balanceOf(address who) external view returns (uint256);
    function transferFrom(address from, address to, uint256 value) external returns (bool);
    function transfer(address to, uint256 value) external returns (bool);
    function burnFrom(address from, uint256 value) external returns (bool);
    function burn(uint256 value) external returns (bool);
}

**In main contract, I've used the following code. In this transferFrom() works fine, replacing it with burnFrom() throws error.**

 constructor(Minter _XToken) public{
        XToken = _XToken;       
    }

function returnTokens(uint256 _amount) public returns(bool){
       
        require(XToken.balanceOf(msg.sender)>=_amount);
        //require(hasInvested[_address] == true);
        
        XToken.transferFrom(msg.sender,address(this),_amount);
              
    }

**Comment by Skyge** [comment]
It looks like a standard contract, so I think it will work fine. So if `accountA` has 100 tokens, then he calls `approve(accountB, 50)` to give `accountB` approval 50 token, if `accountB` want to burn 30 tokens, then ha can call `burnFrom (accountA, 30)`.

**Comment by smrMadhan7** [comment]
@Skyge  I too thought the same, but it didn't work. I even went through the code multiple times, nothing seems odd.

**Comment by smrMadhan7** [comment]
Thanks @Skyge

**Comment by frangio** [comment]
@smrMadhan7 We're not giving up on helping you to make this code work.

So, to be clear, you're replacing `XToken.transferFrom(msg.sender,address(this),_amount)` with `XToken.burnFrom(msg.sender,_amount)`, right?

Your code looks very weird for a couple of reasons. Why are you defining your own `ERC20Burnable` with `MinterRole`? You should be using OpenZeppelin contracts as-is. You can use `ERC20Burnable` and `ERC20Mintable` here. I'd recommend to change `XToken` to use those contracts.

---

We can continue this conversation here now, but for future questions like this please [join our forum](http://forum.zeppelin.solutions/) and post over there. :slightly_smiling_face:

**Comment by Skyge** [comment]
I've helped him out in private, so he closed the issue, the exact reason is that he wrote an interface, it is OK that he gave a return value in a function, but when he rewrote the function, he forgot to give a return value, so it always throws out an error.

**Comment by SuperDev321** [comment]
Hello, @Skyge 
Could you help me on same issue?
I don't use return value, but still get error.

**Comment by frangio** [comment]
Please ask in the [OpenZeppelin Forum](https://forum.openzeppelin.com/).
