### ISSUE TITLE
Add backwards compatilibty with ERC20 for ERC777

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1731]
A major feature of ERC777 is that it can be used as if it were an ERC20 token: we should implement this interface to enable this use case.

Due to ERC777's state variables being private, the most straightforward way to achieve this would be by having this backward compatibility baked-in into the contract. We could then provide a second contract that disables the ERC20 functions (by calling `revert` on them) for users to opt-out of this compatibility.

**Comment by frangio** [comment]
I don't think we should provide the non-ERC20-compatible contract for now. Let's wait and see if there is demand for it.
