### ISSUE TITLE
npm install error in Windows

### ISSUE THREAD

**Issue by startgeek** [OpenZeppelin/openzeppelin-solidity#1738]
when I try to npm install openzeppeli-solidity I reach this err:

os: windows 10

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openzeppelin-docsite@github:OpenZeppelin/openzeppelin-docsite#1a0e1a2a151445f9343cc59e15ccd57d99863f1a postinstall: ln -sf sidebars.json.js sidebars.json
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzeppelin-docsite@github:OpenZeppelin/openzeppelin-docsite#1a0e1a2a151445f9343cc59e15ccd57d99863f1a postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in
```

i cleaned npm cache but nothing so far
I can't complete my pull request because of this and TimeFrame future is delayed
Also there are tons of deprecated warning's

**Comment by frangio** [comment]
Thanks for reporting this @startgeek. I think I've fixed it (b84c145c). Could you please try now?

**Comment by startgeek** [comment]
nope still same error bro


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openzeppelin-docsite@github:OpenZeppelin/openzeppelin-docsite#a21e2688298f6f612d69212973a7e56bc1455f57 postinstall: `scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzeppelin-docsite@github:OpenZeppelin/openzeppelin-docsite#a21e2688298f6f612d69212973a7e56bc1455f57 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by startgeek** [comment]
i deleted package.lockjson before and try but still no progress
and funny thing it,s working on my MacOs MOHAVE

**Comment by frangio** [comment]
Please try again now.

**Comment by startgeek** [comment]
congratulations @frangio 

added 1578 packages from 1503 contributors and audited 226267 packages in 359.087s
found 7 vulnerabilities (1 low, 3 moderate, 3 high)
run `npm audit fix` to fix them, or `npm audit` for details 

works like a charm

**Comment by frangio** [comment]
I'm glad. To be honest though, I doubt that the available scripts we have, like `npm run test`, will work... It's hard for us to support a Windows development environment because we don't use one. I would recommend to test your pull requests on Travis instead of locally.
