### ISSUE TITLE
Does solc calculate a keccak256(...) constant at compile time?

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-solidity#1740]
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/86f214b7a3cb6b938463a3509ccd273ad7a04d44/contracts/drafts/ERC777/ERC777.sol#L28-L29

Last time I checked (several months ago), this resulted in the `keccak256` _calculation_ being inlined in the code, instead of the resulting hash.

**Comment by nventuro** [comment]
I did a quick test on remix, and, it doesn't. Looks like this is the issue tracking this feature: https://github.com/ethereum/solidity/issues/4024

**Comment by frangio** [comment]
We should replace it for the value in the source code then IMO. LIke we did for interface hashes. 

https://github.com/OpenZeppelin/openzeppelin-solidity/blob/86f214b7a3cb6b938463a3509ccd273ad7a04d44/contracts/token/ERC721/ERC721.sol#L19-L21

**Comment by axic** [comment]
This feature has been added and will be released probably in 0.6.12. Looking forward to have it used in zeppelin :wink:

**Comment by frangio** [comment]
@axic That's great news! Thanks for letting us know.
