### ISSUE TITLE
Deployment of ERC777 with Truffle Migrations doesn't work.

### ISSUE THREAD

**Issue by crazyrabbitLTC** [OpenZeppelin/openzeppelin-solidity#1743]
A requirement to deploy ERC777 requires a local instance of ERC1820 to be deployed, which does not exist on a local Test network. 

There are several issues here: 
1: ERC777 fails to deploy, but does not communicate to the user the reason why it failed. No revert/require statements fail with a description why. It is not communicated with the user that the lack of an ERC1820 contract is the problem. 

2: Deployment of ERC1820 via the `OpenZeppelin-test-helpers` in migrations does not work as Truffle Migrations does not seem to be able to properly require in `openzeppelin-test-helpers`

Because of this, it is unclear of the best way to deploy ERC777 using truffle migrations. Perhaps an external 'setup script' needs to be created. 

**💻 Environment**
Mac OSX Mojave, zsh terminal

OpenZeppelin:  openzeppelin-solidity@next (Next at time of this issue filing)
Truffle v5.0.13

**📝 Details**

Solidity code: 

```
pragma solidity >=0.4.21 <0.6.0;

import "openzeppelin-solidity/contracts/token/ERC777/ERC777.sol";

contract My777Token is ERC777 {
    constructor(string memory name, string memory symbol, address[] memory defaultOperators)
    ERC777(name, symbol, defaultOperators) public {
    }

}

```

Migrations code: 
```

const My777Token = artifacts.require("My777Token");
const { singletons } = require('openzeppelin-test-helpers');


const name = "LuckyToken";
const symbol = "LT";
const defaultOperators = [];

module.exports = async function(deployer, accounts) {
    let accounts = await web3.eth.getAccounts();
    const erc1820 = await singletons.ERC1820Registry(accounts[0]);
    
  deployer.deploy(My777Token, name, symbol, defaultOperators);
};

```
**🔢 Code to reproduce bug**

The example above will not deploy an ERC777 token, it is unclear how to deploy a ERC777 in a standard method using Truffle Migrations.

**Comment by frangio** [comment]
Thank you for reporting this @crazyrabbitLTC! We definitely want to get this to work more like an out of the box experience, so we're looking into it.

I think that using the deployer in openzeppelin-test-helpers should be the recommended way, but it's not working due to https://github.com/OpenZeppelin/openzeppelin-test-helpers/issues/35.

**Comment by frangio** [comment]
@crazyrabbitLTC There's a fix for this in https://github.com/OpenZeppelin/openzeppelin-test-helpers/pull/38.

You can try it with `npm install frangio/openzeppelin-test-helpers#reduce-dependencies`. (Sorry for the weird branch name. :sweat_smile:) You will then be able to `require('openzeppelin-test-helpers/inject-web3')(web3)`.

**Comment by crazyrabbitLTC** [comment]
Hi @frangio , for: 

npm install frangio/openzeppelin-test-helpers#reduce-dependencies

is the "#reduce-dependencies" intentional? I'm getting this error: 

`npm ERR! code 1
npm ERR! Command failed: /usr/bin/git checkout reduce-dependencies
npm ERR! error: pathspec 'reduce-dependencies' did not match any file(s) known to git
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dennisonzeppelin/.npm/_logs/2019-05-11T02_18_15_736Z-debug.log`

**Comment by frangio** [comment]
Yes it was intentional but we just merged that. I deleted the PR and forgot to update this comment. Sorry! Updated the comment above now.

**Comment by frangio** [comment]
@crazyrabbitLTC I think you have a bug in your migrations code though.

The function you export in the migration receives three arguments and `accounts` is the third one. At least in `truffle@5.0.13`.
