### ISSUE TITLE
ERC20:Should not approve to self

### ISSUE THREAD

**Issue by prashantprabhakar** [OpenZeppelin/openzeppelin-solidity#1757]
I don't see any need why one would want to `approve` his own address. So `approve` function should have additional check of :

`require(spender != msg.sender, "ERC20: cannot approve to self");`

**Comment by Skyge** [comment]
Emmm, I am not sure whether there is a necessary to do this, but I think it is OK.

**Comment by frangio** [comment]
Thanks for the suggestion @prashantprabhakar!

However, I don't agree that we should do this. Some users may want to use this mechanism and there's no reason to disallow it. It's not something that would result in an error in any way.

**Comment by prashantprabhakar** [comment]
@frangio I do agree this does not result in an error. But if called accidentally wastes gas. I  don't find any reasons why anyone will want to approve to himself. `approve` and `transferFrom` were not intended to handle this. 
So this is more of a **precaution**  an enforces intend of `approve` and `transferFrom`
