### ISSUE TITLE
SafeMath does not protect from negation of smallest integer

### ISSUE THREAD

**Issue by guylando** [OpenZeppelin/openzeppelin-solidity#1758]
Explanation of the problem can be found here: https://consensys.github.io/smart-contract-best-practices/recommendations/#beware-of-negation-of-the-most-negative-signed-integer

The problem is that the name "SafeMath" makes people think that math operations are safe when they are not. Negation includes multiplication and division by -1 but also if X is smallest negative then if you take (X/2) and multiple by (-2) you get the same problem. So the solution is not as simple as checking just for -1 multiplication/division and 0-X. 
Probably the solution should be to check for some invariant in the end of the calculation.

**Comment by guylando** [comment]
I see SafeMath only works with unsigned integers so this is irrelevant, closing

**Comment by guylando** [comment]
Probably there should be a warning "pay attention that safemath only works with uint256, so be careful when working with other types without safemath" and also I wonder why not to implement SafeMath for other types

**Comment by frangio** [comment]
I don't see the need for such a warning. The compiler will not allow using `SafeMath` with signed integers.

However, do note that we have a [`SignedSafeMath`](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/drafts/SignedSafeMath.sol) draft library. It checks for the condition you reported in this issue.

https://github.com/OpenZeppelin/openzeppelin-solidity/blob/2ccc12b328e6d5d1d3faa5b99bec8d1de8b92fea/contracts/drafts/SignedSafeMath.sol#L21

**Comment by guylando** [comment]
@frangio The warning goal was not to prevent the use of SafeMath with signed integers, the goal is to make people aware that they need to utilize other security measures when working with signed integers.

Regarding the condition in SignedSafeMath:
1. `b = -1, a=INT256_MIN` in "mul" bypasses the checks
2. `b = -2^N, a=-2^(255-N) `in "mul" for any `N>0` (only `N=0` is checked at the moment). same for `a = -2^N, b=-2^(255-N)`. Note that the current check in "mul" of the invariant after calculation does not save from the problem because the calculation inside the require will trigger the problem resulting in "true".

Possibly there are more cases.

I believe the better solution is to check for some invariant in the end of the calculation like done in "sub". Although the invariant in "mul" does not protect from this so need to be careful when choosing the invariant.

**Comment by frangio** [comment]
@guylando `SignedSafeMath` correctly catches all of those cases and reverts. The first case is even covered by the test suite. Please try this out yourself.

**Comment by guylando** [comment]
I see, tried it now. From reading the "mul" code it seemed the first require was the implemented defense however actually the first require only protects from division by -1 in the second require (and not the multiplication itself) and in all other cases the second require catches the problem. Code comments could make it easier to read the code and understand this. Also wouldn't it be better for debugging purposes not to pass the same message in two different "require" statements in the same function/flow? I had to change the require messages to understand which one was failing (and that still didnt help because of this problem: https://github.com/OpenZeppelin/openzeppelin-test-helpers/issues/44)

**Comment by guylando** [comment]
By the way used this test case for (2):
```
it('reverts when negatives multiplication results in -(minimum integer)', async function () {
      const N = 5;
      const a = new BN('2').pow(new BN('' + (255 - N))).mul(new BN('-1'));
      const b = new BN('2').pow(new BN('' + N)).mul(new BN('-1'));

      await shouldFail.reverting.withMessage(this.safeMath.mul(a, b), 'SignedSafeMath: multiplication overflow');
    });
```

**Comment by nventuro** [comment]
@guylando I tried that same test locally and it passes. Could you share an example of a failing test? I was not able to reproduce this.

Regarding the error message, they are the same because the internal details of _why_ the overflow occurred are not relevant to the user: all that's important is that the multiplication overflowed. The fact that we have two separate `require` statements is accidental.

**Comment by guylando** [comment]
I am sorry for the misunderstanding, I provided the test case code just in case you would want to add to your safemath test cases, it indeed passes correctly and you were right. That is why I said in https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1758#issuecomment-493740904 that the code without comments is a little confusing about which of the require statements was there to protect from this scenario.
