### ISSUE TITLE
SafeMath does not provide detection of losing precision by division

### ISSUE THREAD

**Issue by guylando** [OpenZeppelin/openzeppelin-solidity#1759]
The name SafeMath can make developers use it without paying attention of problem of division losing precision https://consensys.github.io/smart-contract-best-practices/recommendations/#beware-rounding-with-integer-division
Maybe add a function "safediv" which also checks that precision wasn't lost and add in documentation of "div" that precision can be lost.

**Comment by Skyge** [comment]
As long as you do a division, there is a possible to loss precision. I think adding a `@notice` message is good, it can remind people of this point.

**Comment by nventuro** [comment]
This loss of precision is intrinsically associated with integer division, and would be surprised to learn that someone understood the 'safe' part as being related to it. Besides, `SafeMath`'s documentation makes it very clear that it has to do with overflow protection.

We are, however, considering adding fixed-point support! Please join the discussion in the forum: https://forum.zeppelin.solutions/t/fixed-point-arithmetic-support/356
