### ISSUE TITLE
there is no revert message in source code

### ISSUE THREAD

**Issue by startgeek** [OpenZeppelin/openzeppelin-solidity#1762]
I use test's in github for my refrence and in those test's all of the reverts has message that will fetched via shouldFail.reverting.withMessage(somePromise, 'and heres why I reverted');
I observed that It dosen't return any messages then I inspected the source code and I realized non of the Require() function has message so did I missing some thing here? whats going on? 

💻 Environment: MacOS latest

version of OpenZeppelin :2.2.0

**Comment by frangio** [comment]
The revert messages were added recently in https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1704. 

They are in the latest release candidate which you can install via `npm install openzeppelin-solidity@next`.
