### ISSUE TITLE
SafeERC20 allows GasToken minting/gas draining

### ISSUE THREAD

**Issue by guylando** [OpenZeppelin/openzeppelin-solidity#1767]
Problem: SafeERC20 calls callOptionalReturn which uses .call(..) without .gas(..) which passes all the gas to the call and allows called contract to drain all used gas and perform GasToken minting https://medium.com/level-k/public-disclosure-malicious-gastoken-minting-236b2f8ace38

Recommendation: allow the caller of SafeERC20 to limit the gas used by adding additional parameter to the functions. This parameter will also make those who use SafeERC20 aware of the possible gas drain.

**Comment by nventuro** [comment]
Hello @guylando!

How is this different from any regular call to a contract, though? 63/64ths of the available gas are always forwarded on CALLs, so I don't see what's special about `SafeERC20`.

**Comment by guylando** [comment]
I see, the recommendation I wrote is redundant in light of the solidity ability to limit the gas when calling SafeERC20 using .gas(..) as explained here https://solidity.readthedocs.io/en/v0.5.8/control-structures.html?highlight=gas#external-function-calls
