### ISSUE TITLE
Address.toPayable()

### ISSUE THREAD

**Issue by nventuro** [OpenZeppelin/openzeppelin-solidity#1771]
**🧐 Motivation**
As seen in [this StackOverflow question](https://stackoverflow.com/questions/56154982/call-to-super-owner-transfermsg-value-giving-errors), there's no easy (reasonable) way to convert an `address` into an `address payable`. This was confirmed by the Solidity team on gitter. We should provide a simple wrapper for this ugly conversion.

**📝 Details**
This would simply be a new `internal pure` function in `Address`, that takes an `address` and returns `address payable`. In order to do the conversion, we must first cast the address type into `uint160`.

**Comment by Skyge** [comment]
Yeah, in Solidity 0.5, this is one of the breaking changes, but for some developers including myself, we just use like this `address(uint160(_owner))` to make it become `address payable`, so it is really a good proposal to provide a simple wrapper.

**Comment by pokcup** [comment]
> ใช่ใน Solidity 0.5 นี่เป็นหนึ่งในการเปลี่ยนแปลงที่ไม่หยุดยั้ง แต่สำหรับนักพัฒนาบางคนรวมถึงตัวฉันเองเราแค่ใช้สิ่งนี้`address(uint160(_owner))`เพื่อทำให้มันกลายเป็น`address payable`จริงดังนั้นจึงเป็นข้อเสนอที่ดีที่จะให้เสื้อคลุมเรียบง่าย

**Comment by Skyge** [comment]
@pokcup It is really hard for me to understand your words, could you please use the English?

**Comment by nventuro** [comment]
@pokcup ยินดีต้อนรับ! Please write in English when communicating over this medium :)

**Comment by RCYP** [comment]
Would the solution be a function like this within Address.sol ?
`    
    //@dev Converts an address to address payable.
    function toPayable(address account) internal pure returns (address payable) {
        return address(uint160(account));
    }
`

**Comment by frangio** [comment]
@RCYP Yes, though @Skyge is already working on this, see https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1773.
