### ISSUE TITLE
Test reverts for the wrong reason

### ISSUE THREAD

**Issue by NoahMarconi** [OpenZeppelin/openzeppelin-solidity#1774]
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/test/token/ERC20/ERC20.behavior.js#L111:L118

This test reverts for the same reason the previous describe block reverts.

**Comment by NoahMarconi** [comment]
Likewise for this one: https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/test/token/ERC20/ERC20.behavior.js#L139:L148

It reverts because they're not approved to transferFrom and not because the transferFrom is from the ZERO_ADDRESS

**Comment by nventuro** [comment]
Hello @NoahMarconi, thank you for contributing!

I'm not sure what the issue you're pointing out is, both tests fail for the same underlying reason, the outer describe block:

`'when the spender does not have enough approved balance'`

**Comment by NoahMarconi** [comment]
sorry about that, the outer and inner describe blocks tripped me up. Makes sense
