### ISSUE TITLE
Use mutator methods internally for Eternal Storage

### ISSUE THREAD

**Issue by daniellehrner** [OpenZeppelin/openzeppelin-solidity#1775]
**🧐 Motivation**
Currently all variables in the smart contracts are directly accessed. While this is the most straight-forward approach and keeps the code simple, it prevents using alternative storage approaches like [eternal storage](https://fravoll.github.io/solidity-patterns/eternal_storage.html).

**📝 Details**
There are different approaches for smart contract upgradability. One of them is the mentioned eternal storage pattern, which stores the data of a contract in another contract, which allows the upgrade of the "logic smart contract" without loosing the data of its previous version.
Currently openzeppelin-solidity does not allow this approach, because there is no way to change the underlying storage of the contracts. By using `internal` getters, setters and deleters a contract can extend the existing one and overwrite these methods to use an alternative storage approach.
As this would be a purely internal change, it should not introduce any breaking changes. I understand that the effort for it would be quite high, but I would be willing to offer my help there.

**Comment by nventuro** [comment]
Hello @daniellehrner, thank you bringing this up!

We've actually considered supporting these patterns for the aforementioned reasons, but sadly never got around to.

Have you performed any gas measurements comparing accessing a field directly, versus calling a `private` function that accesses the storage slot via a hash? I'd expect the cost of the SLOAD/SSTORE to dwarf the rest of the operation, but I've been wrong before :stuck_out_tongue:

**Comment by frangio** [comment]
The reason our state variables are private is to provide stronger guarantees with respect to consistency of the state, by encapsulating all the changes to those variables in the contract that defines them. Providing these internal setters would be counter to that purpose, it breaks encapsulation.

If someone is interested in the modifying our contracts to use Eternal Storage or something similar, I would encourage them to clone the contracts and modify the code, because we can't guarantee that that will be safe to do.

**Comment by nventuro** [comment]
Perhaps I misunderstood @daniellehrner's intent (there word `internal` has been used somewhat loosely), but from what I gathered, the idea behind this request is not to expose the storage slots, but to have all internal variables use fixed storage slots, bypassing the compiler's slot allocation algorithm (therefore achieving upgrade safety, at least regarding storage layout).

**Comment by frangio** [comment]
Yeah I think you misunderstood. :slightly_smiling_face: As mentioned in the issue the request is for the following specifically:

>internal getters, setters and deleters a contract can extend the existing one and overwrite these methods to use an alternative storage approach

We won't do this due to what I mentioned above:

>Providing these internal setters would be counter to that purpose, it breaks encapsulation.

Thanks for the suggestion regardless @daniellehrner!

**Comment by daniellehrner** [comment]
@nventuro @frangio Thanks for taking the time to explain, why it does not make sense to you.
