### ISSUE TITLE
IncreasingPriceCrowdsale throws 'rate' rpc-json error when interacting with contract

### ISSUE THREAD

**Issue by benitech** [OpenZeppelin/openzeppelin-solidity#1782]
-getCurrentRate' works as intended but 'rate' is still available to be viewed in deployed contract via Crowdsale.sol

Therefore, 'rate' throws rpc-json error when called.

'rate' should not be available to be viewed when using IncreasingPriceCrowdsale.

**Comment by nventuro** [comment]
Sadly, the Solidity language does not let us remove a function from a contract's interface, so the best we can do is revert when `rate` is called on that particular crowdsale. The alternative would be to manually expose `rate` in all child crowdsales but that one, but I fear that would be too cumbersome and not worth the effort.
