### ISSUE TITLE
PULL_REQUEST_TEMPLATE.md is empty

### ISSUE THREAD

**Issue by alanarvelo** [OpenZeppelin/openzeppelin-solidity#1800]
Under the .github folder, the PULL_REQUEST_TEMPLATE.md only has "# Fixes" written on it. Was this never written? or was it deleted? 

I am looking for what version/configuration of JS and solc linters to set up on my environment to start contributing. 

The PULL_REQUEST_TEMPLATE.md file is mentioned (under _typical workflow_ , step 4) but not linked on the CONTRIBUTING.md file. 

Thanks

**Comment by nventuro** [comment]
Oh, interesting, thanks! We should add that information to the template. It may have been deleted at some point, we used to have a larger one (that was not very useful and was therefore shortened).

Regarding setup, having Node ^v8.0, and running both `npm run lint` and `npm test` should suffice. `npm install` will install all required dependencies to run both of these commands: no other tools are needed.

**Comment by alanarvelo** [comment]
Awesome. Thanks for the clarification @nventuro.

**Comment by frangio** [comment]
Oh, actually the file does have a lot more content, but it's written in HTML comment tags, so it doesn't show up in the GitHub preview. It definitely does show up in the Pull Request text field, though!

https://raw.githubusercontent.com/OpenZeppelin/openzeppelin-solidity/master/.github/PULL_REQUEST_TEMPLATE.md
