### ISSUE TITLE
ERC777 README.md broken link.

### ISSUE THREAD

**Issue by HM999** [OpenZeppelin/openzeppelin-solidity#1809]
Click on the links to find the broken link.
https://github.com/OpenZeppelin/openzeppelin-solidity/tree/master/contracts/token/ERC777

**Comment by HM999** [comment]
also here: https://github.com/OpenZeppelin/openzeppelin-solidity/tree/master/contracts/token/ERC20

**Comment by frangio** [comment]
Thank you @HM999! Unfortunately the links are broken on GitHub but they do work on the published docs at https://docs.openzeppelin.org.
