### ISSUE TITLE
fix value typo in ERC721.sol

### ISSUE THREAD

**Issue by kwanlae** [OpenZeppelin/openzeppelin-solidity#1814]
There is mistypo in ERC721.sol comment

**💻 Environment**

**📝 Details**

In "contracts/token/ERC721/ERC721.sol", there is "bytes4(keccak256('isApprovedForAll(address,address)')) == 0xe985e9c" in comments.

But the result is 0xe985e9c5 not 0xe985e9c, just mustypo I think.

**🔢 Code to reproduce bug**

**Comment by frangio** [comment]
Thanks for reporting @kwanlae!
