### ISSUE TITLE
Cancellable PullPayment helper

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#196]
It would be nice to have a version of `PullPayment` that allows for cancelling an issued payment. I would do it as a subcontract of `PullPayment`.

**Comment by DavidKnott** [comment]
@maraoz I'm getting started on this issue!

**Comment by maraoz** [comment]
Great, thanks!

**Comment by ataddei** [comment]
Hi, I am training myself and would like to play around with this easy issue. I understand the payer is the one in charge of cancelling the payment, right?

**Comment by maraoz** [comment]
Yes.

Alfredo Taddei <notifications@github.com> schrieb am Di., 6. Juni 2017,
09:31:

**Comment by pmosse** [comment]
Hey! I am working on this. I am thinking of something simple as the following:

`pragma solidity ^0.4.23;

import "./PullPayment.sol";

/**
 * @title CancellablePullPayment
 * @dev PullPayment contract supporting cancelling an issued payment.
 */
contract CancellablePullPayment is PullPayment {

  /**
  * @dev Called by the payer to cancel the stored amount for an address.
  * @param _payee The destination address of the funds.
  */
  function cancelPayment(address _payee) internal {
    uint256 payment = payments[_payee];

    require(payment != 0);

    payments[_payee] = 0;
    totalPayments = totalPayments.sub(payment);
  }
}
`
We can make it more complex in case we want to:

- Be able to cancel partial amounts of money.
- Be able to cancel partial payments. For example if a payment of 100 was set for an address and then a payment of 200 was set for the same address, we could allow cancellations of one or both of those payments.

I am not sure if those scenarios are useful. What are your thoughts?

**Comment by frangio** [comment]
Closing as explained in #955:
> After some discussion we're pretty sure that this feature shouldn't be a part of OpenZeppelin. We're not comfortable with the possibility of cancelling payments.
