### ISSUE TITLE
PullPayment version that checks balances

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#197]
`asyncSend` allows more balance to be queued up for sending than the contract holds. I don't see any way to prevent this, given the inheriting contract can manage its balance as it wants. Even if we added a uint counter on the total debt and failed when it exceeds this.balance, the balance can go down by other means.
Still, it would be nice to have a version of `PullPayment` with balance available guards to prevent most cases of misuse. 
I would do this as a subcontract of `PullPayment`.

**Comment by nventuro** [comment]
Closing since this was fixed by #1014.
