### ISSUE TITLE
Implement mutex-guarded payment helper contract

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#2]
See "Remediation Approach 2: Mutexes" section here:
http://vessenes.com/more-ethereum-attacks-race-to-empty-is-the-real-deal/

**Comment by nventuro** [comment]
Our current `ReentrancyGuard` can be used to address these issues, and while more generic and with some limitations (guarded functions cannot call one another), I prefer it over a solution as specific as the proposed one.

**Comment by frangio** [comment]
This is also addressed by using `PullPayment`.
