### ISSUE TITLE
Timed/Periodic payments helpers

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#23]
Contracts want to send periodic or timed payments. E.g: "send x ether to this address every week for 5 weeks". Or "Send x ether to this address in 10 days".

We should write a contract that does that securely

**Comment by ajsantander** [comment]
@maraoz is this still valid considering what is planned for the zOS scheduler?

**Comment by Shrugs** [comment]
What's perhaps best here is an easy "asyncSend" implementation that follows the "vesting pattern" from vesting contracts; allow users to withdraw tokens at an easily configured schedule.

So for "every week" the function would look something like

```
function withdraw() external {
  var hasWithdrawn = withdrawnAmounts[msg.sender];
  // send msg.sender `availableAt(now) - hasWithdrawn` ether

}

function availableAt(uint256 timestamp) internal pure {
  // very pseudo code
   return (timestamp - startTime) / (1 week) * rate;
}
```

**Comment by nventuro** [comment]
Such a feature would be easily implemented via `ConditionalEscrow`s, where only amounts smaller than the currently vested value can be withdrawn. Regarding having someone else execute the transactions, metatransactions are probably the way forward.

Closing to reduce issue clutter.
