### ISSUE TITLE
Write an implementation of an ether timelock

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-solidity#239]

**Comment by frangio** [comment]
See [`TokenTimelock`](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/TokenTimelock.sol) for the same functionality implemented for tokens.

We could evolve that same contract into a multipurpose `Timelock`, such that ether as well as _any_ token can be sent to the contract's address and later released.

**Comment by SylTi** [comment]
I think it could also be interesting to have a simple base contract "lock", that could be inherited by different types of locks in the future. Example: MultiSigLock, OracleLock, VotingLock etc..

**Comment by nventuro** [comment]
This is very much in line with the generic escrow (that supports both ether and tokens) that we want to implement. Closing this to continue the discussion in https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1099.
