### ISSUE TITLE
Provide integration with a secure Random Number Generator

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#297]
Using `block.blockhash(block.number)` as seed?

**Comment by federicobond** [comment]
`block.blockhash` with `block.number` as the argument returns 0x0, because the hash of the current block cannot be known at the time the transaction executes.

There are some attempted solutions like [randao](https://github.com/randao/randao) but none of them has been completely satisfactory as of today.

**Comment by maraoz** [comment]
@federicobond good point. well, this issue is about researching how to do secure RNG for smart contracts

**Comment by rstormsf** [comment]
https://ethereum.stackexchange.com/questions/419/when-can-blockhash-be-safely-used-for-a-random-number-when-would-it-be-unsafe

**Comment by frangio** [comment]
There is an [On-chain Random Number Generation](https://github.com/ethereum/research/wiki/Problems#21-on-chain-random-number-generation-63) entry in the ethereum/research problem list.

**Comment by dogpatchmedia** [comment]
What's the latest on this?

**Comment by adklempner** [comment]
@dogpatchmedia there's a lot of research being done in the Ethereum community to provide a randomness beacon that is un-predictable, un-biasable, and un-stoppable. The top candidate is Verifiable Delay Functions, which you can read more about here: [VDF reading list](https://notes.ethereum.org/52JZtwErThe9KmN6TNd1lg)

**Comment by frangio** [comment]
Very interesting @adklempner! Thanks for that pointer.

As this is an unsolved research problem I'm going to mark the issue `on hold`. It also seems to me like a secure randomnless solution will not be a simple smart contract that we can include in OpenZeppelin, but more of a protocol/system that will be instanced once for all contracts to use. So I'm going to slightly change the name.

**Comment by nventuro** [comment]
Integration with some sort of protocol does seem like the way forward, though I still haven't seen a great one.

Closing to reduce issue clutter.

**Comment by chiro-hiro** [comment]
@nventuro I wrote my smart contract with 26 bytes of OPCODE to provide a cheap and secure PRNG. Please have a look.
https://github.com/chiro-hiro/thedivine
