### ISSUE TITLE
External authorization checks/helpers

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#30]
Idea based on FirstBlood's token: https://github.com/Firstbloodio/token/blob/2ee2fccb4d111bee461de569bf792619cab40650/smart_contract/FirstBloodToken.sol#L228

Provide a mechanism for contracts to validate external auth mechanisms such as verifying an EC signature before proceeding with the function.

**Comment by elopio** [comment]
We have a very generic [SignatureBouncer](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.9.0/contracts/access/SignatureBouncer.sol) that will revert if the call doesn't comes signed from one of the approved bouncers.

I think that if we make the bouncer a contract that verifies an EC signature, and then forwards the call adding their signature, this solves the example that Manu is giving. And many other things can be build on top of that. @shrugs can you please confirm if we can close this issue or if there's something missing?

**Comment by shrugs** [comment]
Yup, SignatureBouncer solves this issue (except the hash is also of the contract address, which stops someone from potentially using the same signature for multiple contracts managed by a single signer.

I'd say this is solved!
