### ISSUE TITLE
Provide verified library contract addresses to the public and provide interface files for integration.

### ISSUE THREAD

**Issue by MicahZoltu** [OpenZeppelin/openzeppelin-solidity#336]
Contracts like ECRecover are very useful but don't need to be re-uploaded and re-verified by everyone.  Instead it would be nice if OpenZeppelin uploaded these contracts to the chain, verified them with all major block explorers, registered them in the various method registries, and made the addresses of these contracts generally available.

To facilitate integration, it would be nice if these contracts also had a "header file" available that was small and well documented (but without source code) that could be included in projects that will be using the contract.  These header files would, presumably, also come with the on-chain address of the contract baked in somehow (perhaps by network ID?)

I don't know if it is possible, but would be nice if there was also a per-network lookup mechanism so I could do something like `ECRecover.lookup(network-id)`.  I believe there has been talk about getting something like network-id added to the EVM but I don't know what happened to that, so this may not be possible.

**Comment by elopio** [comment]
zeppelinos will let you access standard libraries already deployed to the blockchain. This is already implemented for the mvp, but I'm leaving this open until we have a nice link which documents it.

**Comment by nventuro** [comment]
Most of our library contracts are still composed of `internal` functions as opposed to `public`, and while it _would_ save storage costs to only deploy these once, we would then impose a `CALL` overhead on all users, which doesn't seem to be the right trade-off for such small utilities.

**Comment by WyseNynja** [comment]
That's a great point @nventuro. This should be documented somewhere. I started writing some truffle migrations and just assumed that linking would be better until I saw this issue.
