### ISSUE TITLE
Duplicated crowdsale end logic

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-solidity#352]
As mentioned by @jakub-wojciechowski in #310 (items 4 and 5), there is somewhat duplicate logic in `Crowdsale` and in `CappedCrowdsale` in `validPurchase` and `hasEnded`.

We should see what is the best way to consolidate the logic in one place.

**Comment by elopio** [comment]
The [crowdsale contracts were completely rewritten](https://blog.zeppelin.solutions/on-crowdsales-and-multiple-inheritance-af90c694e35f), and this is no longer valid.
