### ISSUE TITLE
Contract death strategies

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#4]
See NaturalDeath section in http://vessenes.com/we-need-some-best-practices-for-smart-contracts/

**Comment by akshithg** [comment]
Related: [Setting Standards for Altering and Undoing Smart Contracts](http://www.arijuels.com/wp-content/uploads/2016/06/Setting-Standards-for-Altering-and-Undoing-Smart-Contracts.docx)

**Comment by elopio** [comment]
We now have contracts that help with closing, finishing or destructing:
* [https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.9.0/contracts/lifecycle/Destructible.sol](Destructible]
* [https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.9.0/contracts/lifecycle/TokenDestructible.sol](TokenDestructible)
* [https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.9.0/contracts/crowdsale/distribution/FinalizableCrowdsale.sol](FinalizableCrowdsale)
* [https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.9.0/contracts/crowdsale/validation/CappedCrowdsale.sol](CappedCrowdsale)
* [https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.9.0/contracts/crowdsale/validation/TimedCrowdsale.sol](TimedCrowdsale)

There are probably more strategies to explore, but I think we can close this issue and open new individual ones for new strategies as they appear.
