### ISSUE TITLE
Create a subcontract of StandardToken that rejects holding funds

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#442]
A subcontract of StandardToken.sol which also implements HasNoEther and HasNoTokens.
This would prevent token contracts from holding unclaimable ETH or token balances, which happens a lot by user error. 

Idea suggested by @SergioDemianLerner

**Comment by SylTi** [comment]
What about also adding HasNoContracts?

**Comment by frangio** [comment]
@SylTi What do you mean by that?

**Comment by SylTi** [comment]
@frangio In my opinion, this contract is here to help users recover from mistakes.  The more mistake it can recover from, the better? 
Take a look at the linked commit for an example.

**Comment by AugustoL** [comment]
@SylTi would you mind having this contract only as an example?

**Comment by nventuro** [comment]
We got rid of `HasNoEther` in https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1254, read more on that issue as to the reasons behind the decision.
