### ISSUE TITLE
Add auction contract

### ISSUE THREAD

**Issue by jordanschalm** [OpenZeppelin/openzeppelin-solidity#458]
Auctioning non-fungible assets is a common requirement for smart contracts (an example even appears in the [Solidity docs](http://solidity.readthedocs.io/en/latest/solidity-by-example.html#blind-auction). It would be great if OpenZeppelin included a standard auction contract for use with either ERC20 tokens or Ether.

**Comment by SylTi** [comment]
If you mean auctions with multiple bidders like a multi-unit auction, the gas limit becomes a problem very fast without using complex data structures.

For the dutch auction, you have https://github.com/maurelian/dutch-auction/blob/master/contracts/DutchAuction.sol (it seems to be the gnosis one. I'm not sure why, but I can't find it in the original repo)

**Comment by JGcarv** [comment]
I actually have a tested dutch auction contract I developed for USCC. I could submit a PR ilater today, If you are interesed

**Comment by Mazecreator** [comment]
@JGcarv Did you submit a PR for the Dutch Auction?

**Comment by JLansey** [comment]
Has anyone looked at auctionhouse as a solution -  and shown that indeed gas-limit becomes a problem. I'm curious to learn more about auction types etc.
http://auctionhouse.dappbench.com/

**Comment by elopio** [comment]
Here is the dutch auction code by @JGcarv: https://github.com/JGcarv/SolidityJourney/blob/master/2%20Dutch%20Auction%20Crowdsale/DutchAuction.sol
It doesn't have a license though, so it's not clear if we can use it or not.

**Comment by JGcarv** [comment]
Hello Everyone.

Sorry about not making a PR, I ended up forgetting it.

There's no problem in using my code, @elopio.

Feel free to make a PR.

If you need anything else, just let me know.

**Comment by dougiebuckets** [comment]
@JGcarv, @elopio - Very cool! I've been playing around w/ the contract and it seems to work well. If it's OK w/ you guys, I can go ahead and update it to use SafeERC20, address unit testing, and add additional documentation in compliance w/ NatSpec.

A couple of quick question:

**Question 1:** I  don't understand why the address that makes the bid is the address receiving the ETH from the bid? Shouldn't the address that corresponds to "wallet" receive the ETH? For instance, why is accounts[1] that's making the bid receiving the ETH?

`auction.bid(web3.eth.accounts[1], {value: web3.toWei(5, "ether")})`

`web3.eth.getBalance(web3.eth.accounts[1])`
`BigNumber { s: 1, e: 20, c: [ 1049999, 99999999999990 ] }`

**Question 2:** The Stage of the auction appears to move to AuctionEnded after only one bid even if finalizeAuction() or claimTokens() are never called. Is there a way I can test w/ web3 in truffle console to see the current Stage of the auction?

Thanks in advance for your feedback.

**Comment by JGcarv** [comment]
Sorry for the late response.

The contract is supposed do accept multiple bids, until the hard cap is reached. I don't see why it would move to a closed state before that.

The `decreaseRate` is simply how much wei the price is diminished each second. There are other functions to calculate the price though. Gnosis did it somewhat differently, if I recall correctly.

**Comment by dougiebuckets** [comment]
@JGcarv We went ahead and created a dutch auction contract for NFTs: https://github.com/OpenZeppelin/openzeppelin-solidity/pull/989

There's definitely value in the auction contract you've implemented for ERC20s it's just that we had trouble understanding how your code was working and how the auction was operating.

**Comment by nventuro** [comment]
Considering progress hasn't advanced on this front, users of auctions may want to take a look at Gnosis's DutchX: https://blog.gnosis.pm/new-dutchx-smart-contracts-are-now-live-665d83f31930

Closing due to staleness.

**Comment by aliekber1976** [comment]
Hey everyone , I am creating NFT marketplace and I finished with minting and listing item, I deployed my contract and works fine until now.I would like to also add auction to marketplace but I don't know how I can start it , should I chance my whole market contract or just do I need to add the auction function ? Thank you so much

**Comment by frangio** [comment]
@aliekber1976 Please ask in the [OpenZeppelin Forum](https://forum.openzeppelin.com/).
