### ISSUE TITLE
FinalizableCrowdsale should just be Finalizable (and not inherit from Crowdsale)

### ISSUE THREAD

**Issue by NoahMarconi** [OpenZeppelin/openzeppelin-solidity#479]
Inheriting from `Crowdsale` means `Finalizable` is not generic or reusable.

My use case is needing a `Crowdsale` that doesn't use a `MintableToken`, but instead uses a `StandardToken`. Since use of a `MintableToken` is hard coded into `Crowdsale` I can't use `Crowdsale` for my use case.

That alone is not such a big deal, but I also can't use anything the inherits from `Crowdsale`; doing so would require an excessive amount of overrides. 

If `FinalizableCrowdsale` was simply `Finalizable` (same contract without the dependency on `Crowdsale`), I could do my custom crowdsale contract without copying and pasting the finalizable logic.

**Comment by canufeel** [comment]
+1 Trying to use my own token with `RefundableCrowdsale` results in massive copy-pasting. Would love to have those:
`function buyTokens(address beneficiary) public payable;`
`function createTokenContract() internal;`
in abstract form on this contract.

**Comment by ajsantander** [comment]
I don't really see the point of having a crowdsale with a non-mintable token. Could you please elaborate?

Regarding extracting the finalizable functionality out of FinalizableCrowdsale into its own Finalizable contract, would you care to produce a PR referencing this issue?

**Comment by NoahMarconi** [comment]
Definitely! I'll put a PR together.

The motivation is for sales where a fixed supply is intended. Having the option of transferring tokens instead of transferring ownership feels like a better pattern.

**Comment by ajsantander** [comment]
Great, thanks @NoahMarconi. When you do your PR, please reference this issue by referencing the issue number in the branch name or in the PR body, eg:
branch name: `fix-for-#479`
PR body: `fixes #479`

**Comment by elopio** [comment]
With the recent [rewrite of the crowdsale contracts](https://blog.zeppelin.solutions/on-crowdsales-and-multiple-inheritance-af90c694e35f), now you can use other tokens. I think this should solve your problems and give you a few nice extra features. I'm closing this, but it would be great to hear from you, what do you think of the new crowdsale architecture?
