### ISSUE TITLE
Tests to check if child classes don't modify superclass-behaviour in unwanted ways

### ISSUE THREAD

**Issue by Qqwy** [OpenZeppelin/openzeppelin-solidity#501]
OpenZeppelin has a wonderful, modular approach where many contracts build upon simpler ones.

However, because of the semi-object-oriented way Solidity works, it is possible to, on purpose or by accident, modify behavior that one of the ancestor contracts provides.

For instance, I would expect any contracts that inherit from `Ownable`, to check if `transferOwnership` [indeed transfers ownership](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/test/Ownable.js#L18).

I believe these tests are important because they could prevent accidental alterations to behaviour specified by an ancestor contract that would otherwise probably go unnoticed until the Smart Contract is deployed and in use.

**Comment by Ivshti** [comment]
I agree, it's something that even audits overlook.

Also, would be nice if there was some automated way to map the relationships and overrides, potentially warn if something is overridden from classes like `Ownable`

**Comment by maraoz** [comment]
Love this idea!

**Comment by ajsantander** [comment]
@Qqwy could you provide an example of such a test?

**Comment by nventuro** [comment]
Our behavior test files can help in this regard (e.g. you can check that your derived contract behaves like an `Ownable` contract), but it is very difficult and sometimes impossible to make them so generic as to be useful in this regard. The solution should IMO come from the language itself, preventing the developer from overriding certain functions.

**Comment by nventuro** [comment]
This is starting to happen in Solidity: see https://github.com/ethereum/solidity/issues/5424.

Closing as per my last comment.
