### ISSUE TITLE
PAC Fundraising

### ISSUE THREAD

**Issue by westurner** [OpenZeppelin/openzeppelin-solidity#502]
### Background
 - PAC: Political Action Committee
    https://en.wikipedia.org/wiki/Political_action_committee
- https://github.com/holographicio/awesome-token-sale

### Questions
- Is Civic PAC fundraising similar to e.g. a Crowdsale or a CappedCrowdsale
   or something else entirely, in terms of ERC20 OpenZeppelin solidity contracts?
- Would it be worth maintaining an additional contract for [PAC] "fundraising"
  with terminology that campaigns can understand; or a terminology map?
- Compared to just accepting donations at a wallet address,
  or just accepting credit/debt card donations,
  what are the **risks** of a token sale for a PAC?
  - Is there any way to check for donors' citizenship?
    (When/Where is it necessary to check donors' citizenship
    (with credit/debit cards or cryptocoins/cryptotokens?))
- Compared to just accepting donations at a wallet address,
  or just accepting credit/debt card donations,
  what are the **costs** of a token sale for a PAC?
  - How much gas would such a contract require?
- Compared to just accepting donations at a wallet address,
  or just accepting credit/debt card donations,
  what are the **benefits** of a token sale for a PAC?
   - Lower transaction fees than credit/debit cards?
   - Time limit (practicality, marketing)
   - Cap ("we only need this much")
   - Refunds in the event of […]

### Objectives
- Comply with all local campaign finance laws
  - Collect citizenship information for a Person
  - Collect citizenship information for an Organization 'person'
- Ensure that donations hold value
- Raise funds
- Raise funds up to a cap
- (Optionally?) collect names and contact information
  ( https://schema.org/Person https://schema.org/Organization )
- Optionally refund if the cap is not met
- Optionally change the cap midstream
- Optionally cancel for a specified string and/or URL reason

**Comment by Kowmung** [comment]
Yes please!

I am trying to get a simple raise funds contract working

**Comment by elopio** [comment]
Hey @westurner, are you still interested in moving this forward?

**Comment by westurner** [comment]
https://tplprotocol.org/

"TPL: A Validation System for Secure Peer-to-Peer Exchange" (May 2018)
https://tplprotocol.org/pdf/TPL%20-%20Transaction%20Permission%20Layer.pdf

**Comment by nventuro** [comment]
Closing due to a perceived lack of interest / information regarding what's actually needed.

**Comment by westurner** [comment]
What additional information about what information is needed does this
require?

PAC Fundraisers *must* track personally identifiable information; PII which
probably shouldn't be stored in a blockchain.

An organization *must not* simply accept anonymous donations.

Can an (Ethereum) smart contact help with this multi-billion-dollar hoopla
every 4 years?

TPL and/or an off-chain application that protects personally identifiable
information (which, in the USA, is potentially subject to FEC and IRS
review) are the best solutions for this that I'm aware of.

Donations must be held in an FDIC-insured account; per the FEC. AFAIU,
Exchanges only FDIC-insure USD deposits.

A person can, say, donate a house or other property, though, so an attorney
with election expertise may have more information regarding [PAC]
fundraising, political campaigns, and crypto*assets*

**Comment by nventuro** [comment]
@westurner if I'm understanding correctly, this would require a system where people can somehow be identified on the blockchain, which sounds out of scope for the type of contracts OpenZeppelin provides. TPL does indeed seem to be a step in the right direction.
