### ISSUE TITLE
ERC223 Support

### ISSUE THREAD

**Issue by macalinao** [OpenZeppelin/openzeppelin-solidity#512]
It would be great if a base contract for an ERC223 token was included in this toolkit.

https://github.com/ethereum/EIPs/issues/223

Thoughts? I am interested in implementing this myself.

**Comment by ajsantander** [comment]
As far as I can tell, this has already been implemented in `ownership/HasNoTokens.sol`.

**Comment by Shrugs** [comment]
@ajsantander ERC223 is more than just the tokenFallback function; and I agree that once the standard figures itself out that we should implement it as we've done with ERC20. Should we re-open this issue?

**Comment by ajsantander** [comment]
Yes please! My bad, thx @Shrugs

**Comment by ajsantander** [comment]
This issue is currently addressed by #609, but the PR is put on hold until the standard is defined.

**Comment by HarryR** [comment]
There is another project which supposedly implements the ERC-223 interface: https://github.com/clearmatics/asset-token/blob/master/contracts/AssetToken.sol (although they seem to add other stuff aside from just ERC-223)

Are there any other ERC-223 implementations which we can look at, even if the standard is 'on hold' what matters is that the implementations faithfully do the same thing, I don't think it's fair to wait for ERC-223 to die by feature-creep as extra things are added on when it does something very specific - it allows method chaining of transactions.

**Comment by shrugs** [comment]
We now have a process for in-progress proposals! They can be added under the `//proposals` folder, just like we've done with ERC1047: https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/proposals/ERC1046/TokenMetadata.sol

**Comment by evseevnntmp** [comment]
any news? someone work on this?

**Comment by GoldenDave** [comment]
> any news? someone work on this?

ERC223 has not really had wide adoption in the community. ERC777 looks like a more likely successor to ERC20

**Comment by nventuro** [comment]
Closing as stale. Also, 223 is still in the draft stage, and doesn't look like it'll move out of it anytime soon.
