### ISSUE TITLE
Add a Voluntary Withdrawal Crowdsale Contract

### ISSUE THREAD

**Issue by nedodn** [OpenZeppelin/openzeppelin-solidity#529]
Referencing this article: http://www.globalcryptopress.com/2017/10/ethereum-creator-vitalik-buterins-bold.html

and whitepaper: https://people.cs.uchicago.edu/~teutsch/papers/ico.pdf

I imagine it would be similar to RefundableCrowdsale.sol, but without the goal and with a deadline.

**Comment by elopio** [comment]
Sounds good @nedodn. Would you be interested in implementing it? With the recent refactor of crowdsales I think it would be a nice experience.

**Comment by nedodn** [comment]
Sure, I can try and throw something together over the next week, I was working on this at one point but it got kinda dropped on the wayside.

**Comment by nventuro** [comment]
This sort of thing would require the funds being stored in an `Escrow`, and could easily be added. Closing though due to lack of activity.
