### ISSUE TITLE
Abstract contracts should have internal constructors

### ISSUE THREAD

**Issue by azavalla** [OpenZeppelin/openzeppelin-solidity#558]
See https://github.com/ethereum/solidity/issues/979
and https://github.com/ethereum/solidity/issues/1040
also https://github.com/ethereum/solidity/issues/2638

**Comment by elopio** [comment]
Hey @azavalla, thanks for your report. Could you please expand a little here? Why should we add the internal constructors?

**Comment by nventuro** [comment]
This has been done throughout the library over the past couple months.
