### ISSUE TITLE
Migrate to Truffle's test node

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-solidity#579]
Things to look out for:
- Custom account balances
- Gas limit?

**Comment by Shrugs** [comment]
Truffle 4's test node doesn't currently have the ability to use custom balances, which our tests depend on.

1. work with truffle to add this feature
2. change tests to work in the lower balance range

We've decided to go with 1. 👍

**Comment by facuspagnuolo** [comment]
Latest version of Truffle 4 does not support customizing account balances for the testrpc develop and testing node. I already opened an [issue](https://github.com/trufflesuite/truffle-core/issues/91), so I'll move this one to on-hold till it get's fixed or we collaborate to work on a PR with the Truffle team.

**Comment by eordano** [comment]
Whats the reasoning behind this? Could those reasons be mitigated by moving from `testrpc` to `ganache-cli`?

**Comment by frangio** [comment]
@eordano I think `testrpc` and `ganache-cli` are aliases to the same thing. We should move to the newer name though.

I can't remember the reasoning 😅. FWIW Truffle's [release docs](https://github.com/trufflesuite/truffle/releases/tag/v4.0.0) say "Truffle Test: Faster Test Cycles & Better CI", so I'd say it's worth trying?

**Comment by elopio** [comment]
We are using truffle 4.1.8: https://github.com/OpenZeppelin/openzeppelin-solidity/blob/ba4cf03da7fd68adf8f6a055d56e34cd1e1541ef/package.json#L61

Am I missing something or can we close this issue?

**Comment by frangio** [comment]
@elopio This issue is about migrating to Truffle's in-process ganache instance, instead of launching our own.

https://github.com/OpenZeppelin/openzeppelin-solidity/blob/ba4cf03da7fd68adf8f6a055d56e34cd1e1541ef/scripts/test.sh#L53-L54

**Comment by elopio** [comment]
got it.

**Comment by nventuro** [comment]
Is there still a reason to do this?

**Comment by frangio** [comment]
Probably yes. I think it would be more performant (read: faster CI) because I think the node is in-process.

**Comment by nventuro** [comment]
Let's give it a try then and decide based on that.

**Comment by frangio** [comment]
It doesn't seem possible yet to configure account balances. Moreover, it seems that the "built in" test node is not really in-process, so there won't be any performance improvements over what we have now.
