### ISSUE TITLE
Mocha Shared Behaviour Support for all OZ contracts

### ISSUE THREAD

**Issue by androolloyd** [OpenZeppelin/openzeppelin-solidity#586]
As per our discussion in the #zeppelin_os channel on Slack, 

https://github.com/mochajs/mocha/wiki/Shared-Behaviours

Shared Behaviours would enable a much more flexible and developer friendly testing experience. 

Existing test coverage of dependant contracts would be importable into the test cases being generated for new contracts. 

This would greatly improve the test development experience for simple and complex contracts and bring a significant level of assurance to changes/emerging patterns and visibility into breaking issues.

**Comment by frangio** [comment]
Thanks for this idea @androolloyd! After your suggestion we've added some behaviors in the library, but they're poorly documented and not well maintained. We're planning to improve that soon and are tracking that issue in #1085.
