### ISSUE TITLE
Make Web3 Injectable in the helper functions

### ISSUE THREAD

**Issue by subramanianv** [OpenZeppelin/openzeppelin-solidity#589]
Helper functions such as ```latestTime()``` use Web3. Web3 is injected when truffle runs the test. If you want to use these helper functions outside tests, then web3 has to passed as an argument

**Comment by frangio** [comment]
This would be great.

**Comment by nventuro** [comment]
Test helpers have been moved to https://github.com/OpenZeppelin/openzeppelin-test-helpers.
