### ISSUE TITLE
Unnecessary use of require checks while using SafeMath

### ISSUE THREAD

**Issue by rmi7** [OpenZeppelin/openzeppelin-solidity#611]
When looking through the contracts I notice usage of `require` statements that are not really needed because of using `SafeMath`. Basically the same check as in the preceding `require` is implicitly executed when using the `SafeMath` operation.

For example here: [BasicToken Line 24](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/token/BasicToken.sol#L24), which can be removed because the usage of `SafeMath.sub` on line 27 will implicitly check if `_value <= balances[msg.sender]`.

So shouldn't these `require` statements be removed, or am I missing something?

**Comment by Shrugs** [comment]
I'm pretty ambivalent to whether or not these stay, but the devils advocate argument is that clarity and readability (rather than implied assumptions) is worth the extra gas usage and duplicative check.

But again, I don't really have a strong opinion. Open to others.

**Comment by elopio** [comment]
@rmi7 It would be nice to discuss this over a PR, with some calculations of the gas being saved. Would you like to work on that?

**Comment by rmi7** [comment]
@elopio sounds good to me, I'll make a PR tomorrow

**Comment by rmi7** [comment]
I tested it locally on `master`,

if we remove the `require(_value <= balances[msg.sender])` line, and we trigger an under/overflow, `assert` will be triggered inside `SafeMath`, this will use up all the gas of the transaction instead of just using what was used up until now when using `require`.

So I say keep it as is, and close this issue.

**Comment by roschler** [comment]
What would be the harm in creating a clone of SafeMath that used require() everywhere instead of assert()?

**Comment by rmi7** [comment]
I think with the adding of error messages in recent solidity, as in:

`require(_value <= balances[msg.sender], "not enough balance")`

it makes sense to keep the original `require`.

If we were to remove it and rely on the checks inside `SafeMath`, we will have no ability to return a message with `"not enough balance"`, since `SafeMath` does not know it's doing a calculation on an erc20 balance, as far as it knows it's just doing a math calculation on 2 `uint`.

So even though the check happens twice if we keep it this way, and we could get the same result with 1 check, it still makes sense to keep the two because of the context (=contract) in which the check is performed.

**Comment by elopio** [comment]
As I see it, SafeMath uses assert to encourage callers to pass correct values. So the situation where BasicToken uses require and SafeMath uses assert seems good to me. Of course, that is my interpretation coming late to the game, there might be some good reasons to replace the SafeMath `assert`s with `require`s, but in that case, it's still good to have a require with a nicer user message. 

I'm closing this one, and we can discuss SafeMath updates in a separate bug, if somebody is interested on that.

@rmi7 would you mind making a PR to add the require message?

Thanks for the nice discussion here.

**Comment by rmi7** [comment]
@elopio 

I think we should add error messages to all requires in 1 PR, not just this one.
