### ISSUE TITLE
SafeMath - support for shift-left

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/openzeppelin-solidity#626]
Perhaps you can add support for shift-left in the SafeMath library:

```
function shl(uint256 x, uint8 y) internal pure returns (uint256) {
    uint256 z = x << y;
    assert((z >> y) == x);
    return z;
}
```

**Comment by ajsantander** [comment]
@barakman would you like to submit a PR of this, ideally with a test?

**Comment by barakman** [comment]
@ajsantander: Not sure how to do that here. The `Create pull request` option is disabled, with `Choose different branches or forks above to discuss and review changes` appearing next to it.

The code for this functionality is already given above, and the test is provided hereby:

```
    let ONE = web3.toBigNumber(1);
    let TWO = web3.toBigNumber(2);

    for (let n = 0; n < 256; n++) {
        it(`test:`, async () => {
            try {
                let retVal = await safeMath.shl.call(ONE, web3.toBigNumber(n));
                assert(n < 255 && retVal.equals(TWO.toPower(n)), `test passed when it should have failed`);
            }
            catch (error) {
                assert(n == 255, `test failed when it should have passed`);
            }
        });
    }
```

I'd be happy to submit it myself, but I will need some specific instructions on how to do it here.

Thanks

**Comment by ernestas2k** [comment]
@barakman I've created pull request for the functionality. Take a look

**Comment by nventuro** [comment]
Closing due to the stalness. If someone does require this feature to be implemented, please also share your use case along with it.

**Comment by wbt** [comment]
Left shift on uints can be emulated with multiplication by a power of 2.  I haven't tested if it's faster in EVM or not.  Some use cases are [here](https://stackoverflow.com/q/520625/798371) but in all cases where I've used left-shift, it's been either (a) not a case where SafeMath would be needed because I wasn't working with representations of numbers, or (b) a shortcut way of doing multiplication.

**Comment by barakman** [comment]
@wbt:
You seem to be forgetting the fact that computing the power of 2 by itself has a "price tag" attached to it.

If the exponent is known then you can use a constant value of course, but otherwise, the operation `x << y` would be replaced with `x * uint256(2) ** y`, which has a much higher "price tag" attached to it.

**Comment by wbt** [comment]
@barakman Good point.  I was primarily considering the case where the exponent is known and a constant value can be used, but it isn't always.
