### ISSUE TITLE
Research DAICOs

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#681]
- [x] 📈 This is a feature request.

See: https://ethresear.ch/t/explanation-of-daicos/465

**Comment by kvbik** [comment]
big part of the DAICO idea was already described by @vbuterin in his ICO methods article [1]

[1] https://vitalik.ca/general/2017/06/09/sales.html

we at @windingtree liked the idea so much, we've implemented it as a part of our token generation event and call it Market Validation Mechanism, feel free to read more [2] about [3] it.

[2] https://blog.windingtree.com/l%C3%ADf-token-generation-event-f9edb43db739
[3] https://blog.windingtree.com/market-validation-mechanism-in-a-nutshell-ddba1d92be89

but most importantly, we have an implementation [4] - we can try to start a work on `DAICO` based on our `MVM`

[4] https://github.com/windingtree/LifToken/blob/master/contracts/LifMarketValidationMechanism.sol

**Comment by AugustoL** [comment]
Yes, I think we were the first ones to implement a DAICO at @windingtree, for us is a validation mechanism, either way the name does not matter. The cool thing about this is to decentralize the ownership/control of the funds raised ! 🎊 

Although I like the MVM idea I would like to think on a solution that provides this control over an unlimited amount of time, in our case the MVM and what Vitalik propose there is an initial distribution and a period for the the "validation mechanism", but whats happens after? 

For our MVM we destroy tokens that it receives and give ETH back, to continue the validation process maybe it can start a sell of the burned tokens in the past validation period?

Something like:

Token Distribution -> Validation Period (tokens are burned, % contributions refunded) -> Redistribution Period (burned tokens, raise more funds) -> Validation Period again..

Seems like a good model for non profit / open source projects.

**Comment by marksaitis** [comment]
any news re daicos? I think they are crucial for faster success

**Comment by nventuro** [comment]
While interesting and definitely something that could be a part of OpenZeppelin, I'm closing to reduce the issue clutter, and due to a lack of activity.
