### ISSUE TITLE
Pre sale contract

### ISSUE THREAD

**Issue by agri9394** [OpenZeppelin/openzeppelin-solidity#703]
How can we create a pre sale contract using openZeppelin and it will be very helpful if any example is available on github ?

**Comment by frangio** [comment]
Hi @agri9394!

A pre-sale contract sounds like a good fit for OpenZeppelin. I think we should reformulate it more generically as a Crowdsale with different stages.

**Comment by benstew** [comment]
I agree with @frangio on this one. Setting up as multi-round crowdsale is probably the best option. The only downside is that you will need to now the allocation percentages for the presale round and the general round at time of deployment

**Comment by jacktang** [comment]
@frangio any progress on this issue?

**Comment by frangio** [comment]
No one has been developing this yet AFAIK.

**Comment by troggy** [comment]
Naive version of the CrowdsaleWithPresale contract: https://gist.github.com/troggy/8287b1c714f951e0da7fd27ebf842e5b

**Comment by nventuro** [comment]
There was some discussion about a Crowdsale that had multiple stages with different rates in https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1072, but it ended up abandoned due to a lack of interest. Closing this for similar reasons.
