### ISSUE TITLE
Improve SafeMath to support signed int operations

### ISSUE THREAD

**Issue by facuspagnuolo** [OpenZeppelin/openzeppelin-solidity#705]
- [x] 📈 This is a feature request.

The idea is to provide basic math operations (like `add`, `sub`, `mul`, etc) for signed integers. I think this could be added within `SafeMath` itself.

**Comment by cedricwalter** [comment]
see https://github.com/OpenZeppelin/zeppelin-solidity/pull/714

**Comment by wbt** [comment]
Just to create a cross-reference, [PR#1484](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1484) expands on SafeMath for `uint32`s, which overflow at somewhat less astronomical values but don't have all the new potential issues that signed integers introduce.
