### ISSUE TITLE
Examples on TokenTimeLock and TokenVesting

### ISSUE THREAD

**Issue by xiaoyao1991** [OpenZeppelin/openzeppelin-solidity#706]
- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

Thanks for the awesome contributions Zeppelin team. I wonder if there're any examples or tutorials on how to use TokenTimeLock and TokenVesting specifically?

**Comment by frangio** [comment]
Agreed @xiaoyao1991! There are no examples currently.

**Comment by cedricwalter** [comment]
@xiaoyao1991 unit test are providing a good start 

https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/test/token/TokenVesting.test.js

https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/test/token/TokenTimelock.test.js

or in solidity

uint256 public constant VESTING_CLIFF = 1 years;
uint256 public constant VESTING_DURATION = 3 years;

MintableToken token = new MintableToken();
TokenVesting newVault = new TokenVesting(beneficiary, now, VESTING_CLIFF, VESTING_DURATION, false);
token.mint(address(newVault), _tokens);

**Comment by xiaoyao1991** [comment]
@cedricwalter Thanks! I'll take a look
