### ISSUE TITLE
Add a new SecureToken contract which integrates Pausable and other Zeppelin security features

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#72]
Throwing this idea out there for discussion

**Comment by Shrugs** [comment]
Would also love the `SafeSend` feature; use push payment

**Comment by Shrugs** [comment]
(sorry, mouse slipped!)

**Comment by elopio** [comment]
We have [PausableToken](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.9.0/contracts/token/ERC20/PausableToken.sol), so I'll close this.
For the other security features, please file individual issues for each of them, if we don't have them yet.
