### ISSUE TITLE
Add Authorizable contract

### ISSUE THREAD

**Issue by medvedev1088** [OpenZeppelin/openzeppelin-solidity#743]
## 🎉 Description

Something like this:

```
contract Authorizable is Ownable {

    mapping(address => bool) public authorized;

    modifier onlyAuthorized() {
        require(authorized[msg.sender] || owner == msg.sender);
        _;
    }

    function addAuthorized(address _toAdd) onlyOwner public {
        authorized[_toAdd] = true;
    }

    function removeAuthorized(address _toRemove) onlyOwner public {
        authorized[_toRemove] = false;
    }

}
```
- [+] 📈 This is a feature request.

Originally discussed here https://ethereum.stackexchange.com/questions/39654/smart-contract-multiple-owners/39657#39657

**Comment by eordano** [comment]
+1!

**Comment by medvedev1088** [comment]
@eordano I've just found contracts/ownership/rbac/RBAC.sol contract that provides similar capabilities to Authorizable.  Do you think Authorizable will be useful?

**Comment by martriay** [comment]
@medvedev1088 why would you prohibit `0x0` to be authorized?

**Comment by medvedev1088** [comment]
@martriay no reason. Forgot to remove it while copying from stackexchange.

**Comment by martriay** [comment]
I like the idea and I definitely would have it separate from RBAC. I'd call it `Whitelist` instead, and have it emit events on every add/removal, along with a check to avoid redundant storage writes and event firings.

**Comment by medvedev1088** [comment]
@martriay Sounds good to me. Although not sure about "check to avoid redundant storage writes". The check itself will add 200 gas right? because we need to read from the storage first. In most cases the owner can make this check off-chain instead to prevent redundant storage write.

What do you think?

**Comment by medvedev1088** [comment]
@martriay do you think I should `revert()` or just ignore on redundant call?

**Comment by martriay** [comment]
@medvedev1088 I would make the function return a boolean value indicating if it was successful. This way the contract can be used programmatically by other contracts and react accordingly.

**Comment by medvedev1088** [comment]
Ok, btw the compiler will auto-generate a public getter for the whitelist. Do you think we still need `isWhitelisted(address)`?

**Comment by martriay** [comment]
Yes, it can be left out.

**Comment by medvedev1088** [comment]
@martriay @eordano Please take a look https://github.com/OpenZeppelin/zeppelin-solidity/pull/746. Any comments are welcome.

**Comment by elopio** [comment]
Already merged. Thank you @medvedev1088 !
