### ISSUE TITLE
Automate docs generation using solidity-docgen.

### ISSUE THREAD

**Issue by ealmansi** [OpenZeppelin/openzeppelin-solidity#751]
## 🎉 Description

Documentation is currently generated manually by running the [solidity-docgen](https://github.com/spalladino/solidity-docgen) project. It would be great if we automated this process as part of the build step on every major and minor version update.

- [x] 📈 This is a feature request.

**Comment by ealmansi** [comment]
cc @ajsantander

**Comment by eordano** [comment]
Not sure about this: It would pollute the repository with generated files. Perhaps after dev installs? What if instead the documentation is published to github pages?

**Comment by nventuro** [comment]
This is already happening as part of the docsite revamp @frangio is carrying out.

**Comment by frangio** [comment]
To be clear, this is already happening _today_. The docsite is deployed automatically.
