### ISSUE TITLE
Evaluate adding standard interface detection to all contracts

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-solidity#754]
## 🎉 Description

EIP 165 (discussed [here](https://github.com/ethereum/EIPs/pull/881)) provides a standard way for contracts to query for implemented interfaces. Discuss whether we want to add support for this standard in OpenZeppelin contracts.

-  📈 This is a feature request.

**Comment by mudgen** [comment]
I would like support for it in the OpenZepplin contracts.

**Comment by nventuro** [comment]
This came up recently in https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1629: I'm closing this to continue the discussion there, since it seems like we won't be moving forward with it.
