### ISSUE TITLE
Encapsulate public variables throughout

### ISSUE THREAD

**Issue by fiiiu** [OpenZeppelin/openzeppelin-solidity#760]
## 🎉 Description

Right now, many variables are publicly accessible, which could raise issues in some inheritance patterns, for instance if some required checks are not properly enforced by derived contracts. It would be safer to encapsulate the variables and provide setters and getters for clients to use. This issue is meant to foster discussion on this topic, to eventually converge on a unified proposal on how to deal with this. 

- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

**Comment by nventuro** [comment]
This has been done for the v2.0.0 release: all variables are now `private`, with `public` getters and setters where applicable.
