### ISSUE TITLE
Evaluate metadata standards at token and contract level

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-solidity#761]
There are proposals for standardising the information that can be attached to a non-fungible asset as metadata, in order to be consumed by a dapp and displayed appropriately to an end-user.

Evaluate such standards, and consider adding them to OpenZeppelin. Note that metadata could affect not just each token individually, but an entire token contract as well. For instance, a given ERC721 contract could have shared metadata that affects all its tokens. Or an ERC20 could have an image and description for all its tokens, to be picked up by a wallet, following the same structure as 721 metadata for compatibility.

**Comment by elopio** [comment]
@nventuro has been playing with [eip-1046](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1046.md) for ERC20: https://github.com/zeppelinos/crafty/

**Comment by nventuro** [comment]
The extension is quite simple: https://github.com/zeppelinos/crafty/blob/master/contracts/ExtendedERC20.sol

**Comment by shrugs** [comment]
https://github.com/OpenZeppelin/openzeppelin-solidity/pull/933
