### ISSUE TITLE
Discuss adding delegate proxy implementation

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-solidity#784]
- 📈 This is a feature request.

[EIP897](https://github.com/ethereum/EIPs/pull/897), based on the work by @izqui and @maraoz, implements delegate proxies, which we will be using throughout zeppelin_os. Should we consider adding a default implementation here in OpenZeppelin as well, so anyone can roll out their own proxies?

**Comment by izqui** [comment]
I completely support this motion. They are becoming such a core piece of the stack that zeppelin-solidity should definitely provide them

**Comment by frangio** [comment]
We've released this in [zeppelinos/zos-lib](https://github.com/zeppelinos/zos-lib). :smile:

**Comment by WyseNynja** [comment]
New URL: https://github.com/zeppelinos/zos/blob/master/packages/lib/README.md
