### ISSUE TITLE
Separating the 'validation' contracts logic from crowdsale contracts

### ISSUE THREAD

**Issue by PhABC** [OpenZeppelin/openzeppelin-solidity#813]
## 🎉 Description
Whitelists and other access/validation functionalities should be standalone contracts, independent of crowdsale contracts. The rationale is that other types of contracts (e.g. gouvernement, exchanges, +18y/o games) might want to implement some sort of access control logic gates. I would suggest rewriting some of contracts along these lines. For instance, [WhitelistedCrowdsale.sol](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/crowdsale/validation/WhitelistedCrowdsale.sol) could be rewritten as `Whitelisted.sol`, like [this](https://gist.github.com/PhABC/cf0e8167e493d8758b46eecbf15dfd87). A Whistelisted contract could then be set to `WhitelistedCrowdsale is Whitelisted, Crowdsale, Ownable { ... }`. 

- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

**Comment by nventuro** [comment]
This has been as proposed for a while now, closing.
