### ISSUE TITLE
Bonding Curve aka Automatic Market Maker Contract

### ISSUE THREAD

**Issue by balasan** [OpenZeppelin/openzeppelin-solidity#819]
## 🎉 Description

I'm working on a PR to add a simple bonding curve contract (aka automatic market maker) based on Bancor formula. Here is the reference contract: https://github.com/relevant-community/contracts/blob/master/contracts/BondingCurve.sol

I have a few questions about structure and dependencies:
- [x] Folder structure —where should this contract go? ```/token```? a separate ```/bondingcurve``` folder?  

Planning on adding a ```curation-markets``` folder width ```BancorFormula.sol``` and ```BondingCurve.sol```. Adding ```Power.sol``` function to the ```math``` folder.
- [x] The contract depends on the ```BancorFormula.sol``` contract with some fancy tricks to compute fraction exponents and comes along with python folder to generate constants and test them: https://github.com/bancorprotocol/contracts/tree/master/solidity/python Do we want to include this in the zeppelin repo or is it enough to link out to it?

Extracting the power function into a  separate ```Power.sol``` (licensed under Apache 2.0) file in the ```/math``` folder.

- [x] Bancor has a .js test for BancorFormula.sol, so I assume we will want to include it: https://github.com/bancorprotocol/contracts/blob/master/solidity/test/BancorFormula.js   

Renaming this to ```Power.test.js```. The file is very lengthy — its iterating through all the constants generated via python — do we want to keep it?

- [x] license - Bancor code is licensed under Apache License v2.0 and OpenZeppelin is MIT, is there a conflict here? do we need some special notice when we use Bancor code?  

Adding a an Apache 2.0 License and modification notice to the  ```BancorFormula.sol``` and ```Power.sol``` files with links to the Bancor repo. 

-------

- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

## 👍 Other Information

Some background reading about bonding curves:  
https://hackernoon.com/how-to-make-bonding-curves-for-continuous-token-models-3784653f8b17
https://medium.com/@simondlr/tokens-2-0-curved-token-bonding-in-curation-markets-1764a2e0bee5
and Bancor formula:
https://drive.google.com/file/d/0B3HPNP-GDn7aRkVaV3dkVl9NS2M/view

**Comment by Shrugs** [comment]
- looks like we've been putting random stuff like that at the top level (see Bounty, DayLimit, ECRecovery). so I'm cool with putting it there until we have a reason to give it its own folder
- wew that's a lot of extra stuff. My opinion is to link it out and simply have the tested/audited stuff in OZ, but that's not a strong opinion. it also means we'd have to train maintainers on how to maintain that code as well, which doesn't seem exciting.
- yeah we'd want the tests as well
- I don't know enough about the licensing to comment
- thanks for the extra bonding curve links!

cc @maraoz for the rest of these questions?

**Comment by balasan** [comment]
thanks @Shrugs!
One advantage of a separate folder is to keep BondingCurve.sol and BancorFormula.sol close together

One more note:
I could move the exponentiation ```power``` function from the BancorFormula into a separate contract in the math folder. This will make BancorFormula contract very simple (could even merge it into a single BondingCurve.sol) and all the complex python constants will live in ```power```. This will also make ```power``` usable in other contracts—for example continuous inflation.

**Comment by Shrugs** [comment]
I hadn't actually looked at those files, so now that makes a lot of sense. I like the `Power.sol` + `BondingCurve.sol` approach. Only downside is that now it's not 1:1 with the existing bancor stuff. If we want to keep it as `BancorFormula` and `BondingCurve`, I'd support another folder called something like `curation-markets` or similar, where we can put generic TCRs as well.

**Comment by balasan** [comment]
Cool, yeah I like that too. Especially since ```BancorFormula.sol``` it won't be 1:1 anyway if we want to use Zeppelin's math library instead Bancor's ```Utils.sol```.

Will get started with this approach unless anyone else objects.

**Comment by balasan** [comment]
RE: license, I'm looking at this: https://softwareengineering.stackexchange.com/questions/297217/using-code-under-apache-2-0-license-in-my-program-using-mit-license

Seems like the best thing to do is keep stuff from Bancor separate from the Zeppelin stuff. Seems like the best way to do it would be separate ```Power.sol```, ```BancorFunction.sol``` files with a license note at the top and separate ```BondingCurve.sol``` that would fall under the default Zeppelin license. (Unless we just make a single ```BondingCurve.sol``` licensed under Apache... 🤔

**Comment by Shrugs** [comment]
I can't really comment on the validity of any licensing approaches, but I like the idea of putting Power and Bancor stuff into apache compliance with a header and keeping BondingCurve under the Zeppelin license (MIT).

Can you update the post at the top to describe the changes we've figured out (namely folder structure, which files are added, licensing)

**Comment by balasan** [comment]
PR is in!
In case the ```Power.sol``` function is too much of a maintenance/trust risk for OpenZeppelin, I extracted the bonding curve code to a separate repo: https://github.com/relevant-community/bonding-curve

Also note: there is a TODO to add a ```minReturn``` parameter to the ```buy``` and ```sell``` functions — this is to prevent front-running by miners. This may be another reason to hold off merging into Zeppelin repo and work on this in the dedicated one.

**Comment by nventuro** [comment]
Closing due to staleness. Also, @balasan has proposed an alternative repository where this can be found.
