### ISSUE TITLE
Add an atomic swap contract for cross-evm-erc20-chains sending of Tokens

### ISSUE THREAD

**Issue by eordano** [OpenZeppelin/openzeppelin-solidity#833]
## 🎉 Description

- [ ] 🐛 This is a bug report.
- [X] 📈 This is a feature request.

## 📝 Details

A number of projects are planning to build on their own evm compatible chain. I think we should add an exchange contract that allows secure transaction of tokens from one chain to the other.

This would work in 5 steps:

0. Alice (who has tokens on chain 1) picks a secret value and transmits the hash of it to Bob (who has tokens on chain 2)
1. Alice locks her tokens on chain 2, such that Bob can take out this tokens if he knows the secret
2. Bob sees the confirmation of that transaction, and then proceeds to lock his tokens on chain 2, such that Alice can take out these tokens by revealing the secret
3. Alice takes out the tokens from chain 2, revealing the secret (this should be included in an event log for easy access)
4. Bob sees the transaction on chain 2 and takes out his tokens from chain 1

Refund scenario:

If Bob never locks his tokens on chain 2, then Alice can, after a grace period, execute a refund to recover her tokens.

## Scribble

**PLEASE DO NOT USE THIS CODE** as it's just a scribble and it needs A LOT of work.

```pragma solidity 0.4.21;

contract ERC20 {
    function transferFrom(address, address, uint) public;
}

contract Atomic {
    // Mapping from receiving address to preimage to amount
    mapping (address => mapping(bytes32 => uint)) public contracts;
    
    // Mapping from sending address to preimage to time
    mapping (address => mapping(bytes32 => uint)) public refundTime;

    // Only one atomic swap per address at a time (prevents hash reuse)
    mapping (address => bool) public locked;

    event Execution(address indexed sender, address indexed receiver, bytes32 secret, bytes32 indexed hashed);
    
    uint public GRACE_PERIOD = 5 days;
    
    ERC20 public token;

    /**
     * Store a given `amount` of ERC20 tokens to be released by `receiver` upon
     * revealing a secret that hashes to `hashedSecret`.
     */
    function store(address receiver, bytes32 hashedSecret, uint amount) public {
        require(!locked[msg.sender]);
        contracts[receiver][hashedSecret] = amount;
        locked[msg.sender] = true;
        refundTime[msg.sender][hashedSecret] = now + GRACE_PERIOD;
        token.transferFrom(msg.sender, this, amount);
    }

    /**
     * Execute an atomic swap by releasing the preimage
     */
    function execute(address receiver, bytes32 secret, address sender) public {
        bytes32 hash = keccak256(secret);
        uint amount = contracts[receiver][hash];
        delete locked[sender];
        delete contracts[msg.sender][hash];
        delete refundTime[sender][hash];
        token.transferFrom(this, receiver, amount);
        Execution(sender, receiver, secret, hash);
    }

    /**
     * Fallback in case the counterparty never executed an equivalent transaction
     * in the other chain
     */
    function refund(address receiver, bytes32 hashedSecret, address sender) public {
        require(now > refundTime[sender][hashedSecret]);
        delete locked[sender];
        delete contracts[receiver][hashedSecret];
        delete refundTime[sender][hashedSecret];
        token.transferFrom(this, sender, contracts[receiver][hashedSecret]);
    }
}
```

**Comment by frangio** [comment]
Great idea.

Can you expand one the reason for the `locked` bit?

**Comment by eordano** [comment]
That’s just a quick fix for an attack that can happen because of the way I was coding it.

I can “burn” the tokens for someone if I send twice a request. There are far better ways to solve this.

**Comment by Shrugs** [comment]
I like having a canonical implementation for this. Is there a complementary EIP standard? Not sure if there needs to be one, but regardless it'd be good for them all to have the same interface.

Which group/individual is working very directly on cross-EVM-chain swaps? It'd be good to get their opinion/involvement.

**Comment by HarryR** [comment]
@shrugs I also have a HTLC implementation 

see: https://github.com/HarryR/shwop/blob/master/contracts/HTLC.sol

I think it would be a very good idea to have a standard ERC for hash-time-locks

Do you fancy working together on this together? There are a few other projects I've linked in a ticket: https://github.com/HarryR/shwop/issues/5

There are a few issues which need documenting and enforcing, such as unequal timeouts to provide one party enough time to withdraw before a refund.

**Comment by shrugs** [comment]
We would certainly welcome an HTLC PR!

**Comment by nventuro** [comment]
Indeed, a more generic hash-time-lock framework does seem more useful (and could benefit from our intended new escrows: #1099). Closing for now due to a perceived lack of interest.
