### ISSUE TITLE
Restrict permission to internal owner (contract) instead of external owner (deployer)

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/openzeppelin-solidity#853]
## 🎉 Description

I have several places in the code, where calling an external function should be permitted only to some other contract. Typically, that contract holds (or has a reference to) the contract which implements the external function. Of course, if a reference (`address` or `interface`) is used, then there can be several contracts holding the contract which implements the external function.

- [x] 📈 This is a feature request.

## 💻 Environment

I am using Truffle + Ganache on Windows, but this feature request is generally platform-agnostic.

## 📝 Details:

I have implemented this feature, and thought it might be appropriate for you to add it too.

My naming conventions are:
- 'owner' - deployer of the contract (same definition as yours)
- 'user' - some other contract

I have named this module 'Callable', since it supports both 'owner' and 'user', to which I refer by the general term 'caller':

```
contract Callable is Claimable {
    mapping (address => bool) public users;

    /**
     * @dev This method adds the given address to the list of `users`.
     */
    function addUser(address user) external onlyOwner {
        users[user] = true;
    }

    /**
     * @dev This method removes the given address from the list of `users`.
     */
    function remUser(address user) external onlyOwner {
        users[user] = false;
    }

    /**
     * @dev Throws an exception if called by any contract other than one of the `users`.
     */
    modifier onlyUsers() {
        require(users[msg.sender]);
        _;
    }
}
```

Thanks

**Comment by Shrugs** [comment]
You can see a similar version of this pattern in [RBAC.sol](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/ownership/rbac/RBAC.sol) and RBACWithAdmin.sol, which allows for a variety of roles and restrictions. (it's pending a slight update in https://github.com/OpenZeppelin/zeppelin-solidity/pull/836)

**Comment by shrugs** [comment]
closing as stale, but let us know if you want to chat about it more!
