### ISSUE TITLE
Create DestructibleCrowdsale that removes itself after finalization.

### ISSUE THREAD

**Issue by Shrugs** [OpenZeppelin/openzeppelin-solidity#862]
##  Description

It'd be cool to have a crowdsale remove itself from the blockchain after it's been finalized. There's no _real_ benefit to this, except for the nice feeling you get by making the Ethereum blockchain lighter.

- [x] 📈 This is a feature request.

---

from https://github.com/OpenZeppelin/zeppelin-solidity/issues/852

**Comment by PhABC** [comment]
I wrote a tangentially related contract which I think more destructible contracts should have, where a delay is introduced between the destruction request and the destruction event. See [DelayedDestructible.sol](https://gist.github.com/PhABC/79ff357dec99fef8bc32a33db469c4af) for the implementation. The `destroyRequest` function could easily be overwritten or modified to include a `require(!finalized)`.

**Comment by Shrugs** [comment]
I like the delayed destructible! That would be a good utility addition to OZ, and then we could use it here as well. I think the `SELFDESTRUCTION_DELAY` should be a constructor arg, though.

**Comment by PhABC** [comment]
Will make a separate PR later today, but yes I agree the delay should be a constructor arg. So long as it can't be changed, I think it's fine. The main rationale is for people to have time to adjust before the destruction of the contrat occurs.

**Comment by frangio** [comment]
I disagree with this. In general I don't think any contract that receives ether should be `selfdestruct`ed. That is because once the contract is destroyed all ether sent to it will be lost.

In the case of crowdsales, once the crowdsale is over it should reject all ether sent to it. If the contract is destroyed, however, there will be no code to reject these transactions.

**Comment by Shrugs** [comment]
☝️that's a really good point about crowdsales. I think selfdestructs are still a valuable tool, but perhaps not in this specific case.
