### ISSUE TITLE
Create vulnerable contract and deploy a Bounty, as an example/challenge

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#88]

**Comment by vinniejames** [comment]
I like this

**Comment by elopio** [comment]
The [ethernaut](https://github.com/OpenZeppelin/ethernaut) serves this role. It has no bounty; but it's a game so the incentive is there, it's just not money.

I think there's nothing left to do here, we can just keep adding levels to ethernaut every time we find an interesting vulnerability.
