### ISSUE TITLE
Add `isValidSignatureAndData` to Bouncer to verify method calls.

### ISSUE THREAD

**Issue by shrugs** [OpenZeppelin/openzeppelin-solidity#891]
## 🎉 Description

Add the ability for `Bouncer.sol` to check the method signature and/or arguments to a method, to allow a bouncer to sign a message for a very specific function call.

The naive approach of 
```
return isValidDataHash(
      keccak256(address(this), _address, msg.data),
      _sig
    );
```

won't work because the signature is part of the data and you need the data to sign and you need the signature to get the data and you need the data to sign you get the point.

One option is to enforce that the signature is always at the end of the msg.data and then ignore the last 32 bytes.

- [x] 📈 This is a feature request.

**Comment by aflesher** [comment]
I can grab this issue if no one else is working on it.

For the method signature should we just add a bool to determine if it should validate the arguments and methodId or just the methodId ?
`function isValidSignatureAndData(address _address, bytes _sig, bool _validateArgs)`

Also I can't think of any alternative to:

> One option is to enforce that the signature is always at the end of the msg.data and then ignore the last 32 bytes.

so I'll just implement that

**Comment by shrugs** [comment]
@aflesher do you think it's worth two different methods/modifiers instead of the boolean switch?

**Comment by aflesher** [comment]
Good point. I think it does make sense to separate them.
