### ISSUE TITLE
helper contracts for separating logic and data

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/openzeppelin-solidity#9]
Idea from https://youtu.be/1D7BH8krdhQ?t=11m54s

Some of this is already present in Ownable.sol, but needs more thought

**Comment by elopio** [comment]
I think people can apply this pattern with what we have in the repo. He mentions transfer ownership, that's [Ownable](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.9.0/contracts/ownership/Ownable.sol). He mentions transferring stuff before self destruct, [https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.9.0/contracts/lifecycle/TokenDestructible.sol](TokenDesctructible) shows how to do that. With these, somebody can make a contract for data and another that allows to transfer the ownership of that data.

He also mentions a generic storage. We have been experimenting with that in the labs on [EternalStorage](https://github.com/zeppelinos/labs/blob/master/upgradeability_using_eternal_storage/contracts/EternalStorage.sol), but I'm not sure if we want to move something like that into openzeppelin.

I also don't think it would be a good idea to apply this pattern to all the contracts in openzeppelin; and most of his concerns will be solved by the upgradeability in [zeppelinOS](http://zeppelinos.org/). 

I'm not going to close this issue (yet), in case I'm missing some details that we would like to have in the framework.

**Comment by nventuro** [comment]
I think proxy contracts (such as [ZeppelinOS's](https://zeppelinos.org/)) are a more robust solution to this issue, and should advocate for those when this requirement is present.
