### ISSUE TITLE
Add to Ownable a function to renounce ownership

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-solidity#903]
I think we should have a function in `Ownable` to set the `owner` state variable to 0, since this can't be done by using `transferOwnership`.

Not sure about the name, but I was thinking `renounceOwnership`.

**Comment by OTTTO** [comment]
Seems superfluous. 
Owner can just call the function and set the new owner to 0x0..., any listeners would than receive this information from the event. And anyone who wants to verify for themselves can simply check the public ```owner``` variable.

**Comment by frangio** [comment]
@OTTTO, in fact `transferOwnership` cannot be used to set the owner to 0x0 since a while ago. Hence this issue.

https://github.com/OpenZeppelin/zeppelin-solidity/blob/77cc33fc5c4d0b0d03aec1d8bba77edc9a7196ae/contracts/ownership/Ownable.sol#L37

**Comment by stefek99** [comment]
I saw the updated code and I agree with @OTTTO that it seems *superfluous* - had to Google that word.

![image](https://user-images.githubusercontent.com/249703/40700864-4cafd9ea-63d3-11e8-8e0e-f7c1cef18bbe.png)

There is `require(newOwner != address(0));` preventing from accidental disasters, alternative approach would be to use so magic value `0x00000000001` here, so the `renounce` makes more sense.
