### ISSUE TITLE
📈assertRevert with message checking.

### ISSUE THREAD

**Issue by MoMannn** [OpenZeppelin/openzeppelin-solidity#917]
Provide assertRevert with the ability to check the revert message (added in solidity 0.4.22).

**Comment by nventuro** [comment]
Not 100% sure on what you have in mind with this, do you want to provide an expected error message, and have the assert fail on a mismatch?

**Comment by MoMannn** [comment]
Bingo, that is exactly what I meant.

**Comment by nventuro** [comment]
With #326 on the horizon, it makes sense to add the capability to the helpers, but I don't know if we want to commit to error messages in OZ itself yet. @frangio WDYT?

**Comment by frangio** [comment]
There's #888 for discussing revert reasons (error messages) in OpenZeppelin itself.

It makes sense to move forward with this helper though even before we introduce reasons in OpenZeppelin.

**Comment by justuswilhelm** [comment]
Hi @MoMannn , I was looking into this issue and wanted to extend `assertRevert` as per your suggestion to check for `revert()` error messages. Now I realize, that I actually don't know how to access the error message in a Truffle test. Do you have any pointers on how to approach this?

**Comment by MoMannn** [comment]
@justuswilhelm Sorry I have never went into the details of truffle so I can't really help you here it is just a feature I would like to have. @shrugs will probably be a better person to address this.

**Comment by nventuro** [comment]
Sadly, it looks like this isn't yet possible in web3: https://github.com/ethereum/web3.js/issues/1707.

**Comment by frangio** [comment]
web3.js is not the culprit. There is actually no way to retrieve the revert reason from a node. [EIP 758](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-758.md) is a proposal to solve that, and there's Geth (https://github.com/ethereum/go-ethereum/pull/16424) and Ganache (https://github.com/trufflesuite/ganache-core/issues/116) issues to implement it.

I guess we'll have to wait and see how that plays out.

**Comment by nventuro** [comment]
Looks like truffle 5.0 will allow for this to be possible: see the relevant [beta release notes](https://github.com/trufflesuite/truffle/releases/tag/v5.0.0-beta.0#reason-strings).

**Comment by remon-nashid** [comment]
It is worth noting that checking revert reason is _currently_ possible with Ganache CLI, as demoed in this repo https://github.com/remon-nashid/assertRevert.

**Comment by frangio** [comment]
@remon-nashid Nice! Are you interested in incorporating your code into the OpenZeppelin helper?

**Comment by remon-nashid** [comment]
IMO this issue can be closed as 'assertRevert' is superseded by `shouldFail.withMessage`.

**Comment by MoMannn** [comment]
@remon-nashid agreed. Closing.
