### ISSUE TITLE
Why doesn't mul() check for b == 0 in the first if?

### ISSUE THREAD

**Issue by jeffreydwalter** [OpenZeppelin/openzeppelin-solidity#930]
## 🎉 Description

I'm just curious to know why this function:
```
  function mul(uint256 a, uint256 b) internal pure returns (uint256) {
    if (a == 0) {
      return 0;
    }
    uint256 c = a * b;
    assert(c / a == b);
    return c;
  }
```
isn't written like this:
```
  function mul(uint256 a, uint256 b) internal pure returns (uint256) {
    if (a == 0 || b == 0) {
      return 0;
    }
    uint256 c = a * b;
    assert(c / a == b);
    return c;
  }
```

Why not check for b == 0 in the first if and return?

- [ ] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.
- [X] ?  This is a question.

**Comment by elopio** [comment]
Take a look at the pull request that added this check:
https://github.com/OpenZeppelin/openzeppelin-solidity/pull/522

The comments in there discuss exactly your question.

**Comment by jeffreydwalter** [comment]
Makes sense. Thanks! Is it really that rare to have b == 0? I'd be curious (but not too curious) to see a comparison of b == 0 with an explicit check and without.

**Comment by elopio** [comment]
@emn178 [here](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/522#issuecomment-340451322) is assuming that most cases will be non-zero, which sounds reasonable. So this is about gas cost for this case, not about how rare is b = 0 compared to a = 0.
You can use remix as they did in the PR to satisfy your curiousity :)
