### ISSUE TITLE
Contracts using old-style constructors.

### ISSUE THREAD

**Issue by ahester57** [OpenZeppelin/openzeppelin-solidity#932]
## 🎉 Description

- [ ] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.
- [x] 💻 This is a suggestion for the future.

Constructor functions for contracts still using the form:
```solidity
  function <Contract_Name>(<params>) {}
```
Instead of the new constructor style with Solidity 0.4.23:
```solidity
  constructor(<params>) {}
```

## 💻 Environment

Truffle 4.1.8
Solidity 0.4.23

## 📝 Details

We should adopt the new constructor style since it will still throw deprecation warnings in future releases of Solidity.

## 👍 Other Information

https://solidity.readthedocs.io/en/v0.4.23/contracts.html#creating-contracts

**Comment by roschler** [comment]
I noticed this too when I saw the deprecated constructor warnings in Remix when I compiled a contract that inherits from Ownable.

**Comment by AleksanderPopov** [comment]
@ahester57 we should replace 'old-style' constructors in all contracts with new, and update pragma to 0.4.23, is this correct?

**Comment by frangio** [comment]
Note that work on this has begun in #921.

As mentioned there, we have a policy of waiting at least a month after a Solidity release to move to it.
