### ISSUE TITLE
Questions about burn() function in 

### ISSUE THREAD

**Issue by roschler** [OpenZeppelin/openzeppelin-solidity#934]
I and too new to both Solidity coding and the Open Zeppelin library be forking anything in this great project and attempting a pull request.  But after reading this medium article that talks about your ERC721 implementation:

https://medium.com/blockchannel/walking-through-the-erc721-full-implementation-72ad72735f3c

I do have some questions about the _burn()_ function in this full implementation of the ERC721 standard.  If I should have simply posted this in the Open Zeppelin slack instead then my apologies in advance.  If so, please go ahead and close this issue and I will do exactly that.

Given the code for the burn() function below, taken from:

https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/ERC721Token.sol

    function _burn(address _owner, uint256 _tokenId) internal {
        super._burn(_owner, _tokenId);

        // Clear metadata (if any)
        if (bytes(tokenURIs[_tokenId]).length != 0) {
        delete tokenURIs[_tokenId];
        }

        // Reorg all tokens array
        uint256 tokenIndex = allTokensIndex[_tokenId];
        uint256 lastTokenIndex = allTokens.length.sub(1);
        uint256 lastToken = allTokens[lastTokenIndex];

        allTokens[tokenIndex] = lastToken;
        allTokens[lastTokenIndex] = 0;

        allTokens.length--;
        allTokensIndex[_tokenId] = 0;
        allTokensIndex[lastToken] = tokenIndex;
    }

I have these two questions:

1)  In the calculation of _lastTokenIndex_, why isn't there a check to see if _allTokens.length_ is 0, so that the subsequent subtraction operation _.sub(1)_ does not cause an arithmetic error resulting in a potentially invalid value for _lastTokenIndex_?

2) Why is the decrement operator being used on _allTokens.length_ instead of the _sub(1)_ method and again, why is there no check to see if it is already zero first?

**Comment by nedodn** [comment]
1. If you look into the contracts that ERC721Token.sol inherits from, you'll see `using SafeMath for uint256;` in ERC721BasicToken.sol. The Safe Math library checks to make sure that the subtraction operation is valid and prevents an invalid value for `lastTokenIndex`, it would throw if `allTokens.length` was zero.

2. Not sure why they switched to using the decrement operator here instead of using `.sub(1)`, but the previous use of `.sub(1)` checks that the value is at least zero so they may not have felt it necessary to include it again.

**Comment by roschler** [comment]
I see what you're saying about allTokens.length being protected at the operation level by SafeMath.  But that's not what I meant with my question about that.  I'm more concerned about what conditions would lead to attempting to do a "sub(1)" from _allTokens.length_ if it is _already_ zero length.  That seems to indicate a failure in the logic flow that needs handling rather than the simple protection of the _lastTokenIndex_ at the arithmetic leve.

If not, then there are two distinct pathways that can lead to _lastTokenIndex_:

1) _allTokens_ has one element in it at the time of execution (length = 1)
2) _allTokens_ is empty at the time of execution (length = 0)

In both cases, this will lead to _lastTokenIndex_ resolving to a value of 0.   I just don't see how this could be "logically sound".  It would seem to worthy of a protective _assert()_ at least that checks that the _allTokens_ is not of zero length, or there could be unintended consequences.

**Comment by roschler** [comment]
@nedodn That's what I didn't think about, thanks.  My fault.  SafeMath.sub() will cancel the transaction if there is an attempt to subtract from an already zero value.

**Comment by elopio** [comment]
Thanks for the answer @nedodn! I'm closing this one, but feel free to send more questions @roschler.
