### ISSUE TITLE
 ParserError: Expected token Semicolon got 'LParen'

### ISSUE THREAD

**Issue by jkDina** [OpenZeppelin/openzeppelin-solidity#939]
## 🎉 Description
truffle version 4.0.5
"zeppelin-solidity": "^1.4.0"

There is a error after I do "truffle compile":

Error parsing zeppelin-solidity\contracts\token\ERC20\StandardToken.sol: ParsedContract.sol:33:18: ParserError: Expected token Semicolon got 'LParen'
    emit Transfer(_from, _to, _value);

Code is:
"pragma solidity ^0.4.18;
import "zeppelin-solidity\contracts\token\ERC20\StandardToken.sol";
contract mytoken is StandartToken {}"

What can be a problem?

- [ ] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 💻 Environment

Next, we need to know what your environment looks like.

- Which version of OpenZeppelin are you using?
- What network are you deploying to? Ganache? Ropsten?
- How are you deploying your OpenZeppelin-backed contracts? truffle? Remix? Let us know!

## 📝 Details

Describe the problem you have been experiencing in more detail. Include as much information as you think is relevant. Keep in mind that transactions can fail for many reasons; context is key here.

## 🔢 Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

```
insert short code snippets here
```

**Comment by nedodn** [comment]
You need to update your version of truffle so you can have a newer version of solc. Using emit for events wasn't added until solidity 0.4.21 and it looks like truffle 4.0.5 uses solidity 0.4.18.

**Comment by frangio** [comment]
As @nedodn said, you seem to be using too old a Truffle version.

Additionally, please update your OpenZeppelin dependency to `"openzeppelin-solidity": "1.9.0"`.

**Comment by shadab14meb346** [comment]
I was having the issue and solved by updating the truffle version.
