### ISSUE TITLE
Contribution Guidelines: Add remote from original OpenZeppelin repo into one's forked repo before fetching upstream

### ISSUE THREAD

**Issue by dougiebuckets** [OpenZeppelin/openzeppelin-solidity#941]
## 🎉 Description

In the Contribution Guidelines under the "A typical workflow" section, it might be worth including another step that mentions the need to add a remote from the original OpenZeppelin repo into one's forked repo. I.e., 

cd openzeppelin-solidity
**git remote add upstream https://github.com/OpenZeppelin/openzeppelin-solidity.git**
git fetch upstream
git checkout development
git pull --rebase upstream development

- [X]  This is a chore

## 💻 Environment

Next, we need to know what your environment looks like.

- Which version of OpenZeppelin are you using?
- What network are you deploying to? Ganache? Ropsten? Ganache
- How are you deploying your OpenZeppelin-backed contracts? truffle? Remix? Let us know! Truffle

Should be labeled as "Good first issue"

**Comment by dougiebuckets** [comment]
@Heph789 I've been wondering about that, too...

**Comment by elopio** [comment]
Thanks for the report! It would be great if one of you make a PR for adding the upstream and one for removing the development references.
