### ISSUE TITLE
SampleCrowdsale.sol deploy error in Remix

### ISSUE THREAD

**Issue by joejoker77** [OpenZeppelin/openzeppelin-solidity#947]
Hi. I'm trying to deploy SampleCrowdsale.sol from example. I do this in IDE Remix + MetaMask and try to deploy it on the Ropsten network. I receive an error: gas required exceeded allowance or always failing transaction at chrome-extension ... But in a test, local network, with the help of a truffle, there is no such error. Is it possible at all to deploy this contract using the mix of Remix + Metamask + Ropsten? Or is it error belongs Remix?

**Comment by joejoker77** [comment]
I apologize, the problem is definitely not in contracts

**Comment by jjperezaguinaga** [comment]
@joejoker77 did you manage to find what was the issue? Stumbled upon the same problem, only in Remix though.
