### ISSUE TITLE
Invalid token amount in Crowdsale buyTokens function

### ISSUE THREAD

**Issue by vittominacori** [OpenZeppelin/openzeppelin-solidity#953]
## 🎉 Description

Invalid token amount in Crowdsale buyTokens function.

- [x] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 💻 Environment

It is for all OpenZeppelin versions, using all networks and all deployment tools.

## 📝 Details

Hi guys, I don't know if this could be considered as an issue or not.

My question is: 
if token has not 18 decimals (but for instance 10), how the **[_getTokenAmount](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/crowdsale/Crowdsale.sol#L186)** function should work?

It is using **_weiAmount** to multiply with **rate** and it means that we are using a 18 decimals number to calculate the token amount to transfer or mint to the beneficiary. 
So if my token has 10 decimals (instead of 18 like the weiAmount) I will transfer about 8 decimals less of tokens than expected. And 8 decimal less means 10^8 tokens more than expected...

It is as described or am I missing something?

## 🔢 Code To Reproduce Issue

Deploy a MintableToken with 10 decimals.
Start a MintedCrowdsale with a rate of 1.
Then send 0.5 ETH to the Crowdsale.
**It returns 50,000,000 of tokens instead of 0.5.**

Function to investigate is:

```
function _getTokenAmount(uint256 _weiAmount)
    internal view returns (uint256)
{
    return _weiAmount.mul(rate);
}
```

**Comment by Heph789** [comment]
Did you send .5 wei to the crowdsale or .5 ETH? Because the crowdsale operates in wei. So if you set the rate to 1, you're really saying 1 token for 1 wei. So if .5 ETH is put in, the amount of tokens returned should be way more than .5. 1 ETH = 10^18 wei. The amount of tokens returned should be .5 * 10^18 or 5 * 10^17. But the amount of tokens actually returned was 5 * 10^7. There's still a problem here, but there are too little tokens instead of too many I think.

**Comment by vittominacori** [comment]
I sent .5 Ether to a crowdsale with a rate of 1.
And crowdsale mints for me 50,000,000 of tokens.

The problem is that weiAmount is N * 10^18 and when crowdsale [transfers](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/crowdsale/Crowdsale.sol#L147) or [mints](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/crowdsale/emission/MintedCrowdsale.sol#L25) the numbers of token is passed to mint or transfer function and that number has not the same decimals of a token with 10 decimals.

So .5 * 10^18 is greater than .5 * 10^10.

I think **rate** is not for wei otherwise if we want to give 1 token for 1 ETH we should set rate as 1 * 10^18 or 1 * 10^10 in my sample?

In this case the multiplication `_weiAmount.mul(rate);`  will be a very high number.

I think that the _getTokenAmount function doesn't apply if token decimals are not equal to 18.

**Comment by Heph789** [comment]
I think I'm kind of getting what you're trying to say. Let me run a hypothetical by you and see if I understand what you're saying.

    GenericToken (GT) sets up a crowdsale with a rate of 1 wei per GT. GenericToken has 3 decimals. The creators of GenericToken sets up the crowdsale using Crowdsale.sol with a rate of 1 without realizing that Crowdsale.sol does not account for decimals.
    A man named "Bob" spends 5 wei and expects to receive 5 GT in return. Bob looks in his Mist wallet and instead finds that he only has .005 GT, or 5 of the smallest unit of GT.

**Comment by vittominacori** [comment]
I think the below function can help in some cases.

```
pragma solidity ^0.4.24;

import "openzeppelin-solidity/contracts/crowdsale/emission/MintedCrowdsale.sol";
import "openzeppelin-solidity/contracts/token/ERC20/DetailedERC20.sol";


contract MyCrowdsale is MintedCrowdsale {
    constructor(
        uint256 _rate,
        address _wallet,
        ERC20 _token
    )
    Crowdsale(_rate, _wallet, _token)
    public
    {

    }

    function _getTokenAmount(uint256 _weiAmount) internal view returns (uint256) {
        uint256 tokenDecimals = DetailedERC20(token).decimals();
        uint256 etherDecimals = 18;

        if (tokenDecimals < etherDecimals) {
            return _weiAmount.mul(rate).div(10 ** (etherDecimals.sub(tokenDecimals)));
        }

        if (tokenDecimals > etherDecimals) {
            return _weiAmount.mul(rate).mul(10 ** (tokenDecimals.sub(etherDecimals)));
        }

        return _weiAmount.mul(rate);
    }
}
```

With low decimals amount (like 1), solidity will approximate the generated token amount.
For instance with 1 decimal, sending 0.099999 ETH, will generate 0 tokens.
So it is not a definitive solution.

If this could be a starting point I could try to write tests and a way to understand if token is a DetailedERC20. In the real world any ERC20 should have decimals, but this is a lib and should cover all the cases.

**Comment by Heph789** [comment]
But if you send 1 ether, with a rate of 1, the expected GT units received should be 10^18, or 10^15 GT. It just needs to be made clear that the rate is how many units of token per wei.

**Comment by elopio** [comment]
Just like on ethereum, where you have a unit called ether, but all the transaccions are done using the smaller undivisible unit, called wei; on Tokens we have an undivisible unit. The standard token adds the decimals and a name for the token, that would be similar to what we do with ether, mostly to have a way to show it nicely without that many zeroes. But the rate is a correspondence between wei and the smallest token unit.

Does this make sense? I'm relatively new here, so please let me know if not.

**Comment by vittominacori** [comment]
Yes it is. 
Issue happens when token hasn't 18 decimals like Ether because of the mul between wei and rate returns a number that is intended to have 18 decimals but, token may have not them, so we can't show nicely.
Do you think that the `_getTokenAmount` I designed above could help solve this issue?

**Comment by elopio** [comment]
I'm not sure I follow you there.
I don't see how the decimals affect the multiplication. You pay an amount of wei. In exchange, you receive an amount of tokens on the smallest unit they have. You can then convert this amount of tokens to the token unit you want. 

I'm failing to see what do you mean with "can't show nicely". Sorry if I'm being dense, feel free to jump into the openzeppelin slack if you think that will make communication easier.

**Comment by vittominacori** [comment]
The [getTokenAmount](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/crowdsale/Crowdsale.sol#L186) function multiply weiAmount and rate.

If token has not 18 decimals the number of units will be considered to have 18 decimals (like the ether because of we are multiplying for the wei amount) but token can have a different numbers of decimals and we can have this issue:

https://rinkeby.etherscan.io/tx/0xa6c8cd7b3aefe1f5fdc28827c7899bfe253fd56a401edb2c7c85f5b966c7da7b

In this transaction token has 3 decimals and crowdsale has a rate of 1.
I know that rate is for the smaller token unit but I can't set a rate less than 1 to adjust the token decimals.
Ideally if I send 1 Ether I should expect 1 token (not a unit but a token with 3 zero units) but I receive 10^15 that is 18 - 3 (ether decimals - token decimals). 
So 1,000,000,000,000,000 token received.
Is that right?

If I would receive 1 token (so in this example 1000 units) how can I set a rate that can handle also the right amount of decimals?
I will join slack but it's night in Italy so tomorrow :)

**Comment by elopio** [comment]
> Ideally if I send 1 Ether I should expect 1 token (not a unit but a token with 3 zero units)
Here is where I disagree. If you send 1 ether = 1000000000000000000 wei, and the rate is 1, you should get 1000000000000000000 of the smallest unit of the token. This is how it is supposed to work. 

The concepts of Ether and token decimals are just syntactic sugar if you don't want to use that many zeroes. But they shouldn't be involved in the implementation of the code.

Talk to you tomorrow. I'm elopio in slack too.

**Comment by vittominacori** [comment]
Definitely we shouldn't build the code thinking about Ether but only about Wei.
So be careful when you choose your decimals amount.

**Comment by sebastien-kr** [comment]
This non-issue should be closed.
