### ISSUE TITLE
Is "require(_value <= balances[msg.sender]);" useless?

### ISSUE THREAD

**Issue by rushairer** [OpenZeppelin/openzeppelin-solidity#954]
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/746673a94f7e43835fcb5cb7b1af8ff1eea4e276/contracts/token/ERC20/BasicToken.sol#L33

Is "require(_value <= balances[msg.sender]);" useless?
Thanks!

**Comment by hadv** [comment]
why do you think it's useless? 

I think that it's necessary to check the balance of the sender have enough fund to send or not. if not then throw error.

**Comment by ahester57** [comment]
@rushairer sure, SafeMath with its assert(b<=a) will cause a revert, and the require adds another line of code. But waiting for SafeMath to cause the revert will end up consuming more gas than if we revert before making the external call.

**Comment by rushairer** [comment]
@hadv @ahester57 
Thank you!

**Comment by elopio** [comment]
Thanks for your question @rushairer. See some more discussion about it in #611.
I'm closing this, but let us know if you have further questions.

**Comment by rushairer** [comment]
I think that Dapps can call "balanceOf" without gas to get the balance of the sender before "transfer".
If the user is intentionally paying more than his own amount, why we should save the gas for him?
And one more line code cause every need pay more gas, Is it fair？
