### ISSUE TITLE
RBAC with owner 

### ISSUE THREAD

**Issue by 4000D** [OpenZeppelin/openzeppelin-solidity#962]
## 🎉 Description

- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

## 📝 Details

`Ownable` controls ownership of contract. I think `RBACWithOwner` is suitable to control access controll with permission than `RBACWithAdmin`. `RBACWithAdmin` has several problems.

1. It can't be integrated with `Ownable` becuase both control permissions. If we have a contract `T is RBACWithAdmin, Ownable` and a single `admin` added, and want to chagne `owner`, 3 transaction are required
```javascript
contract.transferOwnership(newOwner, {from: owner});
contract.adminAddRole(newOwner, 'admin', {from: owner});
contract.adminRemoveRole(owner, 'admin', {from: owner});
```

2. `RBACWithAdmin` may have no `admin` at all if `admin` send trancation
```javascript
contract.adminRemoveRole(admin, 'admin', {from: admin});
```

I suggest to integrate `Ownable` with `RBACWithAdmin` to handle `owner` and `ROLE_ADMIN` at the same time, making sure that `owner` has all permission to control `ROLE_ADMIN`

**Comment by shrugs** [comment]
Thanks for the issue! 

`RBACWithAdmin` will be moved to the examples folder; it's just too powerful 😂 see: https://github.com/OpenZeppelin/openzeppelin-solidity/pull/936#issuecomment-393050257

`RBACOwnable` will be introduced as part of https://github.com/OpenZeppelin/openzeppelin-solidity/pull/950 , but without a focus on backwards compatibility with `Ownable.sol`. We previously tested a backwards-compatible version of `RBACOwnable.sol` but decided that it wasn't a good enough solution.

**Comment by frangio** [comment]
Closing as we've removed the previous `RBAC` and our focus is on Roles now.
