### ISSUE TITLE
[crowdsale] inheriting multiple contracts may cause unpredictable behavior

### ISSUE THREAD

**Issue by sebastien-kr** [OpenZeppelin/openzeppelin-solidity#963]
## 🎉 Description

When using multiple crowdsale contracts to add features, it looks like there are some problems / conflicts.
It _may_ be due to the order of the inheritance, and the right order _may_ be incompatible with the linearization of the inheritance graph.  

- [x] 🐛 This is a bug report.

## 💻 Environment

- Which version of OpenZeppelin are you using?
1.9.0 freshly cloned to confirm the problem.

- What network are you deploying to? Ganache? Ropsten?
Ganache

- How are you deploying your OpenZeppelin-backed contracts? truffle? Remix? Let us know!
Truffle.

## 📝 Details

When building crowdsales, one may want to add some features.
In this case, I added `TimedCrowdsale, CappedCrowdsale, RefundableCrowdsale, WhitelistedCrowdsale, Claimable`.  

1. **First problem :** 
Finding the right order is tricky and NOT documented. Let say you want to put `TimedCrowdsale` before `WhitelistedCrowdsale` :**_BOOM_** `solidity linearization of inheritance graph impossible`. 

2. **Second problem, the one that motivates this issue :**
When testing the code, I had some weird `revert` going on while trying to buy tokens.  
At some point, I simply copy/pasted a sample contract in a fresh openzeppelin-solidity clone to confirm, and yes : the smart contract is unable to complete the tests from `WhitelistedCrowdsale`.

```
  1) Contract: TimedWhitelistedCappedRefundableCrowdsale
       single user whitelisting
         accepting payments
           should accept payments to whitelisted (from whichever buyers):
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: VM Exception while processing transaction: revert'


  2) Contract: TimedWhitelistedCappedRefundableCrowdsale
       many user whitelisting
         accepting payments
           should accept payments to whitelisted (from whichever buyers):
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: VM Exception while processing transaction: revert'


  3) Contract: TimedWhitelistedCappedRefundableCrowdsale
       many user whitelisting
         accepting payments
           should reject payments to addresses removed from whitelist:
     AssertionError: expected promise to be fulfilled but it was rejected with 'Error: VM Exception while processing transaction: revert'
```

## 🔢 Code To Reproduce Issue [ Good To Have ]

Everything is in this commit : https://github.com/sebastien-kr/ozs-crowdsale-test/commit/dbab70b1e31b81feaaad36f32e8d7b3de8586413

Here is what I did : 

 1. Clone `openzepelin-solidity`
 2. Create `contracts/TimedWhitelistedCappedRefundableCrowdsale.sol` with the code below
 3. Create it's `mock` and `test` files. (tests from WhitelistedCrowdsale)
 4. Remove all other test files. Updated the readme.
 5. Launch `npm install && npm test` and watch the test fail.

```
pragma solidity ^0.4.21;

import "./crowdsale/validation/CappedCrowdsale.sol";
import "./crowdsale/validation/WhitelistedCrowdsale.sol";
import "./crowdsale/distribution/RefundableCrowdsale.sol";
import "./crowdsale/validation/TimedCrowdsale.sol";
import "./ownership/Claimable.sol";

import "./examples/SimpleToken.sol";


contract TimedWhitelistedCappedRefundableCrowdsale is TimedCrowdsale,CappedCrowdsale,RefundableCrowdsale,WhitelistedCrowdsale,Claimable{
    
    function TimedWhitelistedCappedRefundableCrowdsale(
        uint _softCap, 
        uint _hardCap, 
        uint _startTime, 
        uint _endTime,
        uint _rate, 
        address _wallet,
        SimpleToken _token
    ) public
    Crowdsale(_rate, _wallet, _token)
    TimedCrowdsale(_startTime, _endTime)
    CappedCrowdsale(_hardCap)
    RefundableCrowdsale(_softCap)
    WhitelistedCrowdsale
    Claimable
    {

    }


}
```

## 👍 Other Information

Ideally I would have loved to check a bit further myself to see if there is something to do with the orther of the inheritance and / or find which ones are starting to fail the test... But at this point I think it needs someone that can take a fresh look and see the obvious out of it.

**Comment by elopio** [comment]
Hello @sebastien-kr. Thanks for your report.

It seems to me that your tests are failing because you are not advancing the time to the start time. Take a look at the TimedCrowdsale tests:
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/test/crowdsale/TimedCrowdsale.test.js#L51

Here's our accompanying post to those crowdsale tests: 
https://blog.zeppelin.solutions/on-crowdsales-and-multiple-inheritance-af90c694e35f

If you have some proposals to improve the code documentation to make these details clearer, please send a PR.

**Comment by sebastien-kr** [comment]
Hello @elopio. 

You are right, I forgot to add it to the demo. 
Unfortunately, after commiting the completed code and added an extra `advanceBlock` just in case : Same result.

And sure, I will see how to contribute to the docs :-) 
Thank you.
