### ISSUE TITLE
Inherit CanReclaimToken in ERC20 StandardToken contract

### ISSUE THREAD

**Issue by subramanianv** [OpenZeppelin/openzeppelin-solidity#976]
## 🎉 Description

Tokens get locked in the contracts. It is better to inherit CanReclaimToken in the StandardToken contract
- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

**Comment by shrugs** [comment]
I don't know if it's up to us to enforce that Standard token inherits from `CanReclaimToken`. Implementers are free to inherit from it as well, of course.
