### ISSUE TITLE
WhitelistedCrowdsale always reverts on send()

### ISSUE THREAD

**Issue by sebastien-kr** [OpenZeppelin/openzeppelin-solidity#979]
## 🎉 Description

The `WhitelistedCrowdsale` contract reverts when calling it using `send()` instead of `buyTokens()`.  

Behaviour confirmed via `npm test` using `ganache-cli`.
  
- [x] 🐛 This is a bug report.

## 💻 Environment
- openzeppelin-solidity commit https://github.com/OpenZeppelin/openzeppelin-solidity/commit/a0c03ee61cdb77327f2435ba2ab1c539b1d34774

## 📝 Details

I did check the comments in the code and the medium posts, and found nothing about this behaviour even though it looks like this is a known issue as the tests are written in a way that uses `send()`  **only** for tests that are expected to revert.

(See : https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/test/crowdsale/WhitelistedCrowdsale.test.js )

## 🔢 Code To Reproduce Issue
1. Clone this repository at commit a0c03ee
1. Insert this line before line 27 of `test/crowdsale/WhitelistedCrowdsale.test.js`
```javascript
await this.crowdsale.send(value, { from: authorized }).should.be.fulfilled;
//Line 28 should be as follow : 
await this.crowdsale.buyTokens(authorized, { value: value, from: authorized }).should.be.fulfilled;
```
1. run `npm test`
1. Enjoy the `AssertionError: expected promise to be fulfilled but it was rejected with 'Error: VM Exception while processing transaction: revert'`

**Comment by shrugs** [comment]
found the issue! truffle-contract's `send()` function is bad software and doesn't accept an options hash like every other method in the library, so the sender of that transaction is always the default account, which is not authorized and therefore fails the whitelist check.

sending a normal transaction is the move. I'll have a PR for this in a few minutes.

**Comment by shrugs** [comment]
https://github.com/trufflesuite/truffle-contract/blob/develop/contract.js#L321

**Comment by shrugs** [comment]
Thank you for your very detailed bug report!! <3
