### ISSUE TITLE
Where is the openzepplin-zos repository?  Unable to find it anywhere on GitHub.

### ISSUE THREAD

**Issue by roschler** [OpenZeppelin/openzeppelin-solidity#982]
UPDATE: I see that the `openzeppelin-solidity` issue also has a _node_modules_ directory with the `MintableERC721Token.sol` contract I describe below.  But if I look in that GitHub repo, I can't find that contract and many others that I do find in the _node_modules_ directory for the `openzeppelin-solidity` package.  It's like a whole set of contract distributed with the `openzeppelin-solidity` and `openzeppelin-zos` packages can't be found on GithUb.

I am posting this issue in the `openzeppelin-solidity` Issues forum because _I literally can't find the `openzeppelin-zos` GitHub repository_.  When you install the `openzeppelin-zos` package, you get the ZeppelinOS smart contract library:

https://www.npmjs.com/package/openzeppelin-zos

In the _node_modules_ directory for that package you find many important contracts, like the one I was looking for on GitHub that triggered this post:

```/node_modules/openzeppelin-zos/contracts/tokenMintableERC721Token.sol```

However, I can't find _any_ Open Zeppelin authored repository that contains that library of contracts.  If you go to the NPM package page for `openzeppelin-zos`:

https://www.npmjs.com/package/openzeppelin-zos

You discover that except for the page title, the rest of that page is for the `openzeppelin-solidity` package, including the GitHub repo link that goes to the `openzeppelin-solidity` repo, _not_ the `openzeppelin-zos` repo, which as I said I can't find anywhere.

Where is the `openzeppelin-zos` repo?

**Comment by alegw** [comment]
You're looking for https://github.com/zeppelinos/zos-lib

**Comment by frangio** [comment]
Hi @roschler, the package is currently at the branch [OpenZeppelin/openzeppelin-solidity#zos-release](https://github.com/OpenZeppelin/openzeppelin-solidity/tree/zos-release). We're still figuring some of this out, and we may move the package to its own repository soon. I'll make sure to let you know!

**Comment by roschler** [comment]
@frangio Thanks.  That explains it:

https://github.com/OpenZeppelin/openzeppelin-solidity/tree/zos-release/contracts/token/ERC721

**Comment by terencechow** [comment]
None of the links work anymore...

**Comment by frangio** [comment]
@terencechow Please take a look at [OpenZeppelin/openzeppelin-zos](https://github.com/OpenZeppelin/openzeppelin-zos). I will update the links.

**Comment by terencechow** [comment]
Thanks. FYI the npm package points here as well.
