### ISSUE TITLE
Do not repeat natspec tags at the start of the line

### ISSUE THREAD

**Issue by elopio** [OpenZeppelin/openzeppelin-solidity#986]
## 🎉 Description

On the natspec docstrings everywhere on openzeppelin solidity we are repeating the tag at the start of every line.

Like we do for `@dev` in this example:

```
/**
 * @title SignatureBouncer
 * @author PhABC and Shrugs
 * @dev Bouncer allows users to submit a signature as a permission to do an action.
 * @dev If the signature is from one of the authorized bouncer addresses, the signature
 * @dev is valid. The owner of the contract adds/removes bouncers.
[...]
```

This is unnecessary, and makes the comment uglier and harder to write and maintain.
We should leave only the first `@dev` tag and remove the repeated ones.

- [x] 🐛 This is a bug report.

## 📝 Details

On https://github.com/zeppelinos/zos-lib/pull/95#discussion_r190130341 we were discussing about it and made a quick check to confirm that it's not necessary to repeat the tag.

**Comment by shrugs** [comment]
I had a question about that ages ago, and the result was to prefix all of the lines. The natspec spec itself doesn't clarify multi-line very well, but now that I check again, it doesn't do anything specific for this multi-line `@notice`: https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format#documentation-output
