### ISSUE TITLE
Feedback From Open Zeppelin About ERC-173 Contract Ownership Standard

### ISSUE THREAD

**Issue by mudgen** [OpenZeppelin/openzeppelin-solidity#987]
A new proposal/draft for the contract interface for owning and transferring ownership of contracts was recently written and merged with the ethereum eip project. The draft is here: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-173.md

What is Open Zepplin's response/feedback about this?

Also, can Open Zepplin help get the word out about contract ownership becoming standardized? Get the word out about this EIP draft so it can get the feedback it needs for standardization.

**Comment by frangio** [comment]
Hi there, @mudgen.

An important piece of feedback is that the semantics of the functions and events don't seem to be specified at all.

**Comment by mudgen** [comment]
@frangio thank you for your comment.  I noticed that the @notice for the `transferOwnership()` function was wrong so I fixed that and will be in the next pull request. 

The notice for the  `transferOwnership()` function now says, "Set the address of the new owner of the contract".  The notice for the `owner()` function says, "Get the address of the owner " Are more semantics needed? If so can you give me more idea of the semantics that should be included?

Implementations of functions `owner()` and `transferOwnership()` are unspecified because they can be implemented how people want to implement them. But the standard does link to Open Zepplin's implementation of the standard as an example.

**Comment by frangio** [comment]
Closing as discussion should be happening in https://github.com/ethereum/EIPs/issues/173.
