### ISSUE TITLE
Whitelist.sol should live in /access

### ISSUE THREAD

**Issue by shrugs** [OpenZeppelin/openzeppelin-solidity#988]
## 🎉 Description

title says it; move Whitelist.sol to /access and update all references.

- [x] 🐛 This is a bug report.

**Comment by arun1595** [comment]
@shrugs I would like to work on this!

**Comment by arun1595** [comment]
@shrugs Submitted a [PR](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/994)

Check it out when you get a chance.

Thanks!
