### ISSUE TITLE
Make ERC721 interfaces abstract again

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-solidity#990]
The ERC721 interfaces should probably be deriving the interface `ERC165` instead of the implementation `SupportsInterfaceWithLookup`.

https://github.com/OpenZeppelin/openzeppelin-solidity/blob/b0292cf628d9f8d65615bc07dd8af4844eb5a6d6/contracts/token/ERC721/ERC721Basic.sol#L10

The logic for registering the proper interfaces should then be moved to the implementations.
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/b0292cf628d9f8d65615bc07dd8af4844eb5a6d6/contracts/token/ERC721/ERC721Basic.sol#L47-L53

**Comment by shrugs** [comment]
Ah, true, good point. will update today.
