### ISSUE TITLE
Stop using syncronous HTTP requests

### ISSUE THREAD

**Issue by LogvinovLeon** [OpenZeppelin/openzeppelin-solidity#999]
## 🎉 Description

- [x] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

It's kinda both.

## 📝 Details

Syncronous HTTP requests are deprecated in upcoming web3 version and provider-engine doesn't support them.
We use them in tests extensively, but it's mostly `web3.eth.getBalance`.
Let's remove them and be future-proof!

**Comment by arun1595** [comment]
@LogvinovLeon I'm on it!

**Comment by frangio** [comment]
I would love to move to async code but the problem is web3.js 0.x uses callbacks instead of promises. I wouldn't want the tests to be ridden with callbacks so we would have to promisify it somehow. @arun1595 keep that in mind!

**Comment by LogvinovLeon** [comment]
https://www.npmjs.com/package/es6-promisify

**Comment by arun1595** [comment]
@LogvinovLeon I've promisified the synchronous `web3.eth.getBalance` calls in the tests. Take a look at my [PR](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1009) when you get a chance.

Thanks!
